OCD-3481 : Complaints reporting
chpladmin/chpl-website pull request #1003
Opened 2022-01-05 19:41 UTC by palakpatel311

2022-01-07 19:28 UTC, ashwinimore requested changes

2022-01-07 19:28 UTC, ashwinimore commented on e2e/components/surveillance/complaints/complaints.readonly.spec.js
> +            expect(hooks.getCellValue(i,6)).toBe('Other - [Please Describe]');
will this test work when the data changes so that there are more closed complaints of Complainant Type 'Other - [Please Describe]' or 'Patient'? I ask this because there are closed complaints for Patient Complainant Type which is one of the applied filter, and when there are more complaints added, the value in row 6 may change

2022-01-09 19:58 UTC, palakpatel311 commented on e2e/components/surveillance/complaints/complaints.readonly.spec.js
> +            expect(hooks.getCellValue(i,6)).toBe('Other - [Please Describe]');
You are right. Updated assertion

2022-01-10 14:23 UTC, ashwinimore submitted a review, later dismissed

2022-01-10 14:31 UTC, athomas-git submitted a review, later dismissed

2022-01-10 14:49 UTC, andlar requested changes

2022-01-10 14:49 UTC, andlar commented on e2e/components/surveillance/complaints/complaints.po.js
> +    return $('chpl-complaint-view-bridge').$('div').getText();
Is there any other locator that we can use instead of the `-bridge` type? These components are temporary ones that will go away as we transition to React, and I'd rather not rely on them now if we can avoid it

2022-01-10 14:49 UTC, andlar commented on e2e/components/surveillance/complaints/complaints.po.js
> +      browser.pause(2000);
Is there any other way of doing this pause? Using the `browser.waitUntil` function or something? This could get stuck in an infinite loop otherwise

2022-01-10 14:49 UTC, andlar commented on e2e/components/surveillance/complaints/complaints.readonly.spec.js
> +        const oncAcbComplaintID_IDX = '4';
There's not much point in putting these `const`s outside of the `it` they're used in, as these aren't used in more than one it, as opposed to the `FIRST_ROW` constant above

2022-01-10 14:49 UTC, andlar commented on e2e/components/surveillance/complaints/complaints.po.js
> +  setOptional(fields) {
I had to go look at where this function is used to figure out what it does. Can we name it something that is more descriptive of what it does? Maybe `setOptionalFields`?

2022-01-10 14:49 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/atls.readonly.spec.js
> +  xdescribe('when impersonating as UL', () => {
Does this need to be ignored? Can we impersonate a different user to keep these tests going?

2022-01-10 17:01 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/atls.readonly.spec.js
> +  xdescribe('when impersonating as UL', () => {
I had to change bunch of things on this test to make it run as we dont show ROLE_ATLs under user management anymore. But it works now and removed skip label.

2022-01-11 13:10 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/atls.spec.js
> +import UsersPage from '../../users/users.po';
If we're not on the Users Page, then we should be using the Users component, not the Users Page. This import should be to the components/user/user.po.js file. The component that's being imported has a "pageTitle" element that doesn't exist on the organizations pages, which is an indication the wrong page object is being used

2022-01-11 13:10 UTC, andlar commented on e2e/pages/users/users.po.js
> +    $(`//*[contains(@title, 'Impersonate ${name}')]`).click();
This one _could_ be here, because we _can_ impersonate from the Users page, but it also needs to be on the users component for use when the tests are on an organization page (ACB, ATL, Developer)

2022-01-11 14:51 UTC, palakpatel311 commented on e2e/pages/users/users.po.js
> +    $(`//*[contains(@title, 'Impersonate ${name}')]`).click();
I am hesitant of duplicating same method in both and leaning towards only keeping in UserComponent.

2022-01-11 15:28 UTC, andlar approved these changes, later dismissed

2022-01-11 15:48 UTC, athomas-git approved these changes, later dismissed

2022-01-11 19:35 UTC, ashwinimore submitted a review, later dismissed

2022-01-13 14:34 UTC, athomas-git approved these changes

2022-01-13 14:52 UTC, ashwinimore approved these changes

2022-01-13 15:27 UTC, andlar approved these changes

2022-01-13 16:38 UTC, merged