OCD-3881 - Add Attestation "Requirement" and "Non-Conformity Type" values
chpladmin/chpl-website pull request #1027
Opened 2022-03-09 20:08 UTC by tmy1313

2022-03-10 14:16 UTC, kekey1 submitted a review, later dismissed

2022-03-10 14:45 UTC, andlar requested changes

2022-03-10 14:45 UTC, andlar commented on src/app/components/listing/details/surveillance/requirement/edit.html
> +        <select class="input-sm form-control" ng-model="$ctrl.requirement.requirement" id="requirement-rwt" name="requirement"
This "id" is "requirement-rwt", which doesn't match the name, nor does it match the "for" in the label two lines up. These should all be the same, though I believe "name" is usually camelCase, while the ID is snake-case

2022-03-11 12:44 UTC, tmy1313 commented on src/app/components/listing/details/surveillance/requirement/edit.html
> +        <select class="input-sm form-control" ng-model="$ctrl.requirement.requirement" id="requirement-rwt" name="requirement"
The "id" is definitely wrong.  I think the "name" is correct based on the existing pattern - we only show one of these label/select combos.  There is a block displayed based on what "requirementType" selected (capability, transparency, rwt, attestations).  By all of them using the name "requirement", the selected value maps correctly to the JS code.

2022-03-11 13:05 UTC, andlar approved these changes

2022-03-11 15:49 UTC, ashwinimore commented on e2e/config/urlsEXAMPLE.js
> +  ff4jURL: 'rest/endpoint?api_key=1234abcd'
As line-78 suggests in README above, should this be in a copy e2e/config/urls.js (which is in gitignore, to exclude from commit)?

2022-03-11 18:21 UTC, kekey1 approved these changes

2022-03-13 22:05 UTC, andlar commented on e2e/config/urlsEXAMPLE.js
> +  ff4jURL: 'rest/endpoint?api_key=1234abcd'
This can't be in the urls.js file, because that file is where our _real_ data goes. This is the example file, and the change here was made to show what the actual format of these values should be. The previous version made it hard to tell if a given URL should have a `/` at the end, or have the `http` or `https` or something at the beginning. For the FF4j one, there wasn't anything that made it clear there should / shouldn't be a `/` at the beginning either

2022-03-14 13:54 UTC, ashwinimore approved these changes

2022-03-14 14:34 UTC, athomas-git approved these changes

2022-03-23 13:20 UTC, merged