Ocd 4094 - update to AQA - ignore flaky quarantined tests
chpladmin/chpl-website pull request #1133
Opened 2023-01-17 20:19 UTC by athomas-git

Ocd 4094 - update to AQA - ignore flaky quarantined tests

2023-01-17 20:29 UTC, andlar requested changes

2023-01-17 20:29 UTC, andlar commented on e2e/pages/administration/jobs/scheduled.readonly.spec.js
> +    /*it('should show Retired ONC-ACBs are retired on the scheduling page', () => {
This should be ignored using `xit` ; it's the same idea as the `xdescribe` you're using everywhere else

2023-01-17 20:36 UTC, athomas-git commented on e2e/pages/administration/jobs/scheduled.readonly.spec.js
> +    /*it('should show Retired ONC-ACBs are retired on the scheduling page', () => {
updated the test using xit

2023-01-18 15:30 UTC, andlar submitted a review, later dismissed

2023-01-23 17:33 UTC, ashwinimore approved these changes, later dismissed

2023-01-24 12:34 UTC, andlar approved these changes, later dismissed

2023-02-02 12:51 UTC, andlar approved these changes

2023-02-04 20:03 UTC, ashwinimore approved these changes

2023-02-07 13:38 UTC, merged