OCD-3673: Add aqa tests for system maintenance - standards
chpladmin/chpl-website pull request #1167
Opened 2023-03-30 03:33 UTC by ashwinimore

2023-03-30 12:42 UTC, andlar commented on e2e/components/standards/qms-standard/qms-standard.spec.js
> +      await (browser.waitUntil(async () => component.qmsDataAvailable()));
Can we add, or change, this to use a similar action as the line above where we wait for the number of rows in the table to have changed back to the initial count? I worry that just waiting for the table to exist might get us to a state where the table's there, but the data hasn't refreshed yet, which would make the next line fail

2023-03-30 12:42 UTC, andlar commented on e2e/components/standards/qms-standard/qms-standard.po.js
> +    await rows.forEach(async (row) => {
While I can see this working, the code has to iterate through all of the rows to find the one it needs, then it picks the cell with the button to edit, right? There's a one-line way of doing that I used in the Developer Join AQA. The line I used was:

```
 $(`td=${developerName}`).parentElement().$('button').click();
```

This is not the async version, but my guess is you could wrap that in nested awaits, like I've done in a bunch of the async files.

The other advantage to a path like this is that if the order of the columns changes, or a new one is added, or whatever, the locator doesn't have to move. For that matter, this entire `editSomething` function might be able to be part of the system-maintenance PO, reducing the need to duplicate this function

2023-04-03 14:08 UTC, andlar commented on e2e/components/standards/qms-standard/qms-standard.po.js
> -
Not sure why this line was removed. All the other PO files have a blank line before the final export line

2023-04-03 14:08 UTC, andlar commented on e2e/components/standards/svap/svap.spec.js
> +      await expect(await (await component.svapTable).getText()).toContain(newVersion);
I think we need a "wait" in here before expecting our results. I agree that this probably works, but as a general practice we should wait for something to change, then expect our new something to happen. In the add/delete cases we wait for the table length to change. I recognize that won't work here, but maybe we could wait for the old name to not be found in the table? 

Maybe something like:

```suggestion
      await action.save();
      await browser.waitUntil(async () => (await component.svapTable).getText().not.toContain(version);
      await expect(await (await component.svapTable).getText()).toContain(newVersion);
```

2023-04-03 14:08 UTC, andlar commented on e2e/pages/administration/system-maintenance/system-maintenance.po.js
> +  async editStandards(identifier) {
I love this genericizing action, and we need to take it one step farther, as not all the things in system-maintenance are standards. Maybe:

```suggestion
  async editItem(identifier) {
```

2023-04-05 13:07 UTC, andlar approved these changes, later dismissed

2023-04-05 13:18 UTC, andlar approved these changes, later dismissed

2023-04-05 14:07 UTC, athomas-git submitted a review, later dismissed

2023-04-07 12:22 UTC, athomas-git approved these changes, later dismissed

2023-04-11 11:47 UTC, andlar requested changes
We are really close. Two small things to address and I might be done with comments

2023-04-11 11:47 UTC, andlar commented on e2e/pages/administration/system-maintenance/system-maintenance.po.js
> +    return $(this.elements.addButton);
I know the "addButton" has to be different on each of the descendent pages, so whatever "addButton" locator this page uses probably won't work, but it still needs to be in the elements object. Right now there is no "addButton" in `this.elements`, which would mean that this would be undefined. I could maybe see an argument for leaving it that way, but that opens up a lot of other topics, and the simple fix would be to add a locator to this file that covers it

2023-04-11 11:47 UTC, andlar commented on e2e/pages/administration/system-maintenance/system-maintenance.po.js
> +  async editItem(identifier) {
There are two of these functions in this file

2023-04-11 12:09 UTC, ashwinimore commented on e2e/pages/administration/system-maintenance/system-maintenance.po.js
> +    return $(this.elements.addButton);
agree. I missed that, pushed update for this

2023-04-11 12:10 UTC, ashwinimore commented on e2e/pages/administration/system-maintenance/system-maintenance.po.js
> +  async editItem(identifier) {
agree, that happened in error while consolidating files. Removed duplicate in new commit

2023-04-11 12:29 UTC, andlar approved these changes

2023-04-11 15:03 UTC, athomas-git approved these changes

2023-04-12 13:51 UTC, merged