OCD 4139 : AQA tests for new SVAP Information collection page
chpladmin/chpl-website pull request #1176
Opened 2023-04-27 15:05 UTC by athomas-git

OCD 4139 : AQA tests for new SVAP Information collection page

2023-04-27 16:22 UTC, andlar requested changes

2023-04-27 16:22 UTC, andlar commented on e2e/pages/collections/svap-information/svap-information.po.js
> +      downloadSVAPInformation: '#download-listings',
I don't think this element is needed. If this is the main download button it should be in the CollectionPage PO, but I also don't think we're doing any tests with that button. The API Info page has a page specific button, but there isn't one for SVAP

2023-04-27 16:22 UTC, andlar commented on e2e/pages/collections/svap-information/svap-information.readonly.spec.js
> +      it('should filter on has any SVAP', async () => {
I would suggest using one of the other SVAP filters as a test. I don't know if we're going to keep this one as an available filter at all, and even if we do, the actual SVAP filters are more likely something end users will use, so that's what we should test against

2023-04-28 11:28 UTC, andlar commented on e2e/pages/collections/svap-information/svap-information.readonly.spec.js
> +const config = require('../../../config/mainConfig');
Are these doing anything? I think they're usually imported when there's a file download test, but I don't think we need those in this spec

2023-04-28 13:42 UTC, andlar approved these changes, later dismissed

2023-04-28 15:54 UTC, andlar submitted a review, later dismissed

2023-05-01 16:28 UTC, andlar approved these changes, later dismissed

2023-05-01 16:32 UTC, andlar submitted a review, later dismissed

2023-05-01 20:02 UTC, andlar commented on e2e/pages/collections/svap-information/svap-information.readonly.spec.js
> +    const expectedHeaders = ['CHPL ID', 'Certification Edition', 'Developer', 'Product', 'Version', 'Status', 'SVAP Information', 'SVAP Notice URL', 'Actions'];
```suggestion
    const expectedHeaders = ['CHPL ID', 'Certification Edition', 'Developer', 'Product', 'Version', 'Status', 'SVAP Information', 'SVAP Notice', 'Actions'];
```

Changed the header after talking with the PO. This change should match the updates

2023-05-02 12:18 UTC, andlar approved these changes, later dismissed

2023-05-02 17:46 UTC, ashwinimore approved these changes, later dismissed

2023-05-05 12:04 UTC, andlar approved these changes

2023-05-05 12:17 UTC, ashwinimore approved these changes

2023-05-05 12:18 UTC, merged