OCD-4174: view / search questionable activity
chpladmin/chpl-website pull request #1184
Opened 2023-05-16 12:23 UTC by andlar

2023-05-16 18:07 UTC, ashwinimore approved these changes, later dismissed

2023-05-16 18:48 UTC, athomas-git submitted a review, later dismissed

2023-05-17 00:09 UTC, kekey1 submitted a review, later dismissed

2023-05-17 14:26 UTC, athomas-git submitted a review, later dismissed

2023-05-17 14:28 UTC, ashwinimore approved these changes, later dismissed

2023-05-17 17:42 UTC, tmy1313 submitted a review, later dismissed

2023-05-22 00:32 UTC, ashwinimore submitted a review, later dismissed

2023-05-25 15:47 UTC, ashwinimore approved these changes

2023-05-25 16:10 UTC, kekey1 approved these changes, later dismissed

2023-05-25 16:48 UTC, tmy1313 submitted a review, later dismissed

2023-05-25 17:07 UTC, ashwinimore requested changes

2023-05-25 17:07 UTC, ashwinimore commented on e2e/pages/reports/questionable-activity/questionable-activity.readonly.spec.js
> +  });
please update the text to use approved text from earlier today

2023-05-25 17:13 UTC, ashwinimore requested changes

2023-05-25 17:13 UTC, ashwinimore commented on e2e/pages/reports/questionable-activity/questionable-activity.readonly.spec.js
> +    await expect(await page.getBodyText()).toContain('Please note that only active and suspended listings are shown by default. Use the Certification Status / Certification Edition filters to display
```suggestion
    await expect(await page.getBodyText()).toContain('The Questionable Activity Report offers users the ability to monitor the activities performed on specific CHPL products by ONC-Authorized Certification Bodies and assess their adherence to ONC-established rules.');
```

2023-05-25 17:17 UTC, kekey1 approved these changes

2023-05-25 17:17 UTC, ashwinimore approved these changes

2023-05-25 17:17 UTC, tmy1313 approved these changes

2023-05-25 17:20 UTC, merged