[#OCD-4294] ui!: Remove references to XML/XSD files from API Page
chpladmin/chpl-website pull request #1259
Opened 2023-12-12 19:24 UTC by andlar

2023-12-12 20:13 UTC, tmy1313 submitted a review, later dismissed

2023-12-12 22:13 UTC, kekey1 requested changes

2023-12-12 22:13 UTC, kekey1 commented on src/app/pages/resources/api/api.jsx
> +      $analytics.eventTrack('Download CHPL', { category: 'Download CHPL', label: files[selectedOption].label });
Since we aren't offering definition files anymore, I feel like there should be an update to the text on the left side of this page to direct the user to the "Schemas" area at the waaaaayyyy bottom of the Swagger UI.

2023-12-12 22:13 UTC, kekey1 commented on src/app/pages/resources/api/api.jsx
> +                  <Typography gutterBottom><strong>Certified Products:</strong></Typography>
I don't have a good place to leave this comment but I think you also need to update text from "Download the CHPL" where it says "JSON and XML files have been moved to the [CHPL API page](https://chpl-dev.healthit.gov/#/resources/api)." Maybe that whole alert can be moved. As a person who totally forgot that we only moved the JSON and XML resources, I was really confused when looking at the CHPL API page. I wanted to download a CSV and I couldn't, but forgot that I had to do that from a different page. The functionality seems really oddly broken up. Downloading the JSON is also "Downloading the CHPL" and I wonder if the "Download the CHPL" page could let you download ALL formats (JSON and CSV) whereas the API page could let you download just the JSON since we guessed developers care most about that. I don't know. I couldn't find anywhere on the "Download the CHPL" page where it told me what format of file I would be getting and that also was confusing.

2023-12-12 22:19 UTC, kekey1 commented on src/app/pages/resources/api/api.jsx
> +                  <Typography gutterBottom><strong>Certified Products:</strong></Typography>
It's equally confusing for the updated page to no longer tell you anywhere what file format you are downloading. I agree that not every item in the dropdown needs "(JSON)" next to it, but it should probably be in some/one place on the page. What about the button? "Download JSON" or "Download Data as JSON" or even on the left side in the description.

2023-12-13 20:12 UTC, kekey1 approved these changes, later dismissed

2023-12-14 00:42 UTC, tmy1313 submitted a review, later dismissed

2023-12-14 17:57 UTC, kekey1 approved these changes

2023-12-20 19:38 UTC, tmy1313 approved these changes

2023-12-21 14:42 UTC, merged