OCD-4449
chpladmin/chpl-website pull request #1275
Opened 2024-01-12 20:49 UTC by mattystank

- Add CTA with editionLessIsOn on home page
- Change icon color to darker blue to match mockup

2024-01-16 13:47 UTC, andlar requested changes

2024-01-16 13:47 UTC, andlar commented on src/app/pages/collections/search/landing-page.jsx
> +                        <CodeIcon style={{ color: theme.palette.primary.dark }} />
Does this actually work? The color in the palette file is named `primaryDark`

2024-01-16 13:47 UTC, andlar commented on src/app/pages/collections/search/landing-page.jsx
> +            { editionlessIsOn ? (
This shouldn't be a ternary. The way this is set up you'll display one thing if the flag is on, and another if it's off, but the way you have it there's nothing that gets displayed when it's off, so this should just be a conditional. Something like this:
```suggestion
            { editionlessIsOn 
            && (
```

2024-01-16 13:47 UTC, andlar commented on src/app/pages/collections/search/landing-page.jsx
> +            ) : null}
Changing it to a conditional makes this something like:
```suggestion
            )}
```

2024-01-16 15:48 UTC, andlar approved these changes

2024-01-17 14:52 UTC, kekey1 approved these changes

2024-01-18 16:41 UTC, merged