OCD-4560
chpladmin/chpl-website pull request #1311
Opened 2024-04-23 15:25 UTC by mattystank

Update Compare Widget Category Analytics to ReactGA4

2024-04-23 15:30 UTC, andlar requested changes

2024-04-23 15:30 UTC, andlar commented on src/app/components/compare-widget/compare-display.jsx
> +      label: listings.map((listing) => listing.id).join('&'),
Why is this label here? We didn't have it before, and no one was asking for it

2024-04-23 15:30 UTC, andlar commented on src/app/components/compare-widget/compare-display.jsx
> +    }); $rootScope.$broadcast('compare.removeAll');
The "rootscope.broadcast" part should be on a separate line

2024-04-23 16:23 UTC, mattystank commented on src/app/components/compare-widget/compare-display.jsx
> +      label: listings.map((listing) => listing.id).join('&'),
I can take it out... This was more of a test to see I got the label in a different category/action

2024-04-23 16:39 UTC, andlar commented on src/app/components/compare-widget/compare-display.jsx
> +      label: listings.map((listing) => listing.id).join('&'),
If you want to keep it as a test, then mark it specifically as a `label: 'test'` or something similar. I don't want to get something in here that we forget to take out, especially if it's something that we don't have a use for

2024-04-23 16:44 UTC, mattystank commented on src/app/components/compare-widget/compare-display.jsx
> +      label: listings.map((listing) => listing.id).join('&'),
Will do !

2024-04-23 17:10 UTC, andlar approved these changes

2024-04-24 18:37 UTC, kekey1 approved these changes

2024-04-25 13:54 UTC, tmy1313 approved these changes

2024-04-25 14:03 UTC, merged