OCD-4528: Add analytics for ONC Organizations
chpladmin/chpl-website pull request #1323
Opened 2024-05-10 15:06 UTC by mattystank

2024-05-10 15:39 UTC, andlar commented on src/app/pages/organizations/onc-organizations/onc-organizations.jsx
> +  const organization = useEffect(() => {
This doesn't work. I don't know what you're trying to do, but `useEffect` doesn't return anything, so can't be used to set the organization to any particular value

2024-05-24 15:55 UTC, andlar requested changes

2024-05-24 15:55 UTC, andlar commented on src/app/components/onc-organization/onc-organization-view.jsx
> +                  edit(true);
```suggestion
                  edit();
```

2024-05-24 15:55 UTC, andlar commented on src/app/pages/organizations/onc-organizations/onc-organizations.jsx
> +                      id="create-new-organization">
```suggestion
                      id="create-new-organization"
                    >
```

2024-05-24 15:55 UTC, andlar commented on src/app/pages/organizations/onc-organizations/onc-organizations.jsx
> +                      </Button>
```suggestion
                    </Button>
```

2024-05-29 14:11 UTC, andlar approved these changes

2024-05-30 14:13 UTC, kekey1 approved these changes

2024-05-30 15:19 UTC, tmy1313 approved these changes

2024-05-30 16:00 UTC, merged