OCD-4518 - Build "Unique products" report in PowerBI
chpladmin/chpl-website pull request #1339
Opened 2024-07-02 20:21 UTC by tmy1313

OCD-4518

2024-07-08 11:05 UTC, kekey1 approved these changes, later dismissed

2024-07-09 12:35 UTC, andlar requested changes

2024-07-09 12:35 UTC, andlar commented on src/app/pages/charts/product/product.component.js
>        this.utilService = utilService;
The only one of these four injects being used is the $sce one. The others should be removed. I sometimes keep $log around for ease of debugging, but I don't think that's necessary any more. The `constructor(...){` line will need to change too

2024-07-09 12:35 UTC, andlar commented on src/app/pages/charts/charts.component.js
> -      this.networkService.getCriterionProductStatistics().then(data => that.criterionProduct = data);
If this networkService call isn't being used anywhere else, it should be removed from the network.service.js file

2024-07-09 16:16 UTC, kekey1 approved these changes

2024-07-09 17:47 UTC, andlar approved these changes

2024-07-19 13:28 UTC, merged