OCD-4643: start tracking SED interactions in new analytics package
chpladmin/chpl-website pull request #1349
Opened 2024-07-26 12:58 UTC by andlar

2024-07-26 14:51 UTC, mattystank approved these changes

2024-07-26 15:16 UTC, kekey1 approved these changes

2024-07-26 15:16 UTC, kekey1 commented on src/app/components/listing/details/sed/sed-task-participants-view.jsx
> +      event: 'View SED Participant Details',
I don't see this one in the spreadsheet,

2024-07-26 15:16 UTC, kekey1 commented on src/app/components/listing/details/sed/sed-task-view.jsx
> +        event: 'Open SED Task',
Is this "Open SED Testing Task" from the spreadsheet?

2024-07-29 14:56 UTC, mattystank commented on src/app/components/listing/details/sed/sed-task-view.jsx
> +        event: 'Open SED Task',
Correct, there the same.

2024-07-29 14:57 UTC, mattystank commented on src/app/components/listing/details/sed/sed-task-participants-view.jsx
> +      event: 'View SED Participant Details',
View is correct, I will update the spreadsheet in follow our historical events

2024-07-29 14:58 UTC, mattystank commented on src/app/components/listing/details/sed/sed-task-view.jsx
> +        event: 'Open SED Task',
Think of changing this to "View" ? to follow previous pattern

2024-07-30 14:06 UTC, tmy1313 approved these changes

2024-07-31 15:24 UTC, kekey1 commented on src/app/components/listing/details/sed/sed-task-participants-view.jsx
> +      event: 'View SED Participant Details',
I updated the spreadsheet

2024-07-31 15:25 UTC, kekey1 commented on src/app/components/listing/details/sed/sed-task-view.jsx
> +        event: 'Open SED Task',
Updated the spreadsheet to say "View SED Testing Task" but this code needs to be updated to match that.

2024-07-31 15:26 UTC, kekey1 requested changes
Marking as request changes so that the spreadsheet events and the events here are made to match.

2024-07-31 15:46 UTC, andlar commented on src/app/components/listing/details/sed/sed-task-view.jsx
> +        event: 'Open SED Task',
The spreadsheet is not relevant to this ticket. The spreadsheet is the "truth and final" and will be going through so many revisions before it even gets started. This ticket is to do something like an alpha-version of SED tracking, and nothing in this is going to be live once we actually have a comprehensive suite of analytics

2024-07-31 15:57 UTC, kekey1 approved these changes

2024-08-01 19:05 UTC, merged