OCD-4653 - Create Developer widgets
chpladmin/chpl-website pull request #1359
Opened 2024-08-21 18:49 UTC by tmy1313

2024-08-29 13:44 UTC, kekey1 submitted a review, later dismissed

2024-08-29 13:44 UTC, kekey1 commented on src/app/navigation/navigation-top.html
> +              <li ng-if="vm.hasAnyRole(['chpl-admin'])"><a ui-sref="power-bi"><i class="fa fa-caret-right" ng-if="vm.isActive('sys-admin.power-bi')"></i>Power BI Report</a></li>
This is just a nitpicky thing but I don't like this being called "Power BI" anything. I would like "CHPL By the Numbers" or "Statistics Dashboard" or just "Dashboard" or something. It seems secondary (from a UI point of view) that we are using Power BI to display this dashboard.

2024-08-29 13:45 UTC, andlar commented on src/app/navigation/navigation-top.html
> +              <li ng-if="vm.hasAnyRole(['chpl-admin'])"><a ui-sref="power-bi"><i class="fa fa-caret-right" ng-if="vm.isActive('sys-admin.power-bi')"></i>Power BI Report</a></li>
I like this idea. We don't know what we're actually going to be calling this thing, but why not try to guess. Even just "chplDashboard" or something would match our patterns and could be what we eventually use

2024-08-30 15:35 UTC, kekey1 approved these changes, later dismissed

2024-09-03 11:55 UTC, andlar requested changes
I noticed the PR is not up to date with staging. Not sure how much that'll change things, but it'll need to be updated before it can be merged, at least

2024-09-03 11:55 UTC, andlar commented on src/app/api/reports.jsx
> +      console.log('reports.jsx');
`report-url` and `report-data` should match. I don't know if I care which one is used, but they should be the same

2024-09-03 11:55 UTC, andlar commented on src/app/api/reports.jsx
> +      console.log(response.data);
Should remove debug lines

2024-09-03 11:55 UTC, andlar commented on src/app/navigation/navigation-top.html
> +              <li ng-if="vm.hasAnyRole(['chpl-admin'])"><a ui-sref="dashboard"><i class="fa fa-caret-right" ng-if="vm.isActive('sys-admin.dashboard')"></i>Dashboard</a></li>
Issue #1 on the ticket says ONC should have access to these reports, and the ticket description says that as well

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard-wrapper.jsx
> +function DashboardWrapper() {
```suggestion
function ChplDashboardWrapper() {
```

Our naming convention is that our components all start with Chpl

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +const useStyles = makeStyles((theme) => ({
```suggestion
const useStyles = makeStyles({
```

Passing a function into the makeStyles was what we did early on, but is not the standard going forward

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +    padding: theme.spacing(8),
The `theme` variable is not imported anywhere in this file, so this value can't exist. It should be imported in line 12 with the `import { palette, theme }` line

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +import HighlightOutlinedIcon from '@material-ui/icons/HighlightOutlined';
These are external imports, and should be part of the first set of imports, immediately after the line with `@material-ui/core`

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +import { palette } from 'themes';
These are internal imports (from our project) and should be separated from the external imports by a new line. I _think_ our js-linter should report on that as an issue, but I don't know if you have it set up

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +                        { text: 'Developer Reporting', page: 'developerReport' },
It feels weird having two arrays of the same data defined in different places. Can this set of data be included in the array above that has the icons, and then this `.map` can just be something like `pages.map((item) =>`?

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +              {/* Add more conditionally rendered cards here based on `activeCard` value */}
Do we have a menu with four icons on it, but only one of them works?

2024-09-03 11:55 UTC, andlar commented on src/app/pages/resources/dashboard/index.js
> +import Dashboard from './dashboard';
We started with using these index.js files, but they just get in the way and don't provide any value. Even in this code you're not actually using this file anywhere

2024-09-03 16:44 UTC, andlar approved these changes, later dismissed
Leaving some comments open, as they're likely going to be dependent on PO input. Would be okay moving forward in the meantime

2024-09-03 16:47 UTC, kekey1 submitted a review, later dismissed

2024-09-04 11:09 UTC, andlar submitted a review, later dismissed

2024-09-04 13:08 UTC, kekey1 approved these changes, later dismissed

2024-09-12 17:16 UTC, kekey1 submitted a review, later dismissed

2024-09-16 17:31 UTC, kekey1 approved these changes

2024-09-16 17:54 UTC, andlar approved these changes

2024-09-17 13:19 UTC, merged