OCD-4668 - Create Surveillance widgets based on Summary Stats
chpladmin/chpl-website pull request #1370
Opened 2024-09-17 18:06 UTC by tmy1313

OCD-4668

2024-09-18 16:48 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +  const [activeReport, setActiveReport] = useState();
`useState()` should have something inside the parentheses. In this case, I suggest `undefined`, and later, where you're setting the state to `'home'` just change that to be `undefined` as well. When the user is on the dashboard, the active report is actually undefined

2024-09-24 15:02 UTC, andlar requested changes
Also, this PR is not up to date with staging

2024-09-24 15:02 UTC, andlar commented on src/app/pages/resources/dashboard/dashboard.jsx
> +              {activeReport == null && (
```suggestion
              {!activeReport && (
```

Two things: 
1) `undefined !== null`, so I don't think this check works
2) In JS, `==` and `===` are different, but `===` is more strict, and what we should be using everywhere

That said, the easy answer is to just use the `!activeReport` check as in the code suggestion, and that would handle both `null` and `undefined`

2024-09-25 13:42 UTC, andlar approved these changes

2024-09-25 13:48 UTC, kekey1 approved these changes

2024-10-01 13:29 UTC, merged