feat: Update scheduled jobs to work correctly with UTC time
chpladmin/chpl-website pull request #677
Opened 2019-11-04 15:49 UTC by tmy1313

2019-11-04 16:03 UTC, andlar requested changes
Can you rename the uibTimepicker file to match the filename conventions of the rest of the util components? `uib-timepicker.directive.js`?

2019-11-04 17:47 UTC, andlar submitted a review, later dismissed

2019-11-13 14:35 UTC, Plow74 submitted a review, later dismissed

2019-11-14 19:13 UTC, andlar commented on src/app/pages/administration/jobs/scheduled/trigger.html
> +    </di    v>
?

2019-11-25 17:25 UTC, andlar approved these changes

2019-11-26 19:56 UTC, kekey1 approved these changes

2019-11-27 15:07 UTC, merged