OCD-3290 - Change the order of display of revised criteria so "Cures Update" is first
chpladmin/chpl-website pull request #726
Opened 2020-04-01 17:56 UTC by tmy1313

OCD-3290

2020-04-01 18:14 UTC, kekey1 requested changes

2020-04-01 18:14 UTC, kekey1 commented on src/app/services/util.service.js
> +            return ['170.302 (a)',
Same concern here with the list of all the criteria... in this case we have services that return them from the API. Maybe you could adjust one of those services to use the sorting code you wrote in the API? Is a list guaranteed to remain sorted once it goes from api json into browser javascript? I just wonder if there is any other way to accomplish it. If not, I will get over it. :)

2020-04-01 18:14 UTC, kekey1 commented on src/app/services/util.service.js
> +                index = 10000;
is there a MAX_VALUE type of constant in javascript?

2020-04-01 18:14 UTC, kekey1 commented on src/app/services/util.service.js
> +                    valueToFind += '(Cures Update)';
Do we have a list of constants anywhere that this "(Cures Update)" string may be able to be added to? I feel like it's probably in a lot of places.

2020-04-01 20:55 UTC, andlar requested changes

2020-04-01 20:55 UTC, andlar commented on src/app/services/util.service.spec.js
> -                    expect(util.sortCert({name: '170.314 (a)(2)'})).toBeLessThan(util.sortCert({name: '170.314 (a)(10)'}));
This test was added because there were some lists of criteria that didn't have "number" as fields, but instead had "name". Unless you can confirm that there are no criteria that come back from the API like that any more then I think the test needs to be reinstated

2020-04-01 20:55 UTC, andlar commented on src/app/services/util.service.spec.js
> -                it('should sort objects that have identical numbers by title', () => {
While the description of the test isn't great, the way to make it better would be to update the "title" values below to have "(Cures Update)" in some of them, and update the test to expect the Cures Update ones to come first

2020-04-01 20:55 UTC, andlar commented on src/app/services/util.service.spec.js
> +                var criteria2014_h_1 = { number: '170.314 (h)(1)' };
Why did this number change? I don't see why the functionality in this ticket would necessitate changing this particular test

2020-04-01 20:55 UTC, andlar commented on src/app/services/util.service.spec.js
> +                var criteria2015_e_1_cures = { number: '170.315 (e)(1)(Cures Update)' };
Non-conformity types are a bunch of strings, and some of them have the string "Removed" in them. This variable / test below were set up to ensure that the "removed" version of a criteria stayed in the same location as it had before

2020-04-01 20:55 UTC, andlar commented on src/app/services/util.service.spec.js
> -                expect(util.sortNonconformityTypes(criteria2015_e_1)).toBe(util.sortNonconformityTypes(criteria2015_e_1_removed));
This is sorting non-conformity types. I tried to get to close to 100% coverage of the utility class; if functionality changed to sort criteria then there should be some new tests added to handle the new functionality, and maybe modifications made to this test, but now it looks like the "removed" criteria sorts aren't being tested

2020-04-02 17:19 UTC, tmy1313 commented on src/app/services/util.service.spec.js
> +                var criteria2014_h_1 = { number: '170.314 (h)(1)' };
170.314 (g)(10) is not a valid criteria, therefore it is not in the list to be sorted.

2020-04-03 11:53 UTC, andlar submitted a review, later dismissed

2020-04-03 11:53 UTC, andlar commented on src/app/services/util.service.spec.js
> +                it('should sort objects that are Cures Update before the original criteria', () => {
```suggestion
                it('should sort strings that are Cures Update before the original criteria', () => {
```

2020-04-03 17:16 UTC, kekey1 submitted a review, later dismissed

2020-04-10 20:40 UTC, andlar commented on src/app/pages/charts/surveillance/surveillance.component.js
> +                .sort((a, b) => that.utilService.sortCertActual(a, b))
If you're not calling the old sort function anymore, can you check to see if it's called anywhere at all? if it's not used any more I'd rather just remove it entirely

2020-04-13 14:59 UTC, andlar commented on src/app/pages/charts/charts.component.js
> +            this.utilService = utilService;
Is this being used anywhere?

2020-04-13 18:04 UTC, kekey1 approved these changes

2020-04-13 20:49 UTC, andlar approved these changes

2020-04-15 14:03 UTC, merged