UI automation test
chpladmin/chpl-website pull request #767
Opened 2020-06-24 19:38 UTC by palakpatel311

2020-06-29 14:21 UTC, Plow74 submitted a review, later dismissed

2020-06-29 15:14 UTC, andlar requested changes

2020-06-29 15:14 UTC, andlar commented on README.md
> +* `yarn e2e`: Run the end to end integration tests
I think you added the `yarn e2e:lint` command too, right? If so, it should be in the README as well

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +class LoginPage extends BasePage {
Would it make more sense for this to be a `LoginComponent` instead of a Page?

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +    LoginButton: '#login-toggle',
We use camelCase for almost all of the variables and member elements in javascript code. The only exception is in an actual Class name. This ought to be `loginButton`

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +const loginElements= {
I just added a rule that requires `=`s to have spaces around them. All of the rest of the codebase has that state, except for about 10 issues that I fixed. It's in my OCD-3408 branch if you'd like to merge that branch into yours. That will show a few other style issues in other parts of this PR

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +        super.open(config.baseUrl);
I'm not sure if component POs should have anything to do with the URL. I would think a test of these should just load the BasePage URL, or any other page that has the component that needs to be tested, and then do the asserts of the component pieces

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +    get login () {
This is a button, right? Would it make sense to name it `loginButton`? Or is it really the `toggleLoginComponent` button?

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +    get username () {
This is an input field, right? To me, "get username" would be the text display of a user's username. Maybe `usernameInput`?

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.po.js
> +    gotoLoginPage () {
Components don't have pages, so what about `openLoginComponent () {`?

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
Is there a reason to use assert? WebdriverIO comes with "expect", and this line could be done with `expect(LoginPage.username).toBeDisplayed();`

2020-06-29 15:14 UTC, andlar commented on e2e/pages/resources/overview/OverviewPage.po.js
> +    compareTableData (){
This function should be in the spec file. While it's specific to the Page, it's only of use for testing, and only for the single test that it's used for

2020-06-29 15:14 UTC, andlar commented on e2e/pages/resources/overview/overviewPage.spec.js
> +import SearchPage from '../../../pages/search/SearchPage.po.js';
Why does the OverviewPage need the Search page? Why can't this test just open the Overview page directly?

2020-06-29 15:14 UTC, andlar commented on e2e/components/login/Login.spec.js
> +import LoginPage from './Login.po.js'
The Overview spec file doesn't have a capitalized filename (overviewPage.spec.js). I don't think this one should either. We have to (should?) capitalize the files that export classes so imports look right, though now that I type that I'm not sure that's true either...

2020-06-29 15:14 UTC, andlar commented on e2e/pages/search/SearchPage.po.js
> +    get chplResource (){
These "get"s should probably both be something like `get chplResourceButton () {`

2020-06-29 17:06 UTC, palakpatel311 commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
Assert is easy to use and also could pass in with optional message at the end so helps in debugging.

2020-06-29 17:08 UTC, palakpatel311 commented on e2e/pages/resources/overview/overviewPage.spec.js
> +import SearchPage from '../../../pages/search/SearchPage.po.js';
Search page is actually home page. so navigation to overview page should be needed from homepage. It is not good practice to just go directly overview page for testing.

2020-06-29 17:31 UTC, palakpatel311 commented on e2e/components/login/Login.spec.js
> +import LoginPage from './Login.po.js'
So by looking at sample projects on wdio site, we can follow having import with first letter capitalized in the test where we are using page but page name can still follow camelCase.

I am open to change either way

2020-06-29 18:36 UTC, andlar requested changes

2020-06-29 18:36 UTC, andlar commented on e2e/components/login/Login.spec.js
> +import LoginComponent from './loginComponent.js'
This file should also be lowercase named

2020-06-29 18:36 UTC, andlar commented on e2e/components/login/loginComponent.js
> +    gotoLoginComponent () {
This doesn't "go" anywhere, right? I just opens the component, so it shouldn't be named "goto"

2020-06-29 18:36 UTC, andlar commented on e2e/pages/resources/overview/OverviewPage.po.js
> +import BasePage from '../../../utilities/basePage';
This file is named "OverviewPage.po.js", but is imported as `import OverviewPage from './overviewPage.po.js';`. That might work on a Windows machine, but Linux won't be able to import it, as Linux cares about file name cases. This one should be renamed as "overviewPage.po.js", or possibly just "overview.po.js", as the "po" part indicates that it's a page

2020-06-29 18:36 UTC, andlar commented on e2e/pages/search/SearchPage.po.js
> +import BasePage from '../../utilities/basePage';
Similar concerns about filename case as in the Overview page

2020-06-29 18:36 UTC, andlar commented on e2e/utilities/BasePage.js
> +export default class BasePage {
Is this a page object? Should be in a file named `base.po.js`, right?

2020-06-29 18:37 UTC, andlar commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
If this has benefits great, but I don't see an optional message. I also don't know where any documentation is for the `assert` object. I was able to find webdriverio `expect` stuff by googling for it, but don't know what to look for to find the `assert` docs

2020-06-29 18:41 UTC, palakpatel311 commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
https://www.chaijs.com/api/assert/

2020-06-29 18:46 UTC, andlar commented on e2e/pages/resources/overview/overviewPage.spec.js
> +import SearchPage from '../../../pages/search/SearchPage.po.js';
Testing navigation ought to be done in a test under the components/navigation files. Tests of a given page shouldn't depend on any other page.

2020-06-30 12:10 UTC, andlar requested changes

2020-06-30 12:10 UTC, andlar commented on e2e/components/login/Login.spec.js
> +import LoginComponent from './login.po'
This file needs a different filename: `login.spec.js` with the lowercase `L`;

2020-06-30 12:10 UTC, andlar commented on e2e/components/login/login.po.js
> +module.exports = new LoginComponent();
Have done some digging. This construction is used in commonJS and mostly for nodeJS and backend server JS development. The `export`/`import` construction is the standard for ES6, and is considered to be best practice going forward. I'd like to switch all of these over to that mode

In this case, I think the right statement should be `export default class LoginComponent;`, and where it's being imported would be `import LoginComponent from 'login.po';` which is already in place in the spec file

2020-06-30 12:10 UTC, andlar commented on e2e/config/mainConfig.js
> +module.exports = {
Here we'd need something like 

```
const config = {
baseUrl: 'https://etc',
etc.
}

export default config;
```

And in the Hooks file, it would be `import config from '../config/mainConfig;' and then it could be used the same way

Oh, and typing that last line made me recognize that `mainConfig` isn't in the right format. Maybe just `main`? As it's already in the config directory?

2020-06-30 12:37 UTC, andlar commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
Have looked into this more. The `expect` matchers that come with wdio give us a lot of things we can check in that are specific to web pages, like styles, elements being enabled/disabled, things being visible, etc. It also extends jest matchers, which lets us use a whole bunch of other basic matchers, and means we don't need a separate package. As well, with the wdio expect we _can_ have optional display messages like:

```
expect(LoginComponent.usernameInput).toBeDisplayed({message: 'usernameInput is not displayed, but it should be'});
```

The other thing that concerns me is that I can't see how we're even getting `assert` into the project. I know it's in the `require('assert')` in the wdio.conf file, which looks through node_modules for the required thing, but there's nothing in package.json about chaijs, so I don't know how it's finding it

2020-06-30 14:23 UTC, palakpatel311 commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
This is where we are getting assert. 
before: function (capabilities, specs) {
        assert = require('assert')
    },

Can we use both assert and expect?
I am not a fan of chain commands like what expect uses.

2020-06-30 20:01 UTC, andlar commented on e2e/components/login/Login.spec.js
> +        assert.equal(LoginPage.username.isDisplayed(),true);
I see that line as the place where our code requires the `assert` package, but I don't see anything that tells me where the package comes from. I'm not completely against keeping both assert and expect as options, but would be interested in seeing if the team can settle on one of them at some point, as having two different packages to use for the same purpose doesn't seem like a great idea

2020-07-01 16:43 UTC, andlar approved these changes

2020-07-02 12:48 UTC, ashwinimore approved these changes

2020-07-02 13:08 UTC, merged