Ocd 3420
chpladmin/chpl-website pull request #783
Opened 2020-07-30 16:03 UTC by palakpatel311

![image](https://user-images.githubusercontent.com/57638347/88945958-9d884880-d25c-11ea-998d-b6138f1cadba.png)
![image](https://user-images.githubusercontent.com/57638347/88945990-a8db7400-d25c-11ea-92fe-ed153d08ff50.png)

2020-07-30 17:40 UTC, andlar requested changes

2020-07-30 17:40 UTC, andlar commented on README.md
> +* `yarn e2e`: Run the end to end integration tests. This script needs to be run as "USERNAMEACB=UserName_for_ACB PASSWORDACB=PassWord_for_ACB USERNAMEADMIN=UserName_for_ADMIN PASSWORDADMIN=PassWord_f
Requiring these to be entered from the command line is not how we usually handle credentials. Putting them in some sort of gitignored file and inserting it during a Bamboo build is the preferred way of doing things, especially as that allows different users to use different credentials and save them in their own local file systems

2020-07-30 17:40 UTC, andlar commented on e2e/components/login/login.po.js
> +    get loginBtn () {
Prefer spelling out simple words, as opposed to abbreviating them

2020-07-30 17:40 UTC, andlar commented on e2e/components/login/login.po.js
> +    loginAsACB () {
If you're going to add functionality to a page-object, it would be useful to add tests that cover that functionality

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +        return uploadAsserts.expectedUploadText;
I don't think expected values should be in the page-objects. The page-objects should be there to return values / elements / etc., but it's the spec files that should have the expected values

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +class ConfirmPage {
There are a lot of page elements here but no spec file that asserts anything about them. Any functionality in a page-object ought to be tested in a related spec file

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +        else {
Should be on the previous line

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +            this.inspectNextBtn.waitAndClick();
If we get into this block, does that mean the "next" button has been clicked four times? That should never happen, right? It's a maximum of three clicks to get to the confirm screen

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    gotoConfirmListingPg (inspectListingId ) {
Please spell out the `Page` part of this method name

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    get inspectNextBtn () {
Same comment re: `Btn` should be `Button`

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    get editcertifiedProduct () {
We usually use the term "listing" to refer to a "certified product", or at least that's the path we're heading towards. That said, with the "certified product", "certified" should be capitalized in this method to match camel-case

2020-07-30 17:40 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    get alltestToolsVersion () {
Similar camel-case issue

2020-07-30 17:40 UTC, andlar commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +class ListingEditPage {
What page is this? the file name doesn't describe where this page is; whether it's a Page or a Component

2020-07-30 17:40 UTC, andlar commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get editcertifiedProduct () {
A lot of these elements look the same as in the confirm page-object. Are they the same elements? Can these be combined in some way? The UI code that shows the edit screen, whether in a listing or a pending listing, is the same code, so if that changes both of the page-objects would need to change, and that seems wrong

2020-07-30 17:40 UTC, andlar commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    gotoEditCriteria (editCriteriaId , cures) {
This doesn't "goto" a criteria. This opens a criteria for editing. The name of the method is unclear

2020-07-30 17:40 UTC, andlar commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +        if (cures === true) {
`cures` is a boolean, right? Why not
```suggestion
        if (cures) {
```

2020-07-30 17:40 UTC, andlar commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    selectTestProcedures (name , version) {
Does this "add a test procedure" to the list of selected test procedures? If so, "selectTestProcedure" doesn't seem like it describes that

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +import UploadPage from '../../pages/administration/upload/upload.po';
The format we're moving towards for file names is "all lowercase, with `-` separating words"

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +import {assert} from 'chai';
Why does "assert" need to be imported? It used to just be a global...

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +    before(() => {
Where did "before" come from? Why does it need to be a global while "beforeEach" doesn't?

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +        assert.include(uploadPage.uploadSuccessfulText.getText(),uploadPage.expectedUploadSuccessfulText, 'File has uploaded successfully');
Why is there an assert in a "before" step? Before steps are for setting up the system, not asserting anything, right?

Also, why aren't all of these in the "beforeEach" block? By putting them in this block does that mean that these elements hold state between tests? Holding state between tests is usually regarded as bad form, as that means that tests are not independent of each other

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +        assert.include($('//*[@id="criteria_170.315 (b)(3)_details_row_Functionality_Tested_cures"]').getText(), 'Request to send an additional supply of medication (Resupply)');
There shouldn't be xpaths in spec files. Xpaths ought to only be in the page-object files

2020-07-30 17:40 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa2_admin_add_remove_testProcDataToolFunc.spec.js
> +import UploadPage from '../../pages/administration/upload/upload.po';
Is this file identical to the ONC-ACB one? If so, I think we need to figure out how to remove the duplicate stuff. If we don't any time we need to change one of these we'd need to change the other, and that doesn't make sense

2020-07-30 17:40 UTC, andlar commented on package.json
> +    "chai": "^4.2.0",
Why is this being added?

2020-07-30 19:20 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +    before(() => {
This is Mocha.hookfunction.
BeforeEach shows as jasmine. 
Not sure how to make before added as defined

2020-07-30 19:37 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/aqa2_admin_add_remove_testProcDataToolFunc.spec.js
> +import UploadPage from '../../pages/administration/upload/upload.po';
Yes it is. I have kept it seperate for now as we have on of the ticket which doesnt allow ACBs to remove test functionality and allows admin

2020-07-30 19:38 UTC, palakpatel311 commented on package.json
> +    "chai": "^4.2.0",
This is where assert should be from when you asked me in other PR. so chai needs to be added.

2020-08-04 12:02 UTC, andlar requested changes

2020-08-04 12:02 UTC, andlar commented on README.md
> +Rename e2e/config/credentialsEXAMPLE.js to e2e/config/credentials.js And Add Usernames and password in it.
The EXAMPLE file doesn't have any content in it. Without a sample of what's expected it's hard to know what to put in it

2020-08-04 12:02 UTC, andlar commented on e2e/components/login/login.po.js
> +            this.usernameInput.addValue(credentials.usernameACB);
This "addValue" happens in both branches of the `if`. Given that, it ought to be outside of the `if`

2020-08-04 12:02 UTC, andlar commented on e2e/components/login/login.po.js
> +        this.usernameInput.addValue(credentials.usernameAdmin);
Why doesn't this `loginAsUser` function have the `if` construct from the `loginAsACB` function?

2020-08-04 12:02 UTC, andlar commented on e2e/components/login/login.spec.js
> +describe('ACB can', () => {
I try to write my `describe` and `it` blocks in such a way that they make sentences. Describe blocks should look like a description of the state of the system / user doing something / something like that. So this one could be `describe('an ACB user'` 

It blocks should be written as `it('should do a thing'`, so the `login successfully` one would be `it('should be able to log in`

The result would be test specs that read "an ACB user ... should be able to log in"

2020-08-04 12:02 UTC, andlar commented on e2e/components/login/login.spec.js
> +        assert.equal(component.loginButton.isDisplayed(),true);
Why isn't this just `assert.isTrue`? Using `assert.equal` when testing against a boolean is like writing `if (value === true) {`

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +        return $('//table[@id="pending-listings-table"]/tfoot/tr/th/button');
I don't know what our standard should be, but in the other files these various locator values are defined as constants / data / something at the top of the file. I'm not entirely sure I _like_ that way of doing things, but that is how we started doing it. Whether we go that way or move to inline locators is maybe worth a conversation, but until then keeping consistent with defining the locators at the top of the file matches our pattern

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +            this.inspectNextButton.waitAndClick();
Is this call going to click the "next" button a fourth time? Isn't that impossible?

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +        else {
Should be `} else {`

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +import {assert} from 'chai';
The `assert` is defined in the wdio.conf.js file in a before block. If we're defining that there it shouldn't need to be here too

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +    })
These blocks should have a `;` at the end of them

2020-08-04 12:02 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +    get ChooseUploadListingButton () {
Should be camel-case, not pascal-case

2020-08-04 12:03 UTC, andlar commented on package.json
> +    "chai": "^4.2.0",
It didn't need to be added before, when it was required in the wdio.conf.js file. If it didn't need to be added to work then, why does it need to be added here?

2020-08-04 12:34 UTC, palakpatel311 commented on package.json
> +    "chai": "^4.2.0",
when i wanted to user other asserts like include, it did not detect chai and thats when i saw that chai is not even added in package.json. It worked earlier my guess is assert was coming from some other package or inbuilt.

2020-08-04 13:56 UTC, palakpatel311 commented on README.md
> +* `yarn e2e`: Run the end to end integration tests. This script needs to be run as "USERNAMEACB=UserName_for_ACB PASSWORDACB=PassWord_for_ACB USERNAMEADMIN=UserName_for_ADMIN PASSWORDADMIN=PassWord_f
Changed back to credentials file

2020-08-04 13:58 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/aqa2_admin_add_remove_testProcDataToolFunc.spec.js
> +import UploadPage from '../../pages/administration/upload/upload.po';
Removed admin user test for now. I tried to do data providers which could be used to handle same TC with different credentials but it did not work the way i wanted it to be. I need some time to figure out this as this will be framework setting up for future.

2020-08-04 13:58 UTC, palakpatel311 commented on e2e/components/login/login.po.js
> +            this.usernameInput.addValue(credentials.usernameACB);
Fixed

2020-08-04 13:58 UTC, palakpatel311 commented on e2e/components/login/login.po.js
> +        this.usernameInput.addValue(credentials.usernameAdmin);
Fixed

2020-08-04 13:59 UTC, palakpatel311 commented on e2e/components/login/login.spec.js
> +describe('ACB can', () => {
Fixed.
Ashwini prefers not using should in the TC summary and thats what I was applying here.
But i like Should way.

2020-08-04 13:59 UTC, palakpatel311 commented on e2e/components/login/login.spec.js
> +        assert.equal(component.loginButton.isDisplayed(),true);
Fixed

2020-08-04 14:01 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.po.js
> +            this.inspectNextButton.waitAndClick();
Sometimes, selenium is clicking so fast that it was missing one of the next button thats why i had to add this if

2020-08-04 14:05 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +import {assert} from 'chai';
Agree. Removed from all spec files

2020-08-04 14:05 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +    })
Fixed

2020-08-04 14:06 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +    get ChooseUploadListingButton () {
Fixed

2020-08-05 03:19 UTC, tmy1313 commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get alltestToolsVersion () {
Should this be `allTestToolsVersion ()`?

2020-08-05 03:19 UTC, tmy1313 commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get alltestDataVersion () {
Should this be `allTestDataVersion ()`?

2020-08-05 03:19 UTC, tmy1313 commented on e2e/pages/administration/upload/upload.po.js
> +
Question - if these are defined here, aren't they global (when the file is imported)?  Is that what we want?  Should these strings be defined with in the class?

2020-08-05 03:19 UTC, tmy1313 commented on e2e/pages/administration/confirm/confirm.po.js
> +}
Question - if these are defined here, aren't they global (when the file is imported)? Is that what we want? Should these strings be defined with in the class?

2020-08-05 03:19 UTC, tmy1313 commented on e2e/components/login/login.po.js
Question - if these are defined here, aren't they global (when the file is imported)? Is that what we want? Should these strings be defined with in the class?

2020-08-05 11:37 UTC, andlar requested changes

2020-08-05 11:37 UTC, andlar commented on e2e/.eslintrc
> +        "process": false,
I don't see `process` used anywhere in the changed code. I also don't see either `before` or `after`

2020-08-05 11:37 UTC, andlar commented on e2e/components/login/login.po.js
> +        if (this.usernameInput.isDisplayed() === false) {
Checking a variable against a boolean value inside an `if` test is redundant. Should just `if` the variable (with or without a `!` as necessary

```suggestion
        if (!this.usernameInput.isDisplayed()) {
```

2020-08-05 11:37 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +    it('should be able to remove uploaded test procedure, test data, test tools (170.315 (b)(3) cures criteria)', () => {
What happens if this test runs before the one above it? If this test depends on the previous one happening then the tests are dependent, and that's something we really want to avoid

2020-08-05 11:37 UTC, andlar commented on wdio.conf.js
> +            browser.saveScreenshot(`assertionError_${assertion.error.message}.png`)
This saves the output screenshots in the root directory, which then means they'll get caught up by git eventually, or need to be gitignored. Usual best practices would be to output all test results (including errors & messages) into whatever directory our other test output stuff goes in. For this project I think it's `test_reports`

2020-08-05 11:39 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +
I don't think these javascript files are imported directly as is. They're also not "smushed" together to make one big file either, so I think these consts don't land on the global scope. By exporting the "UploadPage" class, and then importing that class specifically, I believe that keeps the consts clear

2020-08-05 12:17 UTC, palakpatel311 commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get alltestDataVersion () {
Fixed

2020-08-05 12:17 UTC, palakpatel311 commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get alltestToolsVersion () {
Fixed

2020-08-05 12:29 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +
Agree. We are not importing constants here to spec files.

2020-08-05 12:30 UTC, palakpatel311 commented on e2e/.eslintrc
> +        "process": false,
Fixed

2020-08-05 12:31 UTC, palakpatel311 commented on e2e/components/login/login.po.js
> +        if (this.usernameInput.isDisplayed() === false) {
Fixed

2020-08-05 12:39 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/aqa1_acb_add_remove_testProcDataToolFunc.spec.js
> +    it('should be able to remove uploaded test procedure, test data, test tools (170.315 (b)(3) cures criteria)', () => {
it blocks runs in sequence

2020-08-05 12:42 UTC, palakpatel311 commented on wdio.conf.js
> +            browser.saveScreenshot(`assertionError_${assertion.error.message}.png`)
Fixed

2020-08-06 12:09 UTC, andlar commented on e2e/components/login/login.po.js
> +        if (this.usernameInput.isDisplayed() === false) {
The comment says "fixed", but I don't see a change in the code. Am I missing something? There are a few other comments like that through the PR

2020-08-06 13:04 UTC, palakpatel311 commented on e2e/pages/searchCHPL/listingEdit/listingEdit.po.js
> +    get editcertifiedProduct () {
Moved it from confirm page

2020-08-06 13:25 UTC, andlar requested changes
I think we're really close here. I have a couple of comments about comparing to booleans which ought to be easy to resolve. The only thing that might be more complicated is in the workflow test file

2020-08-06 13:25 UTC, andlar commented on e2e/.eslintrc
> +        "process": false,
I thought I saw this change, but don't see it now, and don't know how I could be missing it

2020-08-06 13:25 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +        assert.equal(confirmPage.findListingtoReject('15.04.04.1722.AQA1.03.01.1.200620').isDisplayed(),false)
I think this ought to be either `assert.isFalse` if that exists, or something like `assert.isTrue(!confirmPage.find...` Or maybe there's a matcher / assertion that's the opposite of `.isDisplayed()`?

2020-08-06 13:25 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +        browser.waitUntil( () => this.uploadSuccessfulText.isDisplayed() === true)
There are a few places where there are `...something === true` or `...something === false`. All of those should have the ` === boolean` part removed

2020-08-06 13:25 UTC, andlar commented on e2e/pages/listing/listingEdit.po.js
> +        if (cures === true) {
Here are a few more of the `...something === true` things

2020-08-06 13:25 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/aqa1_add_remove_testProcDataToolFunc.spec.js
> +        listingEditPage.closeEditListing();
On these two tests, especially for the first of our workflow ones, I'd like to make sure we set them up correctly to start. The things I see that concern me:

- Why do anything _after_ the last assert in a give `it` block? If we're doing something, it either should cause a change we need to assert, or it's a sign that we're doing something outside of tests
- When the first line of an `it` block is `browser.refresh()` it makes me wonder why that's needed. That suggests that _something_ happened before the test itself that needs to be handled, but if that's the case then wherever that thing is that's causing that to be necessary needs to handle it
- In the `beforeAll` there's a single "upload a listing" thing. If we only upload it once, for the entire suite of tests in this spec, then it seems likely those tests will interact with each other in ways we can't predict. It makes sense to log in once, but it seems likely we'd need to upload the file for every test

2020-08-06 15:53 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/aqa1_add_remove_testProcDataToolFunc.spec.js
> +        listingEditPage.closeEditListing();
1. listingEditPage.closeEditListing(); is needed as between two it block we dont open new browser. browser is same and assertion is happening on the pop up so in order for browser to go back to main screen /administration/confirm...... I will have to close pop up. What i could do is move that to afterEach function so it serves 2 purposes.
3. Moved upload a listing to before Each to handle randomly running TC.

Rearraged a bit. Check and let me know

2020-08-06 15:57 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +        browser.waitUntil( () => this.uploadSuccessfulText.isDisplayed() === true)
Fixed

2020-08-06 15:57 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +        assert.equal(confirmPage.findListingtoReject('15.04.04.1722.AQA1.03.01.1.200620').isDisplayed(),false)
Fixed

2020-08-06 15:57 UTC, palakpatel311 commented on e2e/pages/listing/listingEdit.po.js
> +        if (cures === true) {
Fixed

2020-08-06 16:29 UTC, andlar submitted a review, later dismissed

2020-08-06 17:37 UTC, tmy1313 submitted a review, later dismissed

2020-08-12 19:21 UTC, andlar approved these changes

2020-08-13 13:40 UTC, tmy1313 approved these changes

2020-08-13 14:02 UTC, merged