Ocd 3437 - Add "Ignore warnings" checkbox when editing or confirming certified product
chpladmin/chpl-website pull request #784
Opened 2020-08-03 20:33 UTC by tmy1313

OCD-3437

2020-08-19 14:38 UTC, Plow74 submitted a review, later dismissed

2020-08-19 15:38 UTC, andlar requested changes

2020-08-19 15:38 UTC, andlar commented on src/app/components/listing/inspect/inspect.html
> +        <label for="acknowledge-warnings" class="edit-listing__acknowledge-warning-label">I have reviewed the warning(s) above and wish to proceed with this update</label>
For any of the places where we have things like "warning(s)" in the rest of the system, if we can tell if the number of things is !== 1, I've used an `ng-if` to append or not append the "s". Request doing that here

2020-08-19 15:38 UTC, andlar commented on src/app/components/listing/edit.html
> +    <input type="checkbox" ng-model="$ctrl.acknowledgeWarnings" id="acknowledge-warnings" class="edit-listing__acknowledge-warning-checkbox">
Should have a name value as well, which is camelCase, to be able to use it in the `ngForm[name]` thing as needed

2020-08-19 15:38 UTC, andlar commented on src/app/components/listing/edit.component.js
> +            this.acknowledgeWarnings = false;
I don't usually set things to false in constructors, when `undefined` evaluates as falsy anywhere it needs to be checked against. Not necessarily a required change, but I tend to try to not have lines of code that aren't needed

2020-08-19 15:38 UTC, andlar commented on src/app/admin/components/certifiedProduct/listing/edit.scss
> +label.edit-listing__acknowledge-warning-label {
Can we remove this entire file? CSS is global, and these styles are defined in one of the components directories identically. Part of the path forward is to remove the entirety of the `/admin/*` stuff eventually, so not having duplicate styles would help with that

2020-08-19 15:38 UTC, andlar commented on src/app/admin/components/certifiedProduct/listing/edit.controller.js
> +        vm.acknowledgeWarnings = false;
Same comment re: constructor defaults of false

2020-08-20 16:19 UTC, andlar submitted a review, later dismissed
Approving the PR, though there's a conflict in the yarn.lock file. I don't think that should hold up moving forward with testing

2020-08-20 16:57 UTC, Plow74 submitted a review, later dismissed

2020-09-02 17:06 UTC, andlar requested changes

2020-09-02 17:06 UTC, andlar commented on yarn.lock
> +<<<<<<< HEAD
This doesn't look right...

2020-09-02 17:31 UTC, andlar submitted a review, later dismissed

2020-09-02 17:42 UTC, kekey1 requested changes

2020-09-02 17:42 UTC, kekey1 commented on src/app/components/listing/inspect/inspect.controller.js
> +                warningAcknowledgement: vm.acknowledgeWarnings,
Either go with "acknowledgeWarnings" as in listing edit or change listing edit to match this one. They seem like they should be the same.

2020-09-02 18:47 UTC, andlar approved these changes

2020-09-02 19:23 UTC, kekey1 approved these changes

2020-09-02 19:35 UTC, merged