OCD 3437: Test for ignore warnings checkbox on upload
chpladmin/chpl-website pull request #788
Opened 2020-08-19 12:18 UTC by palakpatel311

2020-08-19 14:25 UTC, Plow74 commented on e2e/pages/administration/confirm/confirm.spec.js
> +        confirmPage.rejectListing('15.04.04.1722.AQA3.03.01.1.200620');
Consider putting these values in a const. ex: `const LISTING_ID_TO_REJECT = 15.04.04.1722.AQA3.03.01.1.200620`. It could improve readability and maintenance since the id seems to be hard coded in 2 places.

2020-08-19 14:30 UTC, Plow74 commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +        confirmPage.gotoConfirmListingPage('15.04.04.1722.AQA4.03.01.1.200620');
Same comment as above. Putting these sort of reused or ambiguous (to the first-time reader) strings may be good candidates for descriptive variable names and prevent an error because the string is defined at a single point.

2020-08-19 14:50 UTC, andlar requested changes

2020-08-19 14:50 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +describe('Confirming a listing', () => {
Why do both this and the previous describe blocks have the same description?

2020-08-19 14:50 UTC, andlar commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +        confirmPage.gotoConfirmListingPage('15.04.04.1722.AQA1.03.01.1.200620');
Does this method "confirm" the listing? My reading of the code suggests it doesn't. If it does actually confirm the listing then the name needs to indicate that. If it doesn't confirm the listing then there should never be a checkbox. The checkbox should only appear if there are warnings on the confirmation action. If this does show the checkbox without attempting to confirm, then we'll need to change the feature code

2020-08-19 14:50 UTC, andlar commented on wdio.conf.js
> +        browser.refresh();
Wait, why are we refreshing the page after a test? This is a global action and I don't want to make a global change without talking about it

2020-08-19 14:50 UTC, andlar commented on e2e/components/login/login.readonly.spec.js
> +    await hooks.open('#/administration/upload');
Why go to this page? Not all users will even be able to get to this page, but all of them can get to the resources/overview one

2020-08-19 16:24 UTC, palakpatel311 commented on wdio.conf.js
> +        browser.refresh();
1. When we are editing an uploaded listing, it opens pop up, once one it block test is done, that pop up is still open and i had to add after method to close that pop up in order to start next it block.
2. It makes sense to start clean on each it block so refresh makes screen clear after each it block execution.

FYI: it block runs sequentially not parallel. I verified.

2020-08-19 19:48 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +        confirmPage.rejectListing('15.04.04.1722.AQA3.03.01.1.200620');
Fixed

2020-08-19 19:48 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +        confirmPage.gotoConfirmListingPage('15.04.04.1722.AQA4.03.01.1.200620');
Fixed

2020-08-19 19:48 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +describe('Confirming a listing', () => {
Updated all test cases after our call

2020-08-19 19:48 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-test/bypass_warnings.spec.js
> +        confirmPage.gotoConfirmListingPage('15.04.04.1722.AQA1.03.01.1.200620');
Updated all test cases after our call

2020-08-19 19:49 UTC, palakpatel311 commented on e2e/components/login/login.readonly.spec.js
> +    await hooks.open('#/administration/upload');
Updated back to overview page

2020-08-20 11:56 UTC, andlar requested changes

2020-08-20 11:56 UTC, andlar commented on e2e/components/login/login.readonly.spec.js
> +    await hooks.open('#/administration/overview');
I don't think this page exists

2020-08-20 11:59 UTC, andlar commented on wdio.conf.js
> +        browser.refresh();
Cleaning up after a test makes sense to be in the test cases that make a mess, not in a global hook that runs after every test. This is a step that will add time to every test, but will only be needed on a few tests

If "starting clean" is required, then whatever describe block needs to start clean should have the refresh call in it, not globally

I agree that "it" blocks run sequentially, and not in parallel. That said, each individual "it" block should be able to run and pass whether or not any other "it" block has run. Each "it" block is an individual test, and if a test depends on a different test having been executed first, that adds interrelationships between tests that shouldn't be there

2020-08-20 12:55 UTC, palakpatel311 commented on wdio.conf.js
> +        browser.refresh();
I ll update browser.refresh in test spec when we deal with edit screen. and again this will be temporary until we get new edit screen.

Agree on It block. I have it set up as independent for this test.

2020-08-20 13:39 UTC, palakpatel311 commented on e2e/components/login/login.readonly.spec.js
> +    await hooks.open('#/administration/overview');
Updated

2020-08-20 13:49 UTC, Plow74 submitted a review, later dismissed

2020-08-20 13:57 UTC, andlar submitted a review, later dismissed

2020-08-20 14:23 UTC, ashwinimore submitted a review, later dismissed

2020-08-20 14:52 UTC, athomas-git submitted a review, later dismissed

2020-09-02 17:13 UTC, andlar approved these changes

2020-09-02 17:30 UTC, ashwinimore approved these changes

2020-09-02 17:37 UTC, merged