test: back to back api documentation upload should be successful
chpladmin/chpl-website pull request #789
Opened 2020-08-19 15:27 UTC by palakpatel311

[#OCD-3049]

2020-08-24 13:44 UTC, tmy1313 requested changes

2020-08-24 13:44 UTC, tmy1313 commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
Should this button be updated to have an ID?  I could see a scenario where we add another button to the puge using the class `btn-ai-success`.

2020-08-24 14:17 UTC, andlar requested changes

2020-08-24 14:17 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
I think the better option would be for this page to not have the upload components at all. Create a new `e2e/components/**/upload-api-documentation` component and put this selector in that component. Then the administration-page can import that upload-api-documentation-component object and use the given `.btn.btn-ai-success` selector, because then there will only be one, if the component is scoped to the `<chpl-upload-api-documentation>` element

2020-08-24 14:17 UTC, andlar commented on e2e/pages/administration/upload/upload.spec.js
> +describe('API documentation file', () => {
I think the things that happen in a beforeEach block inside a describe block ought to be noted in the description of the describe block. So this could be something like `when uploading API documentation files as ADMIN`, whereas the previous would could be `when uploading Listings as ONC-ACB`

2020-08-24 14:17 UTC, andlar commented on e2e/pages/administration/upload/upload.spec.js
> +    afterEach(function () {
Can we move the `afterEach` block to be immediately after the `beforeEach` block? I know it happens after all of the tests, but having the "set up" and "tear down" steps in a sort of header area makes it clear that things _will_ happen after the tests run. It'll be especially useful as we add more tests; we won't need to scroll all the way down to the bottom of a random block to figure out if something's happening. Also, I think it'll help make it clear that, at least for this block, we're logging in and logging out for each test. By putting the "afterEach" block at the end that's harder to tell

2020-08-24 14:17 UTC, andlar commented on e2e/pages/administration/upload/upload.spec.js
> +    })
If we're logging out in after each test above, why aren't we after each of the ones in this block?

2020-08-24 14:27 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.spec.js
> +    afterEach(function () {
Again one of those things when i like to see the test in the order it happens. so I like to write before , Tc execution and after block sequence writing. I think we should leave this to personal preference.

2020-08-24 14:36 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
Why component? If i remember correctly we said that components will be those which would be accessed from any page. I dont see upload page to have any components. 
Also, to Todd's point, having id for upload button makes sense. But regardless we only allow user to upload one upload at a time (either listing or surveillance or api doc), In this case upload button with btn-ai-success will be only once on page.

2020-08-24 17:18 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.spec.js
> +    })
Uploading listing had 2 Tcs but upload API doc has only one TC so logging out after that would just add more execution time with no value.
Also, updated beforeEach to beforeAll in upload listing block.

2020-08-24 17:20 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.spec.js
> +describe('API documentation file', () => {
fixed

2020-08-25 20:10 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
Updated as per our coversation

2020-08-26 13:29 UTC, andlar commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
I like the new components, but I think this page object now has stuff in it that's part of the component stuff, and should be removed from the page

2020-08-26 13:30 UTC, palakpatel311 commented on e2e/pages/administration/upload/upload.po.js
> +    uploadButton: '.btn.btn-ai-success',
I did not remove anything from upload.po as i know some tests are using method from that which are in different branch so need to clean up after wards.

2020-08-26 14:13 UTC, andlar approved these changes

2020-08-26 14:16 UTC, tmy1313 approved these changes

2020-09-01 14:04 UTC, merged