OCD- 3452 : Added test for compare widget and compare page
chpladmin/chpl-website pull request #792
Opened 2020-08-24 15:17 UTC by palakpatel311

2020-08-25 12:14 UTC, andlar requested changes

2020-08-25 12:14 UTC, andlar commented on e2e/components/compare-widget/compare-widget.spec.js
> +describe('on compare widget', () => {
Why do these three describe blocks have the same description?

2020-08-25 12:14 UTC, andlar commented on e2e/components/compare-widget/compare-widget.spec.js
> +    describe('if there is atleast 1 listing added for compare', () => {
```suggestion
    describe('if there is at least 1 listing added for compare', () => {
```

2020-08-25 12:14 UTC, andlar commented on e2e/components/compare-widget/compare-widget.spec.js
> +    describe('if there are atleast 2 listings added for compare', () => {
```suggestion
    describe('if there are at least 2 listings added for compare', () => {
```

2020-08-25 12:14 UTC, andlar commented on e2e/pages/compare/compare.po.js
> +    get certificationCriterialink () {
```suggestion
    get certificationCriteriaLink () {
```

2020-08-25 12:14 UTC, andlar commented on e2e/pages/compare/compare.spec.js
> +    it('All 78 certification criteria should be displayed', () => {
```suggestion
    it('all 78 certification criteria should be displayed', () => {
```

All of our other "it" blocks start with lower-case letters. Also, almost all of them are of the form `it('should do a thing'`, which can be read out loud as "it should do a thing", whereas this one would be read as "it all 78 criteria should be displayed" which doesn't sound right. The second point is more of a style choice, though would be more consistent with the majority of our other tests

2020-08-25 12:14 UTC, andlar commented on e2e/pages/search/search.po.js
> +        return this;
Why return this? What does that do?

2020-08-25 12:14 UTC, andlar commented on e2e/pages/search/search.po.js
> +        return this;
Also, why return "this"?

2020-08-25 12:51 UTC, palakpatel311 commented on e2e/components/compare-widget/compare-widget.spec.js
> +describe('on compare widget', () => {
They have different condition in the inside describe block

2020-08-25 14:45 UTC, tmy1313 reviewed
I have looked at this and have no other feedback outside of Andrew's comments.  Once those items are fixed, I will approve.

2020-08-25 16:22 UTC, palakpatel311 commented on e2e/components/compare-widget/compare-widget.spec.js
> +    describe('if there are atleast 2 listings added for compare', () => {
Fixed

2020-08-25 16:22 UTC, palakpatel311 commented on e2e/pages/compare/compare.po.js
> +    get certificationCriterialink () {
Fixed

2020-08-25 16:22 UTC, palakpatel311 commented on e2e/pages/compare/compare.spec.js
> +    it('All 78 certification criteria should be displayed', () => {
Fixed

2020-08-25 16:23 UTC, palakpatel311 commented on e2e/pages/search/search.po.js
> +        return this;
Fixed

2020-08-25 16:23 UTC, palakpatel311 commented on e2e/pages/search/search.po.js
> +        return this;
Fixed

2020-08-25 17:57 UTC, andlar commented on e2e/components/compare-widget/compare-widget.spec.js
> +describe('on compare widget', () => {
So all three of the "if there are" blocks can be inside a single "on compare widget" block

2020-08-25 17:57 UTC, andlar commented on e2e/components/compare-widget/compare-widget.spec.js
> +    describe('if there is at least 1 listing added for compare', () => {
```suggestion
    describe('if there is exactly 1 listing added for compare', () => {
```

If there were more than one, which the "at least" suggests, then some of these tests would fail

2020-08-25 18:17 UTC, palakpatel311 commented on e2e/components/compare-widget/compare-widget.spec.js
> +    describe('if there is at least 1 listing added for compare', () => {
Fixed

2020-08-25 20:12 UTC, palakpatel311 commented on e2e/components/compare-widget/compare-widget.spec.js
> +describe('on compare widget', () => {
Changed

2020-08-26 13:31 UTC, andlar submitted a review, later dismissed

2020-08-26 14:18 UTC, tmy1313 submitted a review, later dismissed

2020-09-09 16:43 UTC, andlar approved these changes, later dismissed

2020-09-09 19:18 UTC, andlar approved these changes, later dismissed

2020-09-10 15:09 UTC, kekey1 approved these changes, later dismissed

2020-09-10 17:43 UTC, kekey1 approved these changes

2020-09-10 19:08 UTC, andlar approved these changes

2020-09-16 18:15 UTC, merged