Ocd 3393 - Add ability to validate and save Real World Testing data
chpladmin/chpl-website pull request #793
Opened 2020-08-25 17:53 UTC by tmy1313

2020-08-25 18:08 UTC, andlar commented on src/app/pages/listing/listing.scss
> +    display: grid;
Doesn't this need more styling? Just "display grid" won't do anything without some other stuff, right?

2020-08-25 18:08 UTC, andlar commented on src/app/pages/listing/history/history.component.js
> +            if (prev.rwtPlanUrl !== curr.rwtPlanUrl) {
Was this a requirement? I don't remember if it is

2020-08-25 18:08 UTC, andlar commented on src/app/pages/listing/listing.html
> +              <div ng-if="$ctrl.listing.rwtPlanSubmissionDate && ($ctrl.hasAnyRole(['ROLE_ADMIN', 'ROLE_ONC']) || $ctrl.canManageAcb($ctrl.listing.certifyingBody) || $ctrl.canManageDeveloper($ctrl.li
`canManageAcb` also checks against ROLE_ADMIN/ROLE_ONC. It shouldn't need to be here too

2020-08-25 18:08 UTC, andlar commented on src/app/services/login.service.js
> +        function canManageAcb (acb) {
There should be a test for this

2020-08-25 18:08 UTC, andlar commented on src/app/services/util.service.js
> +        function displayRealWorldTesting (listing) {
This would be good to have in the unit tests too

2020-08-26 17:54 UTC, kekey1 submitted a review, later dismissed

2020-08-26 21:03 UTC, tmy1313 commented on src/app/pages/listing/history/history.component.js
> +            if (prev.rwtPlanUrl !== curr.rwtPlanUrl) {
![image](https://user-images.githubusercontent.com/24817202/91356646-03191780-e7be-11ea-91e5-7867d59dfc04.png)

2020-08-26 21:17 UTC, tmy1313 commented on src/app/pages/listing/listing.scss
> +    display: grid;
By default a 1 column grid is created if the column layout is not specified.
![image](https://user-images.githubusercontent.com/24817202/91357956-07463480-e7c0-11ea-8c60-4fe43856f7d6.png)

2020-08-30 22:07 UTC, andlar commented on src/app/pages/listing/listing.scss
> +    display: grid;
Is there a Listing ID of some listing I can find on DEV where I can examine this? If the default styling of the grid basically mimics what you'd see if the style wasn't there then I'm not sure what the point would be, but don't know where to test this

2020-08-30 22:08 UTC, andlar commented on src/app/pages/listing/history/history.component.js
> +            if (prev.rwtPlanUrl !== curr.rwtPlanUrl) {
Suggest double-checking against the "confirm date" thing in the requirements; if they're not displayed to the end users then activity shouldn't be in the eye, but otherwise fine with this change

2020-08-30 22:12 UTC, andlar requested changes

2020-08-30 22:12 UTC, andlar commented on src/app/services/login.service.spec.js
> +                expect(auth.canManageAcb({id: 5}));
Doesn't this need at `.toBe(true)` or something like it? Same question for all of the following ones

2020-08-30 22:12 UTC, andlar commented on src/app/services/login.service.spec.js
> +                    expect(auth.canManageAcb({id: 4}));
![image](https://user-images.githubusercontent.com/909012/91670501-3cb68f00-eaec-11ea-9543-b1acb86154ab.png)
What's the difference here?

2020-08-30 22:12 UTC, andlar commented on src/app/services/login.service.spec.js
> +            it('should know ACB cannot manage any developer', () => {
Pretty sure all ACBs should be able to manage all Developers

2020-08-31 14:19 UTC, tmy1313 commented on src/app/pages/listing/history/history.component.js
> +            if (prev.rwtPlanUrl !== curr.rwtPlanUrl) {
We discussed this last week, and Jim did not feel this was a problem.

2020-08-31 15:26 UTC, tmy1313 commented on src/app/pages/listing/listing.scss
> +    display: grid;
https://chpl.ahrqdev.org/#/listing/10414

2020-08-31 16:14 UTC, andlar commented on src/app/pages/listing/listing.scss
> +    display: grid;
Taking off the "display: grid" value makes almost no difference; it brings the next section a few pixels up on the screen. We already have a ton of unused/wasted CSS. While I have no problem leaving the class in the HTML for XPATH/CSS/future-proofing reasons, I'd rather remove the class entirely from the css, as the styling doesn't make any significant difference

2020-08-31 16:14 UTC, andlar commented on src/app/services/login.service.spec.js
> +            it('should know ACB cannot manage any developer', () => {
Test description doesn't match execution

Also, can you add a linebreak between tests? Stacking them all together is not consistent with our other test files

2020-08-31 16:14 UTC, andlar commented on src/app/services/util.service.js
> +        function displayRealWorldTesting (listing) {
Not sure if this util function is needed. It's only in one place, and could be replaced with `ng-if="$ctrl.listing.rwtEligibilityYear...` which would be clear, not add to our `util` service (which is already a service I wish we didn't have) and wouldn't require adding tests to the `util.service.spec.js` file

2020-09-03 10:44 UTC, kekey1 approved these changes

2020-09-03 10:45 UTC, kekey1 requested changes
Needs conflict resolved in yarn file; otherwise I don't have any comments to add.

2020-09-03 12:45 UTC, andlar requested changes

2020-09-03 12:45 UTC, andlar commented on src/app/components/listing/edit.component.js
> +                this.listing.rwtPlanSubmissionDate = this.listing.rwtPlanSubmissionDateObject.getTime();
These dates are LocalDate objects in Java, now, right? So they won't be of type `long` in the API, which means this init & save stuff is using the wrong types of the dates

2020-09-21 19:26 UTC, kekey1 requested changes

2020-09-21 19:26 UTC, kekey1 commented on src/app/admin/components/certifiedProduct/management.directive.js
> +        //vm.localDateToString = DateUtil.localDateToString;
Do we need the commented out line?

2020-09-21 19:58 UTC, andlar requested changes

2020-09-21 19:58 UTC, andlar commented on src/app/admin/components/certifiedProduct/listing/edit.controller.js
> +                vm.cp.rwtResultsCheckDateObject = new Date(vm.cp.rwtResultsCheckDate);
Why is the `Plans` one different from the `Results` one? They're the same object type coming from the API, right?

2020-09-21 19:58 UTC, andlar commented on src/app/admin/components/certifiedProduct/listing/edit.html
> +              <input class="input-sm form-control" type="url" ng-model="vm.cp.rwtPlansUrl" id="rwt-plans-url" name="rwtPlansUrl" ng-maxlength="1024">
This input needs a URL validation to reduce the chance of an improperly formatted URL getting into the system

2020-09-21 19:58 UTC, andlar commented on src/app/admin/components/certifiedProduct/listing/edit.html
> +            <label class="col-sm-6 control-label" for="rwt-plans-check-date">Plans Last ONC-ACB Completeness Check</label>
```suggestion
            <label class="col-sm-6 control-label" for="rwt-plans-check-date">Plans' Last ONC-ACB Completeness Check</label>
```

Is this possessive? Should there be an apostrophe here?

2020-09-21 19:58 UTC, andlar commented on src/app/pages/listing/history/history.component.js
> +
Extra blank line here isn't needed

2020-09-22 17:32 UTC, andlar approved these changes
Will leave the comment about text changes around, but let that go to the PO. I'm good with the functionality here

2020-09-22 18:14 UTC, kekey1 approved these changes, later dismissed

2020-09-28 13:42 UTC, andlar requested changes

2020-09-28 13:42 UTC, andlar commented on src/app/pages/listing/history/history.component.js
> +                    activity.change.push('Real World Testing Plans URL changed from ' + prev.rwtPlansUrl + ' to ' + curr.rwtPlansUrl)
Missing a semi-colon, as the linter calls out

2020-09-28 13:42 UTC, andlar commented on src/app/pages/listing/history/history.component.js
> +                    activity.change.push('Real World Testing Results URL changed from ' + prev.rwtResultsUrl + ' to ' + curr.rwtResultsUrl)
Also missing a semi-colon

2020-10-07 17:47 UTC, andlar commented on src/app/pages/listing/listing.component.js
> +            this.canManageDeveloper = authService.canManageDeveloper;
Don't think these are used any more

2020-10-07 17:47 UTC, andlar commented on src/app/pages/listing/listing.html
> +            <h2>Real World Testing</h2>
Why doesn't this have the same class as the other `<h2>` items in this file?

2020-10-08 12:21 UTC, andlar approved these changes

2020-10-12 14:10 UTC, kekey1 approved these changes

2020-10-13 15:17 UTC, merged