OCD-3456 - Update Product Report and DR to use js-joda library
chpladmin/chpl-website pull request #796
Opened 2020-09-02 14:02 UTC by tmy1313

OCD-3456

2020-09-08 11:16 UTC, kekey1 submitted a review, later dismissed

2020-09-08 12:11 UTC, andlar requested changes

2020-09-08 12:11 UTC, andlar commented on src/app/services/date-util.service.js
> +        if (date && date.month && date.dayOfMonth && date.year) { //This maps perfectly to a js-joda LocalDate
These values are in a js-joda LocalDate object, but the object that comes back from our API doesn't have the `.format` method. Loading a Listing with a DR (the only place where this function is used with that Java LocalDate type) gives the error:

```
TypeError: date.format is not a function
    at DateUtil.localDateTimeToString (date-util.service.js:47)
    at DateUtil.getDisplayDateFormat (date-util.service.js:35)
    at view.component.js:39
    at Array.map (<anonymous>)
    at DirectReviewsNonConformitiesController.$onChanges (view.component.js:34)
```

2020-09-08 12:11 UTC, andlar commented on src/app/services/date-util.service.spec.js
> -                expect(date.getDisplayDateFormat(mock.dateObject)).toBe('Sep 22, 2020');
This is the "shape" of the object that comes back from our API. Our mock data should match what the API returns

2020-09-08 17:00 UTC, andlar commented on src/app/components/direct-reviews/non-conformities/view.component.spec.js
> +                DateUtil.getDisplayDateFormat.and.returnValue('aaa');
Is this needed? No other changes were made by the view component, right?

2020-09-08 18:01 UTC, andlar submitted a review, later dismissed

2020-09-08 18:59 UTC, kekey1 submitted a review, later dismissed

2020-09-10 17:16 UTC, andlar approved these changes

2020-09-14 14:21 UTC, kekey1 approved these changes

2020-09-14 14:48 UTC, merged