Ocd 3474
chpladmin/chpl-website pull request #798
Opened 2020-09-09 18:53 UTC by palakpatel311

2020-09-12 15:44 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +        loginComponent.loginAsACB();
The "loginComponent.logIn('acb')" method should be in staging now, which means you ought to be able to use that here so we can work to remove this `loginAsACB` method

2020-09-15 00:43 UTC, kekey1 approved these changes, later dismissed
Nothing to add beyond Andrew's comment

2020-09-15 13:05 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +        loginComponent.loginAsACB();
This is still in ready for test

2020-09-15 14:29 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +        loginComponent.loginAsACB();
I don't see this as having changed

2020-09-15 14:37 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.spec.js
> +        loginComponent.loginAsACB();
done

2020-09-15 15:12 UTC, andlar approved these changes, later dismissed

2020-09-15 15:14 UTC, kekey1 submitted a review, later dismissed

2020-09-28 23:38 UTC, andlar approved these changes, later dismissed

2020-09-29 12:27 UTC, kekey1 submitted a review, later dismissed

2020-09-29 13:23 UTC, kekey1 requested changes

2020-09-29 13:23 UTC, kekey1 commented on yarn.lock
> +<<<<<<< HEAD
this still looks like a conflict

2020-09-29 13:26 UTC, palakpatel311 commented on yarn.lock
> +<<<<<<< HEAD
done

2020-09-29 13:28 UTC, kekey1 approved these changes

2020-09-29 14:51 UTC, andlar approved these changes

2020-09-29 20:14 UTC, merged