OCD 3487: Create AQA testing for CMS ID
chpladmin/chpl-website pull request #803
Opened 2020-09-25 00:48 UTC by palakpatel311

2020-09-29 18:18 UTC, kekey1 requested changes

2020-09-29 18:18 UTC, kekey1 commented on e2e/components/cms-widget/cms-widget.po.js
> +    missingBaseCriteriaListAnd: '.cms-widget__missing-and',
A locator was also added for "cms-widget__missing-additional" - do we need to test that one too?

2020-09-29 18:18 UTC, kekey1 commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +            assert.isFalse(cms.missingBaseCriteriaListAnd.isDisplayed());
Also this one? "cms-widget__missing-additional"

2020-09-29 18:18 UTC, kekey1 commented on wdio.conf.js
> +                reject(new Error('File did not exists and was not created during the timeout.'));
```suggestion
                reject(new Error('File did not exist and was not created before the timeout.'));
```

2020-09-30 12:37 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.po.js
> +    missingBaseCriteriaListAnd: '.cms-widget__missing-and',
How do we get this? I tried couple of listing even with 0% but I did not see this.

2020-09-30 14:21 UTC, kekey1 commented on e2e/components/cms-widget/cms-widget.po.js
> +    missingBaseCriteriaListAnd: '.cms-widget__missing-and',
Turns out those "combo" messages only appear if you try to create a CMS ID with a combination of 2014 and 2015 listings. Since there is no longer a "+ CMSID" button next to any of the 2014 listings I guess there is nothing to test!

2020-09-30 14:21 UTC, kekey1 submitted a review, later dismissed

2020-09-30 20:02 UTC, andlar requested changes

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.po.js
> +        return $(asserts.noProductsSelected);
What is the difference between `asserts` and `elements`?

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let ListingId1 = 9851;
We use `camelCase` on variables, not `PascalCase`. The only place with `PascalCase` is for Classes

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let search1 = '2621';//using developer code to search listing
Is this developer code or developer database ID?

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let chplPublicGuide = 'https://www.healthit.gov/sites/default/files/policy/chpl_public_user_guide.pdf';
This is an expected value, right? Then it should be `const` not `let`

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +            //Assertion to check if file downloaded ?
What's this comment for?

2020-09-30 20:02 UTC, andlar commented on wdio.conf.js
> +     onComplete: function() {
Why is this function here? It looks like you're trying to remove things after the tests run. I'd lean towards having those things removed as part of the `yarn e2e:clean` command, because removing them by default makes it hard to debug stuff. If we _do_ keep it, the indentation is all off

2020-09-30 20:02 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +            //creating cms id first as they are different cms ids between different environments
Shouldn't create CMS IDs separately. Once a CMS ID has been generated in PROD, it will get to all of our environments, so we should use those as things we can execute tests against.

Even trying to generate a new CMS ID from scratch, if it uses a set of Listings that have already generated a CMS ID, should generate the same one as the first time

2020-09-30 20:02 UTC, andlar commented on e2e/components/cms-widget/cms-widget.po.js
> +    get downloadPDFButton () {
PDF isn't an acronym, or if it is, it's not used that way
```suggestion
    get downloadPdfButton () {
```

2020-10-01 01:51 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.po.js
> +        return $(asserts.noProductsSelected);
I am using asserts to check assertions. such as this text is only used in assertions and which means it is not element on which you could perform any action.

2020-10-01 01:53 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let search1 = '2621';//using developer code to search listing
Developer code

2020-10-01 01:56 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +            //creating cms id first as they are different cms ids between different environments
Agree. But CMSID for listing1 and listing2 is different in dev , qa and stage. so i cant hard code cmsId in cmsId reverse look up.

2020-10-01 02:40 UTC, palakpatel311 commented on wdio.conf.js
> +     onComplete: function() {
Moved this to as part of yarn e2e:clean

2020-10-01 02:40 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.po.js
> +    get downloadPDFButton () {
Updated

2020-10-01 02:41 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +            //Assertion to check if file downloaded ?
Removed

2020-10-01 02:41 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let chplPublicGuide = 'https://www.healthit.gov/sites/default/files/policy/chpl_public_user_guide.pdf';
Changed

2020-10-01 02:41 UTC, palakpatel311 commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +let ListingId1 = 9851;
Changed

2020-10-02 19:43 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +            //creating cms id first as they are different cms ids between different environments
Used cmsid created from prod

2020-10-03 17:47 UTC, andlar submitted a review, later dismissed

2020-10-05 10:34 UTC, kekey1 requested changes

2020-10-05 10:34 UTC, kekey1 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +var listingIds = ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'];
Is it possible to use the database IDs here? There are a number of actions that users can do that cause the CHPL Product Numbers to change which would break this test.

2020-10-05 13:37 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +var listingIds = ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'];
No. Assertion here is to check that these IDs shows up on the screen when finding cms id and as well as in pdf. so if i switch to database id, I cant test anything.
But i did add these Ids in aqa wiki so no one should be using it

2020-10-05 13:40 UTC, kekey1 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +var listingIds = ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'];
Understood. I think it's possible a user in prod would make the change and that would migrate down into our test data, but I can live with it!

2020-10-05 13:40 UTC, kekey1 approved these changes, later dismissed

2020-10-05 13:42 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +var listingIds = ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'];
Agree. But we have to see if these listings will change frequently. if it does, we can change listing ids later

2020-10-14 14:05 UTC, andlar requested changes

2020-10-14 14:05 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                var length = $$('//*[@id="lookupCertIdResults"]/tbody/tr').length;
These element locators ought to be in the page object, right?

2020-10-14 14:05 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup-dp.js
> +        listingIds: ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'],
These aren't listing IDs, they're chpl product numbers. IDs are database values

```suggestion
        chplProductNumbers: ['15.07.07.1447.BE02.01.00.1.160815','15.07.07.1447.BE01.02.01.1.161014','15.07.07.1447.EP03.02.03.1.161209','15.07.07.1447.EP03.03.04.1.170403'],
```

2020-10-14 16:17 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                var length = $$('//*[@id="lookupCertIdResults"]/tbody/tr').length;
I think this locator was very specific to this test thats why I dint bother to move that to PO.

2020-10-14 16:26 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                var length = $$('//*[@id="lookupCertIdResults"]/tbody/tr').length;
The locator that is the "length of the rows" is specific to the test, but the locator that is the "rows of the table" would not be, and could be used in other tests to verify that certain listings appeared or didn't appear in the lookup table

2020-10-14 16:46 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
>                      ls.push($('//*[@id="lookupCertIdResults"]/tbody/tr[' + j + ']/td[6]').getText());
This should be a locator too. I've done things in the Product edit where I pass, to the Page Object file, an element, and have that file return some sub-element from that element. Something like 
```suggestion
                    ls.push(page.getChplProductNumber(cmsLookup.rowsLookupResultsTable(j)).getText());
```

2020-10-14 17:05 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
>                      ls.push($('//*[@id="lookupCertIdResults"]/tbody/tr[' + j + ']/td[6]').getText());
Not sure if it will work in this case as its table, but i did what i think will be fine here.

2020-10-14 17:09 UTC, andlar submitted a review, later dismissed

2020-10-14 17:28 UTC, kekey1 requested changes

2020-10-14 17:28 UTC, kekey1 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                var isInclude = false;
I think if _any_ of the chplProductNumbers are found this will be "true" but do we want to check that _all_ of them are found? Needs the logic reorganized a bit.

2020-10-14 20:20 UTC, andlar requested changes

2020-10-14 20:20 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.po.js
> +
Why is this added?

2020-10-14 20:20 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +    for (const i in inputs) {
This looks weird. `i` is usually the indexing variable, which _must_ change. But `const` variables don't change. What's going on here?

2020-10-14 20:20 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                assert.equal(isInclude,inputs[i].chplProductNumbers.length, 'All chpl product numbers arent present in the download file');
`arent` isn't a word. It should be `aren't`, as these error messages ought to be grammatically correct

2020-10-14 20:20 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +                var isInclude = 0;
`isInclude` looks like a boolean value. It shouldn't be used to hold a count of anything

2020-10-15 14:09 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.po.js
> +
This is the way i am getting chplproduct number from table in the spec file

2020-10-15 14:10 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +    for (const i in inputs) {
so beforeall in the describe block seems to be changing i values and running it for only third values from array(I think its running in async mode but not positive) so i have to keep i as const through out one describe block.
I value will still get increased after iteration.

2020-10-15 15:32 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.po.js
> +
The line I was asking about was the added blank line. Not the locator

2020-10-15 15:35 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +    for (const i in inputs) {
What about?
```suggestion
    inputs.forEach(input => {
```

Then, anywhere below you're using `inputs[i]` you can replace it with just `input`?

2020-10-15 15:38 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +    for (const i in inputs) {
Tried. It sys 0 test and doesnt run anything

2020-10-15 16:13 UTC, andlar approved these changes

2020-10-15 18:10 UTC, kekey1 approved these changes

2020-10-15 18:11 UTC, merged