OCD-3508- Edit SVAP information for specific criteria in listing details
chpladmin/chpl-website pull request #807
Opened 2020-10-01 17:01 UTC by tmy1313

OCD-3508

2020-10-02 13:02 UTC, andlar requested changes

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.js
> +                    .filter(svap=> !(svap.svapId === action.item.item.svapId));
```suggestion
                    .filter(svap => svap.svapId !== action.item.item.svapId);
```
The "test data" filter has the "not (this and this and this)" construct because there are multiple values to check. Test standard, which is similar in that it only has the standard, just does the id !== id check. Request the simpler check

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +    fdescribe('the Certification Criteria Modal controller', () => {
```suggestion
    describe('the Certification Criteria Modal controller', () => {
```

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                    //    {svapId: 1, regulatoryTextCitation: 'reg1', approvedStandardVersion: 'ver1'},
Please delete

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                scope.resolve.cert = ({
Why not just put these values in the `mock.cert` object defined at the top of the file?

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/edit.html
> +          <td ng-if="$ctrl.cert.testStandards && $ctrl.cert.testStandards.length > 0 && !$ctrl.canEdit()">
Why are you adding test standard stuff to this row?

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/view.html
> +              Standards Version Advancement Process <button class="btn btn-link btn-xs pull-right" uib-tooltip="TBD" tooltip-trigger="'mouseenter focus click'"><span class="sr-only">TBD</span><i clas
Reminder for the TBD

2020-10-02 13:02 UTC, andlar commented on src/app/components/listing/details/criteria/view.html
> +                  <span ng-if="m.approvedStandardVersion"><ai-ellipsis text="{{ m.regulatoryTextCitation + ' ' + m.approvedStandardVersion }}" max-length="100" word-boundaries="true"></ai-ellipsis></
Aren't you building the display value in the component? Why concatenate those values again here?

2020-10-02 13:02 UTC, andlar commented on src/app/components/util/expandable-list.component.js
> +            selectedItem.item.name = selectedItem.item[this.itemText];
Curious why this needed to be added when none of the other expandable-list stuff changed, and it didn't look like the SVAP stuff needed anything special from this component

2020-10-05 18:04 UTC, kekey1 approved these changes, later dismissed
Nothing to add to Andrew's comments

2020-10-06 02:13 UTC, tmy1313 commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                scope.resolve.cert = ({
Honestly, I couldn't figure out where it goes.  That string is not formatted, and is difficult to follow.  I think there is a lot of data in there that is not used by the tests.

2020-10-06 02:31 UTC, tmy1313 commented on src/app/components/listing/details/criteria/view.html
> +                  <span ng-if="m.approvedStandardVersion"><ai-ellipsis text="{{ m.regulatoryTextCitation + ' ' + m.approvedStandardVersion }}" max-length="100" word-boundaries="true"></ai-ellipsis></
I'm building the display value in the edit component, not the view component.  I need it in the edit component for the expandable list control.  Should i change this?

2020-10-06 12:19 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                scope.resolve.cert = ({
The `scope.resolve` object is created in line 42. In that object, the cert is a copy of the `mock.cert` object, which is created on line 8. If you add the `allowedSvaps` and `svaps` from lines 55-60 to just after line 20 it'll put these things there. What string are you talking about that's "not formatted"? The `mock.resources` has a lot of stuff, but you shouldn't need to touch that

2020-10-06 12:19 UTC, andlar commented on src/app/components/listing/details/criteria/view.html
> +                  <span ng-if="m.approvedStandardVersion"><ai-ellipsis text="{{ m.regulatoryTextCitation + ' ' + m.approvedStandardVersion }}" max-length="100" word-boundaries="true"></ai-ellipsis></
No, this is fine. Missed that this is in the view component

2020-10-06 20:30 UTC, tmy1313 commented on src/app/components/util/expandable-list.component.js
> +            selectedItem.item.name = selectedItem.item[this.itemText];
This was actually a bug in the expandable list component.  All other instances of the component use `item-text = "name"` .  The svap instance of the expandable list component, uses `item-text = "displayText"`.  So `selectedItem.item.name` always worked.  But when I used a different attribute name for the item name (displayText), there was nothing to display.  Can discuss further with you if you would like.

2020-10-06 20:31 UTC, andlar submitted a review, later dismissed

2020-10-07 10:32 UTC, kekey1 submitted a review, later dismissed

2020-10-15 15:42 UTC, andlar commented on src/app/pages/reports/listings/listings.component.js
> +                    obj.changes.push('<li>SVAP changes<ul>');
This doesn't have the same structure as the testToolsUsed report stuff. Does this report changes in multiple SVAP at the same time? SVAP and Test Tools have the same basic structure, right? If so, why aren't the tests against changes the same?

2020-10-15 17:02 UTC, andlar approved these changes, later dismissed

2020-10-15 17:21 UTC, kekey1 approved these changes, later dismissed

2020-12-10 15:11 UTC, andlar commented on src/app/components/listing/details/criteria/view.scss
> +.criteria__tooltip-button {
This looks like a candidate for an `atoms.scss` style

2020-12-14 17:01 UTC, andlar approved these changes, later dismissed

2020-12-14 19:16 UTC, kekey1 approved these changes, later dismissed

2020-12-17 14:13 UTC, andlar requested changes

2020-12-17 14:13 UTC, andlar commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                        }
This line reports a linting error about commas. There are a few others that show up when running the tests. During that execution the linting errors are displayed for the *.spec.js files. Doesn't need to be fixed now, but does before it goes to staging

2021-01-12 21:44 UTC, tmy1313 commented on src/app/components/listing/details/criteria/edit.component.spec.js
> +                        }
I did not get an error about this particular file, but fixed another linting error.  Let m know if this is still an issue.

2021-01-13 11:31 UTC, kekey1 approved these changes, later dismissed

2021-01-13 12:44 UTC, andlar requested changes

2021-01-13 12:44 UTC, andlar commented on src/app/components/listing/details/criteria/view.html
> +            <td ng-if="$ctrl.cert.svaps && $ctrl.cert.svaps.length > 0">
Why is the `ng-if` here? With this `if` and the `ng-if` in the `<tr>` above, if the listing has an empty array of svaps we'd have a table row with no data inside it, which breaks the rules of HTML (I know, I know, "HTML rules", but still...)

If the SVAP data shouldn't be there at all when there isn't data, then the `ng-if` should be in the `<tr>` check. If it should show something like "SVAP: none", when there aren't any, then this first `<td>` of the row should keep the SVAP td always, and there should be two other `<td>` options; one that shows when there's data, one that shows "none" when there isn't, in a similar fashion to how the "Standard" below works

2021-01-13 12:44 UTC, andlar commented on src/app/components/listing/details/criteria/edit.html
> +          <td ng-if="$ctrl.cert.svaps && $ctrl.cert.svaps.length > 0 && !$ctrl.canEdit()">
When does this `<td>` get displayed? The way I read it, if it's displayed there's no heading for the section

2021-01-13 16:46 UTC, tmy1313 commented on src/app/components/listing/details/criteria/edit.html
> +          <td ng-if="$ctrl.cert.svaps && $ctrl.cert.svaps.length > 0 && !$ctrl.canEdit()">
If for some reason the criterion were removed and the user is ROLE-ACB, they would only "see" the existing SVAPs for the criterion.  Let me know if this isn't correct.

2021-01-13 18:08 UTC, kekey1 submitted a review, later dismissed

2021-01-21 13:51 UTC, andlar approved these changes

2021-01-21 14:08 UTC, kekey1 approved these changes

2021-01-21 16:18 UTC, merged