OCD-3443: Add AQA for listings and ACB name on products bar for a developer
chpladmin/chpl-website pull request #808
Opened 2020-10-08 13:19 UTC by palakpatel311

[#OCD-3443]

2020-10-09 11:20 UTC, andlar requested changes

2020-10-09 11:20 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +        browser.setWindowSize(1600, 1024);
These first four lines don't do anything that are needed for the tests, right? So why have them?

2020-10-09 11:20 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +describe('When user is on the Developer page for a Developer that doesnt exist', () => {
```suggestion
describe('when a user is on the Developer page for a Developer that doesn\'t exist', () => {
```

2020-10-09 11:20 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +    it('it should go to Home page', () => {
```suggestion
    it('should go to Home page', () => {
```

Don't need the "double it"

2020-10-09 11:20 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +            it('should have ACB name', () => {
This is the same `it` block as the previous test

2020-10-13 15:45 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +                browser.waitUntil(() => page.getVersionCount(product).isDisplayed());
Is this still needed? I think it was here originally because we had to wait for the "get products" and "get versions" calls to finish, but with those no longer happening I don't think we need to wait for anything. Once the product can be scrolled into view it should be fully complete

2020-10-13 20:17 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +                browser.waitUntil(() => page.getVersionCount(product).isDisplayed());
Removed and its working

2020-10-14 10:58 UTC, andlar approved these changes

2020-10-14 14:07 UTC, tmy1313 approved these changes

2020-11-10 18:47 UTC, merged