OCD-3434: Create Upload for Real World Testing
chpladmin/chpl-website pull request #816
Opened 2020-10-15 15:32 UTC by tmy1313

2020-10-16 14:48 UTC, andlar requested changes
I was trying really hard to find something to ask to be changed, and was sad. But then a file appeared that probably shouldn't be here at all! Oh joyous day!

Anyway, the only requested change is that I think there's some extra stuff here that shouldn't be. The functionality as per the Feature looks great!

2020-10-16 14:48 UTC, andlar commented on src/app/pages/listing/listing.html
> +              <label for="rwtRsultsURL">Results</label>
Two things:
1) I think the change to this file shouldn't be in this PR
2) If it is, the "for" value should be an id, which should be in the dash-case format, not the camelCase one, and "results" is misspelled

2020-10-19 17:35 UTC, andlar approved these changes

2020-10-19 17:54 UTC, kekey1 approved these changes

2020-11-24 15:28 UTC, merged