feat: remove references to  effective-rule-date-plus-three-months and…
chpladmin/chpl-website pull request #817
Opened 2020-10-21 19:40 UTC by tmy1313

… update text

OCD-3532

2020-10-22 18:19 UTC, kekey1 submitted a review, later dismissed

2020-10-23 11:04 UTC, andlar approved these changes

2020-10-23 11:06 UTC, andlar requested changes
I think this is the only place where the feature-flags component is used in the resources module, which means the `pages/resources/resources.module.js` shouldn't import the `feature-flags` tool any more

2020-10-26 17:11 UTC, andlar submitted a review, later dismissed

2020-10-26 17:21 UTC, kekey1 approved these changes, later dismissed

2020-11-02 14:21 UTC, andlar approved these changes

2020-11-02 14:26 UTC, kekey1 approved these changes

2020-11-02 15:47 UTC, merged