Ocd 3484
chpladmin/chpl-website pull request #821
Opened 2020-10-28 12:18 UTC by palakpatel311

2020-11-02 18:31 UTC, andlar requested changes

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search-home.readonly.spec.js
> +        assert.isTrue(page.homeSearchPageButtons('API Info for 2015 Ed. Products').isDisplayed());
This doesn't assert anything about clickability

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search-home.readonly.spec.js
> +        assert.equal(page.homeSearchPageButtons('SED Info for 2015 Ed. Products').isDisplayed(),true);
Why are these `assert.equal` but the ones for API documentation are `assert.isTrue`? I'd prefer the second type, because checking against `= true` is literally what the assert says, but in either case they ought to be the same

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +var countBefore;
Generally speaking we shouldn't have global variables. These ought to be defined and used in the scope where they're needed

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +            assert.isAbove(count,500);
Why is the number 500 being used? It ought to be saved as a const as well, with a meaningful name, to avoid the use of magic numbers

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +                assert.include(page.getColumnText(i,3),productName);
The `3` here ought to be a const as well. Something like `const PRODUCT_COL_IDX = 3;`

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +            assert.isBelow(countAfter,countBefore);
Setting the "retired" status to true should mean there are _more_ listings, not fewer, right? So why is the assert asserting that something `isBelow`?

2020-11-02 18:31 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +        it('should atleast show 1 retired listing', () => {
```suggestion
        it('should at least show 1 retired listing', () => {
```

2020-11-03 19:30 UTC, palakpatel311 commented on e2e/pages/search/search-home.readonly.spec.js
> +        assert.equal(page.homeSearchPageButtons('SED Info for 2015 Ed. Products').isDisplayed(),true);
Oops. I missed these.

2020-11-03 19:35 UTC, palakpatel311 commented on e2e/pages/search/search.readonly.spec.js
> +            assert.isAbove(count,500);
I used 500 hoping that listings will be more than that number always. But welcome for suggestion.
I will move that number to be constant.

2020-11-06 13:35 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +    var countAfter;
It's better that these aren't global in scope, but they're still not deep enough. Most of the describe blocks don't use these variables; these variables should only exist in scopes where they're needed. If there are groups of the describe blocks below that all need these, then that group of describe blocks ought to be grouped in a describe block together

2020-11-06 13:35 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +const CHPLID_COL_IDX = 6;
Suggest calling this "CHPL_PRODUCT_NUMBER_COL_IDX". The "CHPL ID" is the database ID, and though we sometimes refer to that product number as the id, it's not really correct

2020-11-06 13:35 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +            assert.equal(true, isInclude);
Any reason this isn't assert.isTrue?

2020-11-06 17:32 UTC, andlar submitted a review, later dismissed

2020-11-09 14:52 UTC, andlar approved these changes

2020-11-09 17:39 UTC, ashwinimore approved these changes

2020-11-09 17:39 UTC, ashwinimore commented on e2e/pages/search/search.readonly.spec.js
> +describe('On search page- When searching listings by ONC-ACB Id', () => {
'When searching listings by _CHPL ID_ or _CHPL product number_' instead of  ONC-ACB ID.
That's my only comment, not holding off on approval just for this, make edit when you can

2020-11-09 17:53 UTC, palakpatel311 commented on e2e/pages/search/search.readonly.spec.js
> +describe('On search page- When searching listings by ONC-ACB Id', () => {
This test is for searching listing by ONC-ACB Id, there is a separate test for searching listing by CHPL id.

2020-11-09 17:59 UTC, ashwinimore commented on e2e/pages/search/search.readonly.spec.js
> +describe('On search page- When searching listings by ONC-ACB Id', () => {
ref: prev. comment- looking at acbID parameter, looks like this one is searching listings by ONC-ACB Id

2020-11-09 18:02 UTC, palakpatel311 commented on e2e/pages/search/search.readonly.spec.js
> +describe('On search page- When searching listings by ONC-ACB Id', () => {
Looks like you are looking at outdated file. I see onc-acb id only once in latest file

2020-11-09 18:51 UTC, ashwinimore commented on e2e/pages/search/search.readonly.spec.js
> +describe('On search page- When searching listings by ONC-ACB Id', () => {
I reviewed commit by commit so that's possible(i did see updates for other things I came across but didn't one for this), it appears that it's already taken care of then

2020-11-13 15:50 UTC, merged