OCD 3554: AQA test for new role ONC_STAFF
chpladmin/chpl-website pull request #830
Opened 2020-11-19 14:12 UTC by palakpatel311

2020-11-19 22:58 UTC, ashwinimore commented on e2e/pages/users/user.spec.js
> +    });
I am thinking ....when this test runs for the first time, it works for the purpose where the original value is cleared and then 'Mr' is added & saved. On next run, even if the save doesn't go through, the test will pass because it had worked on previous run and 'Mr' input was saved. Does that sound correct? If yes, then using something dynamic like date function can help with new input value everyday (won't work for multiple runs on same day but good for overnight runs). I have same thoughts on phoneNumber test below.

2020-11-20 00:12 UTC, palakpatel311 commented on e2e/pages/users/user.spec.js
> +    });
Maint plan in bamboo does take copy of DB before running any test and sets it back after test to the same DB copy as taken before test.

2020-11-20 13:13 UTC, andlar requested changes

2020-11-20 13:13 UTC, andlar commented on e2e/components/login/login.readonly.spec.js
> +    it('should be able to log in as developer with an email address', () => {
This test will fail (or at lest should) on STG, as this depends on the role-developer flag being turned on

2020-11-20 13:13 UTC, andlar commented on e2e/pages/users/user.spec.js
> +        page.userPhoneNumber.addValue('000-000-0000');
What if you generated a phone number by doing something like:
```
let number = (new Date()).getTime() % 1000000;
```
That way you'd have a number that would be mostly unique each time it ran, and (on the off change) someone editing this user to have a phone number of 000-000-0000 we'd still have a valid test

2020-11-20 13:13 UTC, andlar commented on e2e/pages/users/user.spec.js
> +        actionBarComponent.save();
If this works I think that's a problem. I don't think a user should be able to unlock themselves, even if they're logged in. Or at least, there's an argument to be made that that could be the case. It's possible that maybe _no_ user should be able to modify their own "checkbox" states. One way to fix that in this test would be for the acting user to be not ROLE_ONC_STAFF, but instead ROLE_ONC or ROLE_ADMIN. I recognize that doesn't help with the requirement for ROLE_ONC_STAFF to be able to manage other ROLE_ONC_STAFF users, but I think the only way to do that would be to create two ROLE_ONC_STAFF users and use one to manage the other

2020-11-20 13:15 UTC, andlar commented on e2e/pages/users/user.spec.js
> +    });
Palak's right about the plan resetting the database after the run, which is why this test isn't in a `user.readonly.spec.js` file. That said, it wouldn't be a bad idea to make the title that the user is set to have be something that's somewhat random, even if the randomness is just based on a `new Date()` value in some way. That way, if for some reason someone edits this user, outside of the tests, to have a title of "Mr", the test will still be valid

2020-11-20 15:27 UTC, palakpatel311 commented on e2e/components/login/login.readonly.spec.js
> +    it('should be able to log in as developer with an email address', () => {
Oh yes, I can comment it out for now then

2020-11-20 18:40 UTC, palakpatel311 commented on e2e/pages/users/user.spec.js
> +    });
Done

2020-11-20 18:41 UTC, palakpatel311 commented on e2e/pages/users/user.spec.js
> +        page.userPhoneNumber.addValue('000-000-0000');
Done

2020-11-20 18:41 UTC, palakpatel311 commented on e2e/pages/users/user.spec.js
> +        actionBarComponent.save();
ROLE_ONC_STAFF can check checkboxes for  unlock, enabled them selves and password change in next login right now. So this is a problem/issue. This is open question to PO.
I have changed this TC as admin logs in and edit on staff roles details.

2020-11-22 15:50 UTC, andlar commented on e2e/components/login/login.readonly.spec.js
> +    // it('should be able to log in as developer with an email address', () => {
Not sure if our system supports it for the AQA tests, but the unit tests in this feature can ignore a test by marking it as `xit` instead of `it`, and it will e`x`clude that test
```suggestion
    xit('should be able to log in as developer with an email address', () => {
```

2020-11-23 14:31 UTC, ashwinimore approved these changes, later dismissed

2020-11-23 15:22 UTC, andlar commented on e2e/components/login/login.readonly.spec.js
> +    //     component.logInWithEmail('developer');
When the test is ignored, the code inside the test shouldn't be commented out. We shouldn't have commented out code in our system at all

2020-11-23 15:27 UTC, andlar submitted a review, later dismissed

2020-11-23 15:49 UTC, ashwinimore approved these changes, later dismissed

2020-12-10 15:11 UTC, kekey1 approved these changes

2020-12-10 15:20 UTC, andlar approved these changes

2020-12-10 15:46 UTC, merged