OCD 3208: AQA test for merging versions
chpladmin/chpl-website pull request #832
Opened 2020-12-02 14:13 UTC by palakpatel311

2020-12-02 23:49 UTC, andlar requested changes

2020-12-02 23:49 UTC, andlar commented on e2e/pages/organizations/developers/developers.po.js
> +    getVersionMerge () {
The method name suggests it returns an object, but the functionality does a `click`. That disconnect makes this harder to tell what's happening

2020-12-02 23:49 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +
Is there a reason to add this space? I'd rather have spaces added in between the `it` blocks, and not during all of the closing places. That's the way the ~1700-ish unit tests have the spacing laid out (mostly)

2020-12-02 23:49 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +                it('should create new version successfully', () => {
What happens if this test runs before the two above? If tests can be rearranged and they fail, then the tests aren't independent. I'd suggest that for any test that changes data, it should use data that no other test depends on. I think both of the above tests should be in a `.readonly` file, as they could be run at any time

2020-12-02 23:49 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +                let name = 'Greenway Intergy Meaningful Use Edition';
For these things, if they're `let`, they should be defined here as `let name;`, and instanciated in the `beforeEach` block. If they're constants they can defined here as `const name = 'Greenway...';`

2020-12-04 01:14 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.spec.js
> +                it('should create new version successfully', () => {
Above 2 tests uses admin login so I don't think those should be in .readonly spec file.

2020-12-04 13:50 UTC, kekey1 requested changes

2020-12-04 13:50 UTC, kekey1 commented on e2e/pages/organizations/developers/developers.spec.js
> +                    expect(page.getVersionCount(product).getText()).toBe('7 Versions');
Instead of looking for a count (which could *not* be 7 if the test below that actually completes merge runs BEFORE this test - and the order is not guaranteed) could you just assert that "v11" is still in the list of available versions to merge? Meaning that nothing happened and the cancel worked.

2020-12-04 13:50 UTC, kekey1 commented on e2e/pages/organizations/developers/developers.spec.js
> +                it('should create new version successfully', () => {
I don't know the standard for when something is readonly but I tend to agree with Andrew that the tests above do not modify the developer data since they do not complete a merge. I don't really see login as changing data (although I could see the argument of it changes the user's last login time but that seems trivial). I'd vote for moving the tests that cancel the merge and try to complete the merge w/o required data to readonly

2020-12-04 13:50 UTC, kekey1 commented on e2e/pages/organizations/developers/developers.spec.js
> +                    page.moveVersionToBeMerged(0);
This is hard to follow for me as far as what is expected from the test. You are merging "v10.10" with "page.moveVersionToBeMerged(0)" - so the first version in the list of available versions. I would find it easier to understand if you specified which version you are merging ("v12" or whatever) and then in the things you assert at the end of the test you can check that neither "v10.10" nor "v12" show up as versions of this product.

2020-12-08 15:28 UTC, kekey1 submitted a review, later dismissed

2020-12-08 19:30 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +beforeEach(async () => {
Can we put this beforeEach block back inside the `the Developers page` describe block, and then move the `when Logged in as an admin` block inside that one too? The actions that are happening in this beforeEach block aren't described anywhere, either with a `describe` or with an `it` block, and I think that makes it less clear when/why things are happening

2020-12-08 19:30 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +        let timestamp = (new Date()).getTime();
```suggestion
        let timestamp;
```

Setting the variable to a value should happen in the 'beforeEach' block. That way, if there were multiple `it` blocks covered by the `beforeEach`, they would each have a different value for the timestamp, which helps ensure we're actually using "random-ish" values for these things

2020-12-08 19:30 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +            version = 'v11';
This one and the `newVersion` values should be set in the beforeEach block too

2020-12-08 19:30 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +beforeEach(async () => {
The "not readonly" script has the above described structure, and I think it makes it more clear

2020-12-08 20:38 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +beforeEach(async () => {
If I move beforeEach block inside describe block, not all other previously added tests needs to have login. Only test which needs login is the one I added. 
I also thought of keeping my added test out of these describe block, bit in that case, it will be duplicate lines of code for the same beforeEach block along with login code.

2020-12-08 20:43 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +        let timestamp = (new Date()).getTime();
Did.

2020-12-08 20:43 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +            version = 'v11';
Done

2020-12-10 13:49 UTC, kekey1 approved these changes, later dismissed

2020-12-10 14:25 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +beforeEach(async () => {
While it's true that only a few of the other tests need to have a logged in user, you could nest those tests inside the "the Developers page" block too. The other problem with moving this beforeEach block out here is that it now is affecting the block with the describe: "When a user is on the Developer page for a Developer that doesn\'t exist", which it shouldn't do

2020-12-10 15:54 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +            let timestamp = (new Date()).getTime();
This assignment should happen inside the `beforeEach` block

2020-12-10 15:54 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +                let newVersion = 'New version - ' + timestamp;
Same comment re: assignment

2020-12-10 16:14 UTC, andlar submitted a review, later dismissed

2020-12-10 16:27 UTC, kekey1 submitted a review, later dismissed

2020-12-18 21:03 UTC, andlar reviewed
Why does this PR have all of the commits from the feature branch for OCD-3208?

2021-01-12 14:19 UTC, andlar approved these changes

2021-01-12 15:15 UTC, kekey1 approved these changes

2021-01-13 21:18 UTC, merged