OCD 3584: ONC Staff access to scheduled and background job page
chpladmin/chpl-website pull request #847
Opened 2021-01-15 15:40 UTC by palakpatel311

2021-01-22 18:07 UTC, andlar requested changes

2021-01-22 18:07 UTC, andlar commented on e2e/pages/administration/jobs/background/background.spec.js
> +describe('ONC-Staff user can see', () => {
When in `describe` blocks, the phrasing I usually use is something where the text in the describe phrase should explain the setup, so here it'd be something like 
```suggestion
describe('when an ONC-Staff user is logged in', () => {
```

2021-01-22 18:07 UTC, andlar commented on e2e/pages/administration/jobs/background/background.spec.js
> +    it('correct background jobs', () => {
`it` blocks be should in the form "should <fill in the blank>", so here I'd go with something like 
```suggestion
    it('should see the right set of background jobs', () => {
```

2021-01-22 18:07 UTC, andlar commented on e2e/pages/administration/jobs/background/background.spec.js
> +        assert.equal(actualResult.toString(),expectedResult.toString());
This test doesn't change data, right? So the file could be `background.readonly.spec.js` right?

2021-01-22 18:07 UTC, andlar commented on e2e/pages/administration/jobs/scheduled/scheduled.spec.js
> +describe('ONC-Staff user can see', () => {
Same comments re: format of `describe` and `it` blocks, as well as the filename itself

2021-01-25 12:44 UTC, andlar approved these changes, later dismissed
I'm leaving some comments with a few things I'd prefer to see changed, or addressed, or discussed, but am okay with this going forward as is as far as the logic goes

2021-01-25 12:44 UTC, andlar commented on e2e/pages/administration/jobs/background/background.po.js
> +    get backgroundJobRowsCount () {
I think this element should just be the rows, not the count of them. A PageObject element that is the count of something isn't really useful for any other purpose, while an object that is a set of Rows could be used to get a count, to iterate through to find an object, to see if it's null, etc. All of those actions could be used in the logic portion of a spec file, but only if the PageObject element is the actual element that's on the page

2021-01-25 12:44 UTC, andlar commented on e2e/pages/administration/jobs/background/background.po.js
> +    backgroundJobNames (rowNumber) {
The object title suggests this is multiple objects that's returned, but it looks like it's only returning the name on the given row, which is singular. Which is it?

2021-01-25 12:44 UTC, andlar commented on e2e/pages/administration/jobs/scheduled/scheduled.po.js
> +    get scheduledJobRowsCount () {
Same comments re: style & pluralization as in the background.po.js file

2021-01-25 12:44 UTC, andlar commented on e2e/pages/administration/jobs/scheduled/scheduled.readonly.spec.js
> +describe('When an ONC-Staff user is logged in', () => {
```suggestion
describe('when an ONC-Staff user is logged in', () => {
```
I'd prefer to keep all of our `describe` and `it` block text lower-case. The basic reason is that these sentence fragments can be combined to make full sentences, but the nesting can change in a variety of ways, and they can change over time, and if we start with a capital letter at one point, but then nest that block later, the capital letter will show up in the middle of a sentence. It's simpler to just keep them all as lowercase, always

2021-01-26 01:57 UTC, andlar submitted a review, later dismissed

2021-01-26 12:48 UTC, athomas-git commented on e2e/pages/administration/jobs/scheduled/scheduled.readonly.spec.js
> +        var expectedResult = ['All Broken Surveillance Rules Report','Developer Access Report','Inherited Certification Status Errors Report','Overnight Broken Surveillance Rules Report','Pending "Ch
Is 'Real World Testing Email Report' job missing for ONC_STAFF ?

2021-01-26 14:32 UTC, palakpatel311 commented on e2e/pages/administration/jobs/scheduled/scheduled.readonly.spec.js
> +        var expectedResult = ['All Broken Surveillance Rules Report','Developer Access Report','Inherited Certification Status Errors Report','Overnight Broken Surveillance Rules Report','Pending "Ch
Yes you are right. Added.

2021-01-26 14:39 UTC, athomas-git approved these changes, later dismissed

2021-01-26 15:14 UTC, andlar submitted a review, later dismissed

2021-01-26 19:01 UTC, ashwinimore submitted a review, later dismissed

2021-01-28 20:23 UTC, athomas-git submitted a review, later dismissed

2021-02-12 18:45 UTC, andlar requested changes

2021-02-12 18:45 UTC, andlar commented on e2e/components/cms-widget/cms-widget.po.js
> +    browser.pause(2000);
Can this be made explicit? After adding an item to the widget, the "processing" thing appears, and the length of the list changes from "whatever it was before" to "before + 1". Either of those things could be used as a check on when it was done processing

2021-02-12 18:45 UTC, andlar commented on e2e/pages/administration/jobs/background/background.readonly.spec.js
> +    browser.pause(2000); //Have to add this wait as jobs gets in order in micro seconds.
If we don't care about the order of the Jobs, and instead only care about the existence of them, we wouldn't need to wait. The test below could loop through the jobs that were found and compare them to a Set of expected jobs, as well as comparing the length of the list to the size of the Set. Any jobs found that don't exist in the Set, or any difference in length, could be asserted against and used as a test

2021-02-12 18:45 UTC, andlar commented on e2e/pages/administration/jobs/background/background.readonly.spec.js
> +    browser.pause(2000); //Have to add this wait as jobs gets in order in micro seconds.
The same could work with the other type of jobs page

2021-02-15 17:05 UTC, andlar requested changes

2021-02-15 17:05 UTC, andlar commented on e2e/pages/administration/jobs/scheduled/scheduled.readonly.spec.js
> +    browser.pause(2000); //Have to add this wait as jobs gets in order in micro seconds
```suggestion
```

2021-02-15 17:05 UTC, andlar commented on e2e/pages/administration/jobs/scheduled/scheduled.readonly.spec.js
> +    assert.isTrue(isExist);
We shouldn't need to loop through these things twice

In pseudocde it should be done with something like:
```
const expected = new Set(['things here'])
// expect the table to have the same number of rows as the expected data
expect(scheduled.scheduledJobsRows.length).toBe(expected.size)

// expect each row in the table to be in the set of expected data
scheduled.scheduledJobRows.forEach(row => {
  expect(expected.contains(row.getText()).toBe(true)
})
```

2021-02-16 13:38 UTC, andlar requested changes

2021-02-16 13:38 UTC, andlar commented on e2e/pages/administration/jobs/background/background.readonly.spec.js
> +      assert.exists(expected , row.getText());
This test won't work as anticipated. Please check out the PR I created that touches on this

https://github.com/palakpatel311/chpl-website/pull/9/files

2021-02-16 15:20 UTC, palakpatel311 commented on e2e/pages/administration/jobs/background/background.readonly.spec.js
> +      assert.exists(expected , row.getText());
I kept the comments for the future references for myself.

2021-02-16 15:53 UTC, andlar approved these changes

2021-02-16 16:00 UTC, athomas-git approved these changes

2021-02-16 20:32 UTC, ashwinimore approved these changes

2021-02-16 21:06 UTC, merged