OCD: 3476 AQA testing for Surveillance Management
chpladmin/chpl-website pull request #848
Opened 2021-01-22 15:33 UTC by palakpatel311

Upload surveillance
Inspect surveillance
Confirm surveillance
Reject surveillance

2021-02-02 15:59 UTC, ashwinimore requested changes

2021-02-02 15:59 UTC, ashwinimore commented on e2e/components/upload/upload-surveillance/upload-surveillance.spec.js
> +    it('can\'t upload valid file format of surveillance activity file', () => {
'invalid' file format

2021-02-02 20:00 UTC, ashwinimore submitted a review, later dismissed

2021-02-03 18:08 UTC, ashwinimore submitted a review, later dismissed

2021-02-03 18:49 UTC, kekey1 requested changes

2021-02-03 18:49 UTC, kekey1 commented on e2e/components/surveillance/edit/surveillanceEdit.po.js
> +const elements = {
Can you change this filename to follow the dash-case convention? surveillance-edit.po.js

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/add_new_requirement_nonconformity.spec.js
> +import UploadSurveillanceComponent from '../../components/upload/upload-surveillance/upload-surveillance.po';
Needs dashes instead of underscores in the filename

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/add_new_requirement_nonconformity.spec.js
> +        it(`should be able to ${testName} without non conformity`, () => {
It's a little thing but when we refer to non-conformities throughout the app we write it like "non-conformity" and if it's a variable name in code it's camelCased like nonConformity.

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/add_new_requirement_nonconformity.spec.js
> +        it(`should not be able to ${testName} as non conformity without adding non conformity`, () => {
non-conformity

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/add_new_requirement_nonconformity.spec.js
> +        it(`should be able to ${testName} with non conformity to randomized surveillance activity`, () => {
non-conformity... not going to add more of these but please check over the files for other places

2021-02-03 18:49 UTC, kekey1 commented on e2e/components/surveillance/edit/surveillanceEdit.po.js
> +    removeNonconformity: '//*[@ng-click="$ctrl.deleteNonconformity(noncon)"]',
In variables in code I have "nonconformity" all over the place in the API but we are changing it to be camelCased (so nonConformity). Can you make those same changes to variable names throughout the files you are updating in this PR?

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/edit_requirement_with_nonconformity.spec.js
> +import UploadSurveillanceComponent from '../../components/upload/upload-surveillance/upload-surveillance.po';
Same comment about underscores vs dashes in the filename

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/edit-surveillance-test/view_edit_surveillance_details.spec.js
> +import UploadSurveillanceComponent from '../../components/upload/upload-surveillance/upload-surveillance.po';
Filename underscores vs dashes

2021-02-03 18:49 UTC, kekey1 commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm_surveillance.spec.js
> +import UploadSurveillanceComponent from '../../components/upload/upload-surveillance/upload-surveillance.po';
Underscores vs dashes in filename... I may have missed some places in the comments so please check around the various files in the PR to keep the naming consistent

2021-02-04 11:46 UTC, kekey1 approved these changes, later dismissed

2021-02-04 15:05 UTC, andlar requested changes

2021-02-04 15:05 UTC, andlar commented on e2e/components/upload/upload-surveillance/upload-surveillance.spec.js
> +describe('When uploading a surveillane activity as ONC-ACB', () => {
```suggestion
describe('when uploading a surveillance activity as ONC-ACB', () => {
```

Capitalization & typo

2021-02-04 15:05 UTC, andlar commented on e2e/config/mainConfig.js
> +    logLevel: 'info',
Could we default this to `warn`, but find some way of running a different log level via the command line? That way we could set it up to have whatever level we need in the automated tests, but when running locally keep the output limited by default

2021-02-04 15:05 UTC, andlar commented on e2e/components/surveillance/edit/surveillance-edit.po.js
> +        {
```suggestion
        } else {
```

2021-02-04 15:05 UTC, andlar commented on e2e/workflowTest/upload-reject-surveillance-test/reject-surveillance-onInspect.spec.js
> +describe('When user rejects a surveillance activity while inspecting uploaded surveillance', () => {
```suggestion
describe('when user rejects a surveillance activity while inspecting uploaded surveillance', () => {
```

2021-02-04 15:05 UTC, andlar commented on wdio.conf.js
> +    specFileRetries: 1,
Is this needed?

2021-02-04 15:05 UTC, andlar commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
What does this do? It seems like an odd thing to have in a global "before" block. What's scrolling into view?

2021-02-04 16:10 UTC, palakpatel311 commented on wdio.conf.js
> +    specFileRetries: 1,
Yes I would like to have it as we were finding random failures in nightly runs. This is helping to clear those out and we are seeing all tests passing from 2-3 days

2021-02-04 16:15 UTC, palakpatel311 commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
It tells browser where to align element vertically and horizontally in visible area and then scrolls that way.

2021-02-04 16:25 UTC, palakpatel311 commented on e2e/config/mainConfig.js
> +    logLevel: 'info',
Changed back to warn and added in readme how to change log level from command line

2021-02-04 17:26 UTC, andlar commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +describe('User can confirm', () => {
```suggestion
describe('when a user has surveillance management abilities', () => {
```

2021-02-04 17:26 UTC, andlar commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +    it('surveillance activity successfully', () => {
```suggestion
    it('should be able to confirm surveillance', () => {
```

2021-02-04 17:26 UTC, andlar commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +describe('User can\'t confirm', () => {
The structure of these describe/it blocks makes composing the sentences they create complicated. The current structure is something like this:

```
User can confirm
  surveillance activity successfully
User can't confirm
  surveillance activity when they add certified requirement which listing is not attested to
User can't confirm
  surveillance activity when they add non-conformity type which listing is not attested to
```

When reading these out loud, with the "describe" replaced with "when" or "given", and the "it" with "it should" or "they should", gives things like

> Given User can confirm it should surveillance activity successfully
> Given User can't confirm it should surveillance activity when they add certified requirement which listing is not attested to
> Given User can't confirm it should surveillance activity when they add non-conformity type which listing is not attested to

This doesn't read well

Something like the below would generate phrases that make sense

```
describe('when confirming surveillance'
  describe('when the user has permissions'
    it('should allow confirmation'
  describe('when the user does not have permissions'
    it('should not allow confirmation when the surveillance has a requirement the listing does not attest to
    it('should not allow confirmation when the surveillance has a non-conformity type the listing does not attest to
```

Writing this out makes me realize the describe blocks aren't really correct. Maybe:

```
describe('when confirming surveillance'
  describe('and the surveillance has good data'
    it('should allow confirmation'
  describe('but the surveillance has bad data'
    it('should not allow confirmation when the surveillance has a requirement the listing does not attest to
    it('should not allow confirmation when the surveillance has a non-conformity type the listing does not attest to
```

2021-02-04 17:26 UTC, andlar commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
`scrollIntoView` is an action that's taking place on `this`, right? Isn't `this` the entire page at this point? What scrolling happens here? If there were screenshots taken immediately before and after this line would there actually be any difference?

2021-02-04 20:29 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +describe('User can\'t confirm', () => {
Both scenarios has user's permission as its done by acb. I rephrased it differently. Let me know if that's not fine.

2021-02-04 20:44 UTC, palakpatel311 commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
Yes but if we don't scroll into view and if there is a pop up/modal open, it creates element intercepted error. Surveillance edit has lot of modals open on each other so this is useful there.

2021-02-05 13:26 UTC, andlar commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
I get that, if we're in the middle of a test. This line runs at the beginning of every test, right? And it scrolls "this" into view, right? But "this" is the entire page, so what actually scrolls? "scrollIntoView", called on an element, will scroll that element into the viewport. Okay, that's good. This is calling that method on the entire page, which is already in view. So what does it do?

2021-02-05 13:27 UTC, andlar commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +describe('when confirming surveillance, ACB', () => {
There are three describe blocks in a row with the same description. Why aren't they all the same block?

2021-02-05 14:03 UTC, palakpatel311 commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
Oh no. This is part of scrollAndClick command. so it will only be called when I call scrollAndClick().
browser.addCommand("scrollAndClick", function () {
        // `this` is return value of $(selector)
        var runInBrowser = function (argument) {
            argument.click();
        };
        this.scrollIntoView({block: 'center', inline: 'center'});
        browser.execute(runInBrowser,this);
        }, true)

2021-02-05 14:06 UTC, palakpatel311 commented on e2e/workflowTest/upload-confirm-surveillance-test/confirm-surveillance.spec.js
> +describe('when confirming surveillance, ACB', () => {
Combined

2021-02-08 12:47 UTC, andlar commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
Oh, I see. The problem then is the indentation. It's not immediately clear that this call is inside that `scrollAndClick` function because it's not indented

2021-02-08 14:43 UTC, palakpatel311 commented on wdio.conf.js
> +        this.scrollIntoView({block: 'center', inline: 'center'});
fixed

2021-02-08 18:44 UTC, andlar approved these changes, later dismissed

2021-02-15 16:58 UTC, andlar approved these changes

2021-02-15 19:13 UTC, kekey1 approved these changes

2021-02-15 19:18 UTC, ashwinimore approved these changes

2021-02-15 19:23 UTC, merged