OCD-3517 - Enable SVAP Administration
chpladmin/chpl-website pull request #851
Opened 2021-02-03 19:45 UTC by tmy1313

2021-02-04 11:38 UTC, kekey1 approved these changes, later dismissed

2021-02-04 11:38 UTC, kekey1 commented on src/app/components/user/user.component.js
> +            this.$log.info('here ' + action);
Is this useful to leave in? If it is that's fine but it looks like the sort of thing you might write when debugging during development so that's why I asked.

2021-02-04 11:38 UTC, kekey1 commented on src/app/navigation/navigation-top.html
> +              <li ng-if="vm.hasAnyRole(['ROLE_ADMIN', 'ROLE_ONC', 'ROLE_ONC_STAFF'])"><a ui-sref="administration.svaps"><i class="fa fa-caret-right" ng-if="vm.isActive('administration.svaps')"></i> S
Same question about ROLE_ONC_STAFF that I had in the API PR. If they are supposed to be able to do this then that's fine but I wanted to ask.

2021-02-04 11:38 UTC, kekey1 commented on src/app/pages/administration/svaps/svaps.component.js
> +            this.isEditting = true;
typo in the "isEditting" variable name

2021-02-04 13:13 UTC, andlar requested changes

2021-02-04 13:13 UTC, andlar commented on src/app/components/action-bar/action-bar.html
> +        <li ng-if="$ctrl.maxMessageCharacters" ng-repeat="message in $ctrl.errorMessages"><ai-ellipsis text="{{ message }}" max-length="{{ $ctrl.maxMessageCharacters }}"></ai-ellipsis></li>
I think we want these to use the `wordBoundaries` attribute too, as the general use for the ellipsis, when used on sentences, should break on word breaks

2021-02-04 13:13 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +            this.isEditting = false;
As well as the typo, setting things to (basically) null/undefined/falsy values in the constructor isn't really needed

2021-02-04 13:13 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +    fdescribe('the SVAP Administration page', () => {
```suggestion
    describe('the SVAP Administration page', () => {
```

All tests ought to be run when PRs are submitted

2021-02-04 13:13 UTC, andlar commented on src/app/services/network.service.js
> +    createSvap (svap) {
All of these need corresponding tests in the `network.service.spec.js` file

2021-02-04 16:20 UTC, andlar commented on src/app/components/action-bar/action-bar.component.js
> -                this.previousErrors = angular.copy(this.errorMessages);
Why are these getting deleted? I don't remember exactly why they're here, but they're used to populate the `needToShow` variable, so I don't think they should be removed

2021-02-04 16:20 UTC, andlar commented on src/app/pages/administration/administration.state.js
> +                    if (authService.hasAnyRole(['ROLE_ADMIN', 'ROLE_ONC', 'ROLE_ONC_STAFF'])) {
```suggestion
                    if (authService.hasAnyRole(['ROLE_ADMIN', 'ROLE_ONC'])) {
```

2021-02-04 16:20 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +                this.availableCriteria = angular.copy(changes.availableCriteria.currentValue);
This line isn't needed. The `.filter` function in the next line creates a new array, so making an angular copy isn't required

2021-02-04 16:20 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +        cancel () {
Can we alphabetize these methods? Or otherwise group them in some logical fashion?

2021-02-04 16:20 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +            if (Array.isArray(this.svap.criteria)) {
Is this object never not an array?

2021-02-04 16:20 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +                    xit('should cancel out of edit mode on success', () => {
Is there a reason this one (and any others in this file) are ignored?

2021-02-04 18:19 UTC, tmy1313 commented on src/app/pages/administration/svaps/svaps.component.js
> +            if (Array.isArray(this.svap.criteria)) {
When you are creating a new SVAP, it might not exist yet.

2021-02-04 18:23 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +            if (Array.isArray(this.svap.criteria)) {
Creating an SVAP is an action where you create an object that is that new SVAP, right? Why not, in the process of creating the blank SVAP, create it in the shape of a fully-realized one so we can dispense with extra checks that aren't related to different shapes of things coming from the API

2021-02-04 18:30 UTC, tmy1313 commented on src/app/components/action-bar/action-bar.component.js
> -                this.previousErrors = angular.copy(this.errorMessages);
Not sure what happened here.  I didn't mess with any of the internals of how the component works.  I'll add it back in.

2021-02-05 13:22 UTC, andlar reviewed
Also, can't finish a review until all merge conflicts are gone

2021-02-05 13:22 UTC, andlar commented on src/app/components/action-bar/action-bar.component.js
> +                this.previousErrors = angular.copy(this.errorMessages);
Why is this one changing?

2021-02-05 13:22 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +            if (Array.isArray(this.svap.criteria)) {
Why not create the criteria array when creating the new svap in the first place? Initialize it with an empty array and skip this check

2021-02-05 13:22 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.js
> +            if (!Array.isArray(this.svap.criteria)) {
This check could be removed as well

2021-02-05 13:22 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +                it('should call the svap delete endpoint', () => {
```suggestion
                });
                
                it('should call the svap delete endpoint', () => {
```

2021-02-05 13:22 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +                describe('when editing an svap', () => {
```suggestion
            describe('when saving', () => {
                describe('when editing an svap', () => {
```

2021-02-08 12:54 UTC, andlar submitted a review, later dismissed
Okay going forward based on functionality

2021-02-08 12:54 UTC, andlar commented on src/app/pages/administration/administration.state.js
> +    }, {
Why change these? I believe all of the other state definition files have this "smushed" `},{` style. I don't know if it's wrong, but making this change makes it inconsistent

2021-02-08 12:54 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +      svaps: [{
If SVAPs are going to be used in other places / tests, there are some `src/app/test/*.mock.js` files that extract the test data out to a single point of truth. I don't know if it's required to move these there, but maybe worthwhile

2021-02-08 12:54 UTC, andlar commented on src/app/pages/administration/svaps/svaps.component.spec.js
> +          xit('should cancel out of edit mode on success', () => {
I can't remember; is there a reason these are ignored? I think I'd be okay moving to the next step in the process, but I don't think we want to merge new features to staging with tests that never ran successfully

2021-02-08 16:08 UTC, kekey1 submitted a review, later dismissed

2021-02-15 22:31 UTC, andlar commented on src/app/navigation/navigation-top.html
> +              <li ng-if="vm.hasAnyRole(['ROLE_ADMIN', 'ROLE_ONC'])"><a ui-sref="administration.svaps"><i class="fa fa-caret-right" ng-if="vm.isActive('administration.svaps')"></i> SVAP Administration
Given that the title of the page, once it's loaded, is "SVAP Maintenance", shouldn't this navigation match?

2021-02-15 22:31 UTC, andlar commented on src/app/chpl.mock.js
> +        mock.svaps = [{
Can this be moved into the `src/app/test` directory with the other specific mock elements?

2021-02-16 13:38 UTC, tmy1313 commented on src/app/chpl.mock.js
> +        mock.svaps = [{
What is the thought process to know whick mocks belong in this file and which ones belong in a separate file.  Should all mocked data be part of this service?  Should there ever be any mocked data in a .spec.js?

2021-02-16 15:15 UTC, andlar commented on src/app/chpl.mock.js
> +        mock.svaps = [{
Whether the mock data is in a "general" file or not is based on whether that data is being used in multiple spec files. If it's in multiple spec files, or could be, it should be in one of the general files.

Once the decision has been made to move it to a general file, then it should go into the `src/app/test` directory, likely as a new file. It used to be in the `src/app/chpl.mock.js' file, but that file was getting too big, so I've been breaking pieces out of there as I update them

2021-02-16 15:18 UTC, andlar approved these changes

2021-02-16 18:32 UTC, kekey1 approved these changes

2021-02-16 19:40 UTC, merged