[#OCD-3607] feat!: Support display & edit of SVAP Notice
chpladmin/chpl-website pull request #855
Opened 2021-02-12 22:19 UTC by andlar

2021-02-15 18:07 UTC, kekey1 approved these changes, later dismissed

2021-02-16 11:47 UTC, kekey1 requested changes
I think we also need a file indicating the XSD has changed

2021-02-16 13:35 UTC, kekey1 approved these changes, later dismissed

2021-02-16 14:53 UTC, tmy1313 approved these changes, later dismissed

2021-02-24 14:48 UTC, palakpatel311 approved these changes

2021-02-24 17:16 UTC, ashwinimore approved these changes

2021-02-24 21:48 UTC, tmy1313 approved these changes

2021-02-25 00:51 UTC, kekey1 approved these changes

2021-02-25 14:46 UTC, merged