OCD-3612: Add AQA test for supporting v20 template upload
chpladmin/chpl-website pull request #859
Opened 2021-02-22 18:02 UTC by palakpatel311

[#OCD-3612]

2021-02-22 20:24 UTC, kekey1 requested changes

2021-02-22 20:24 UTC, kekey1 commented on e2e/components/surveillance/edit/surveillance-edit.po.js
> +  get removenonConformity () {
```suggestion
  get removeNonConformity () {
```

2021-02-22 20:24 UTC, kekey1 commented on e2e/components/upload/upload-listing/upload-listing.spec.js
> +  it('can upload v20 template', () => {
Does this also test the flexible upload component? If not, can we have tests for both?

2021-02-22 20:34 UTC, palakpatel311 commented on e2e/components/surveillance/edit/surveillance-edit.po.js
> +  get removenonConformity () {
we changed format of noncomformity to "nonConformity" so kept the same. But this was your suggestion originally so I could change this one, too. let me know

2021-02-22 20:35 UTC, palakpatel311 commented on e2e/components/upload/upload-listing/upload-listing.spec.js
> +  it('can upload v20 template', () => {
Flexible upload also test this which is added in upload-listing-beta-dp.js

2021-02-22 21:15 UTC, kekey1 commented on e2e/components/surveillance/edit/surveillance-edit.po.js
> +  get removenonConformity () {
Yeah, I think though to be properly camel-cased, each word needs to start with a capital letter.

2021-02-22 22:07 UTC, kekey1 approved these changes, later dismissed

2021-02-23 02:00 UTC, andlar approved these changes, later dismissed

2021-02-23 13:45 UTC, athomas-git submitted a review, later dismissed

2021-03-02 14:28 UTC, ashwinimore submitted a review, later dismissed

2021-03-02 14:48 UTC, andlar approved these changes

2021-03-02 15:20 UTC, athomas-git approved these changes

2021-03-02 15:52 UTC, ashwinimore approved these changes

2021-03-02 18:09 UTC, kekey1 approved these changes

2021-03-02 18:28 UTC, merged