OCD 3488: AQA tests for Download CHPL files
chpladmin/chpl-website pull request #867
Opened 2021-03-15 17:25 UTC by palakpatel311

2021-03-16 10:58 UTC, kekey1 requested changes

2021-03-16 10:58 UTC, kekey1 commented on e2e/pages/resources/download/download-dp.js
> +    dfSize: '3000',
I had a hard time knowing what some of these variables mean, although I think I've figured it out now that I've read through. I wonder if you could make them more consistently named? For example, definitionFileSize (dfSize to me could be definition file size or data file size), dataFileSize, definitionFileLineCount, dataFileLineCount, etc. For "days" maybe generationFrequencyInDays ?

2021-03-16 16:47 UTC, kekey1 approved these changes, later dismissed

2021-03-17 15:34 UTC, ashwinimore requested changes

2021-03-17 15:34 UTC, ashwinimore commented on e2e/pages/resources/download/download-dp.js
> +  },
this-2014 & 2011(below) ed. are missing definitionFileSize, due to which test run shows 'undefined' for definition file size check

2021-03-17 15:36 UTC, palakpatel311 commented on e2e/pages/resources/download/download-dp.js
> +  },
Updated

2021-03-17 15:40 UTC, ashwinimore approved these changes

2021-03-17 16:40 UTC, kekey1 approved these changes

2021-03-17 18:21 UTC, athomas-git approved these changes

2021-03-18 17:21 UTC, merged