OCD-3596 - API Key registration should require additional security measures
chpladmin/chpl-website pull request #876
Opened 2021-03-26 14:45 UTC by tmy1313

2021-03-26 15:27 UTC, andlar requested changes
I have a lot of comments. A big chunk of them are related to the migration to React, and the philosophy around that, but I want to call out that I think the functionality implemented here is awesome, and I'm really looking forward to moving along this path in the future

2021-03-26 15:27 UTC, andlar commented on package.json
> +    "test:react": "jest"
Can we move this to be in the section of scripts that has the other `test:*` scripts?

2021-03-26 15:27 UTC, andlar commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
I'm leery of `alpha` stuff in a prod system. Is this required?

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +import {getAngularService} from './';
I've been thinking about how we organize our imports. I have been leaning towards something like:

```
import React
import (things that come from React)
import (things that come from Material-UI)
blank line
import (things that come from our code)
```

My theory is that the first lines are the most "required" things, with "theming" stuff as secondary, and separating them all from our custom-written code with a blank line. I'm up for conversations about this, but wanted to put the idea out there

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +  const [confirmError, setConfirmError] = useState(false);
I'm wondering about conventions here too. I was starting with this philosophy:

```
set state(s)
getAngularService(s)
useStyles()
was there anything else?
```

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                  <ul className="MuiTypography-body1">
I think this should just be `body1`, though I'm not sure. I _think_ we shouldn't be putting classes with `Mui` in their names in our code directly

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                    <li>The confirmation token in the URL is not correct.</li>
Both of these `li` items can't exist at the same time, right?

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                    Your API key must be included in all API calls via either a header with the name &lsquo;API-Key&lsquo; or as a URL parameter named &lsquo;api_key&lsquo;.
Can we remove the special left/right quote marks? We don't have them anywhere else in the CHPL, and I'd like to keep that consistent

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                  <Typography variant="body1" paragraph={ true } data-testid="api-key-display">
A question of style. There are three `Typography` blocks here all with the same attributes. Can they / should they be combined? Can we put these three lines in one block, maybe with `<br />` tags? I honestly don't know, and am looking for the most idiomatic way of doing this kind of thing going forward

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +  //const $log = getAngularService('$log');
Probably don't need this

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +  const createRequest = (values) => {
I usually don't include the parentheses when the function has only one parameter. I'm not against having it, but if we choose to go that way we should make that part of our style guide, whether or not our linting tools can catch it

```suggestion
  const createRequest = values => {
```

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +            body: 'To confirm your email address, an email was sent to: ' + values.email + '  Please follow the instructions in the email to obtain your API key.',
Does the response have the email address? I usually try to use the response to fill out the responding messages, but if that data isn't there this is fine

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +  const classes = useStyles();
I feel like this should be up at the start of the function with the other "set up the function" things. I could see the argument for it being here, just before it's used, so am up for discussion

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +                       helperText={ formik.touched.nameOrganization && formik.errors.nameOrganization } />
I want to call this out as as example of what I think we should do for all of our input things, specifically with respect to the order of things, and one that I'd like to repeat:

1. Styles
2. id
3. name
4. label
5. value
6. on*
7. error*

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +import { toBeInvalid, toBeValid, toBeEnabled, toBeDisabled, toHaveValue } from '@testing-library/jest-dom';
I've been trying to alphabetize the imports where I can. I don't know if we can lint that, but I think it'd be helpful for consistency

```suggestion
import { toBeDisabled, toBeEnabled, toBeInvalid, toBeValid, toHaveValue } from '@testing-library/jest-dom';
```

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +  //it('should renders without crashing', () => {
Probably can be removed, or maybe `xit` (or whatever jest does)

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +
```suggestion
```

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +    it('should display a toaster indicating success when the response is success', async () => {
I just noticed the `async` in the `it` definition. Am curious about that; what's it for? I'm assuming it's required, but I'd like to know more about what's going on for my own edification

2021-03-26 15:27 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +
```suggestion
```

These tests are great. I'm super excited to fold this pattern into the rest of the stuff we work on. Good work!

2021-03-26 15:27 UTC, andlar commented on src/app/components/components.module.js
> +  .component('chplApiKeyConfirmBridge', reactToAngularComponent(ChplApiKeyConfirm))
I've been trying to alphabetize both the `.component` lines, and the `import` ones above. I don't know that it matters, but I feel it mimics what we have in our java `import` blocks in some way, and I hope it might help us recognize issues in the future

2021-03-26 15:27 UTC, andlar commented on src/app/services/network.service.js
> +    return this.apiPOST('/key/confirm', hash);
The `network.service` file is the _one file_ I think we have a lot of code in, that has nearly 100% coverage. Can you add tests to the relevant spec file for this service?

2021-03-26 15:27 UTC, andlar commented on yarn-error.log
> +Arguments:
This file shouldn't be committed to git. I'm assuming it was an accidental response to a `git add .`, but it shouldn't be here

2021-03-26 15:27 UTC, andlar commented on src/app/pages/resources/chpl-api/chpl-api.html
> -            <ai-api-key></ai-api-key>
Does the `aiApiKey` component still exist? Is it used somewhere else? If so, no issues, but if it's removed from use we should delete it from the project

2021-03-26 15:27 UTC, andlar commented on src/app/pages/registration/registration.state.js
> +  url: '/~/{hash}',
What's the `~` for? I've not seen that in any of our URLs before

2021-03-26 15:27 UTC, andlar commented on src/app/pages/registration/confirm-api-key.component.js
> +export const ConfirmApiKeyPage = {
Can we have a spec file for this component? I know it won't have much in it, but it fits our structure, and can `expect(the HTML to exist)`

2021-03-26 15:27 UTC, andlar commented on src/app/pages/registration/components/api-key.html
> -            <div class="text-danger" ng-if="vm.registerForm.userName.$touched && vm.registerForm.userName.$error.required">Name or Organization is required</div>
If these variables are removed from the `vm` object, and they're not used in the rest of the HTML, then they should probably be removed from whatever component/directive creates them, as well as whatever functions this deleted block of code references that are otherwise no longer used

2021-03-26 17:53 UTC, kekey1 reviewed
Just leaving a couple of comments based on using the feature. Nice job! I'll certainly approve after conflicts are resolved and Andrew's notes are addressed.

2021-03-26 17:53 UTC, kekey1 commented on src/app/components/api-key/api-key-confirm.jsx
> +            <CardHeader title="API Email Confirmation"/>
Could this read "API Key Email Confirmation" or maybe just "API Key Confirmation"?

2021-03-26 17:53 UTC, kekey1 commented on src/app/components/api-key/api-key-confirm.jsx
> +                    Your API key must be included in all API calls via either a header with the name &lsquo;API-Key&lsquo; or as a URL parameter named &lsquo;api_key&lsquo;.
This is good information for the user and I feel like it should also be on the API Key Registration page (https://chpl.ahrqdev.org/#/resources/chpl-api). We only mention the api_key URL parameter there in passing but it's stated much more clearly in this text.

2021-04-01 15:11 UTC, tmy1313 commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
I understand, but I'm not sure how we want to move forward.  I'm using it to display the Alert when there is a problem confirming the API Key request:
![image](https://user-images.githubusercontent.com/24817202/113314591-79dd3c80-92da-11eb-8209-ac6c3024e4d3.png)
I think this is a component we are going to want use in the future.  I see 3 paths forward:
1. Leave this alone for now - typically items from the "lab" are incorporated into the "core" after they have been determined to stable enough and that there is enough of need for the component.  By using this component, I feel that we are contributing to the "need" portion of the component.  https://material-ui.com/components/about-the-lab/
2. Redesign the component.  This would be fairly easy.  But as stated above - I think we are going to want the Alert component eventually.
3. Find a third-party Alert component that is supported/maintained.

Let me know how you want to proceed.

2021-04-01 15:17 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.jsx
> +                  <ul className="MuiTypography-body1">
I think so, too.  But when I include the `<ul>` in the `<Typography>` tag, I get the following warning when running the tests:
![image](https://user-images.githubusercontent.com/24817202/113315932-d0974600-92db-11eb-997e-0679e9a386b2.png)

I'm not sure what the correct structure should be here...  Any ideas?

2021-04-01 15:22 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.jsx
> +                    <li>The confirmation token in the URL is not correct.</li>
We don't know why the confirmation failed.  Not sure how much information we should return on why the confirmation failed - not sure if we could be creating a security issue by telling the user exactly why the confirmation failed.  Kind of like telling the user that their password is incorrect - instead you just get a generic message about invalid credentials.

If you want, we can change the response from the API to provide a reason and just display that failure reason as an error message.

Let me know how you want to proceed with this.

2021-04-01 15:37 UTC, tmy1313 commented on src/app/components/api-key/api-key-registration.jsx
> +            body: 'To confirm your email address, an email was sent to: ' + values.email + '  Please follow the instructions in the email to obtain your API key.',
This response is only failure/success.

2021-04-01 15:42 UTC, tmy1313 commented on src/app/components/api-key/api-key-registration.test.jsx
> +    it('should display a toaster indicating success when the response is success', async () => {
The `async` keyword makes the function run asynchronously and acts as an indicator that the function should expect the possibility of the `await` keyword.  
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

2021-04-01 15:45 UTC, tmy1313 commented on src/app/pages/resources/chpl-api/chpl-api.html
> -            <ai-api-key></ai-api-key>
There is a second piece of functionality in the Angular `aiApiKey` component.  It displays a list of api keys and allows an admin/onc to revoke the api key.  So, we only replaced a portion of the component's functionality.

2021-04-01 15:50 UTC, tmy1313 commented on yarn-error.log
> +Arguments:
Deleted this file and added it to `.gitignore` in case it reappears.

2021-04-01 16:18 UTC, tmy1313 commented on src/app/services/network.service.js
> +    return this.apiPOST('/key/confirm', hash);
Tests added.

2021-04-01 16:20 UTC, tmy1313 commented on src/app/pages/registration/registration.state.js
> +  url: '/~/{hash}',
I think this was an accidental deletion.  I reverted it back to the original value.

2021-04-05 14:35 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                    <li>The confirmation token in the URL is not correct.</li>
I'm fine leaving it generic, and think that's generally a good idea. My original comment was that it was impossible for both of these `li` items to be true at the same time, so we shouldn't have them static here

2021-04-05 14:35 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                    Your API key must be included in all API calls via either a header with the name &apos;API-Key&apos; or as a URL parameter named &apos;api_key&apos;.
Is there a reason this isn't just using the standard `'` character? I don't think we've used this HTML entity anywhere else in our codebase

2021-04-05 14:35 UTC, andlar commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
Could you get the AngularJS toaster service and use that? At least that way it's consistent with our other alert messages, and when we figure out how we're going to replace that toaster we can do them en masse.

I'm leery of item 1 as it's making a UX choice without going through our UX review process. Item 2 is basically using the toaster service temporarily, and we'll get to item 3 (maybe with the alpha code you're using now) but we'll make that decision when the team figures out how we want to handle these kinds of things

2021-04-05 14:35 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +import {getAngularService} from './';
Will resolve this one in a bit, pending a style guide conversation

2021-04-05 14:35 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +  const [confirmError, setConfirmError] = useState(false);
Are these kinds of things in any styleguide out there?

2021-04-05 14:35 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                  <ul className="MuiTypography-body1">
It looks like you can set a component on the Typography tag of "div" to allow it to nest. The default for Typography is "p", which doesn't allow block elements inside of it, according to the HTML spec

Reference: https://stackoverflow.com/a/53494821/16593

2021-04-05 18:17 UTC, tmy1313 commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
I still the think the card needs to have some sort of error message displayed in it.  Not sure it would make sense to display possible reasons for failure without indicating in the same "area" that an error occurred.  Is there any relationship between this an displaying errors in the action bar??  Not sure...

Maybe we should throw this over the fence for Matt to evaluate?

2021-04-05 18:38 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.jsx
> +                  <ul className="MuiTypography-body1">
Let me know if this is not what you meant...

2021-04-05 19:01 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.jsx
> +  const [confirmError, setConfirmError] = useState(false);
Not that I have seen.  I think that by adding these types of rules that cannot necessarily be enforced via eslint, we will have rules that we can only enforce during code reviews creating a "secret convention."  I am not a huge fan of expanding the "standard" conventions unless we really have to - I am of the opinion that AirBnB has spent more time and money developing this standard than us, and that it is pretty complete.  Also, I'm not sure that I am comfortable saying anything should be in any sort of order based on the limited React coding I have done.

2021-04-06 12:48 UTC, andlar commented on src/app/pages/registration/components/api-key.directive.js
> -        $analytics.eventTrack('Register For API Key', { category: 'CHPL API', label: label });
I don't see this analytics event getting tracked in the new component. I don't think we have a react version of this service yet, but we should be able to get the angular version and use that after a successful registration

2021-04-08 14:46 UTC, tmy1313 commented on src/app/pages/registration/components/api-key.directive.js
> -        $analytics.eventTrack('Register For API Key', { category: 'CHPL API', label: label });
Important to only use the domain - ...@domain.com

2021-04-08 17:45 UTC, andlar submitted a review, later dismissed

2021-04-08 18:19 UTC, kekey1 approved these changes, later dismissed

2021-04-12 15:52 UTC, andlar commented on .eslintrc
> +    "max-len": ["off"],
This rule should be in the set of rules that were deleted. Here it only applies to the `*.jsx` and `*.spec.js` files, which is not what we want

2021-04-12 15:52 UTC, andlar commented on lint-summary.js
> +        const occurrence = `${current.filePath}:${line}:${column}`;
I see we're building up a set of messages, but later the only thing we do with it is display the count. Feel like we should either just count them, or display the messages, but this half-and-half seems odd

2021-04-12 15:52 UTC, andlar commented on lint-summary.js
> +};
Missing a new-line

2021-04-12 15:52 UTC, andlar commented on package.json
> +    "prop-types": "^15.7.2",
I think this should be in `devDependencies`. We're not publishing this package as something others can consume as a library, and putting it in the `dependencies` just makes our bundled PROD slightly bigger, for no benefit

2021-04-12 15:52 UTC, andlar commented on src/app/components/api-key/api-key-confirm.jsx
> +                      {' '}
Why did this line-break happen? I'm curious about what rule was broken here, when the output is a single line of text

2021-04-12 15:52 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +  let formik = {};
Wondering why this couldn't be a `const`. Again, curious about the rule, and why it's better to do it this way

2021-04-12 15:52 UTC, andlar commented on .babelrc
> +        "@babel/preset-react",
Is this necessary? In the webpack.config.js file we're already using the `@babel/preset-react` on all of the *.js and *.jsx files

2021-04-12 15:52 UTC, andlar commented on src/app/components/api-key/api-key-confirm.test.jsx
> +  render, cleanup, screen, waitFor,
Do these need to be on a new line? Most of the other multi-imports are on a single line

2021-04-12 15:52 UTC, andlar commented on src/app/components/api-key/api-key-registration.test.jsx
> +    it('should not have any invlid fields', async () => {
```suggestion
    it('should not have any invalid fields', async () => {
```

2021-04-12 15:52 UTC, andlar commented on src/app/services/network.service.js
> +  /// /////////////////////////////////////////////////////////////////
```suggestion
  /*
   * Helper functions
   */
```

2021-04-22 14:02 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.jsx
> +                      {' '}
I'm not sure what this was....  I reverted the code, linted and got 0 errors wrt to this.  Then ran  --fix and it made not difference.  I have reverted the change and removed the `{' '}`.

2021-04-22 14:10 UTC, tmy1313 commented on src/app/components/api-key/api-key-registration.jsx
> +  let formik = {};
I think...
* we need to define the `formik` variable near the top of the function, so that it can be referenced in other functions
* toward the bottom of the function we 'redefine' the `formik` variable using `formik = useFormik...` 
Isn't the `formik = useFormik...` redefining the variable, therefore it cannot be a `const`?

2021-04-22 14:44 UTC, tmy1313 commented on src/app/components/api-key/api-key-confirm.test.jsx
> +  render, cleanup, screen, waitFor,
Not sure about this error.   This is the result when I put it all on a single line...
![image](https://user-images.githubusercontent.com/24817202/115734364-a6272e80-a357-11eb-9dc8-988ff3edf364.png)

2021-04-22 16:12 UTC, andlar reviewed
There's a theme.js file that's committed here, as an empty file. Should there be something in it?

2021-04-22 16:12 UTC, andlar commented on .babelrc
> +        }],
I think this extra comma isn't needed, and as this isn't a *.js file, even though it looks like it, I don't think it should be here

2021-04-22 16:12 UTC, andlar commented on .eslintrc
> -    "no-console": ["off"],
Why was this rule removed? Why was the selector changed? The way this is now this entire section of overrides doesn't do anything

2021-04-22 16:12 UTC, andlar commented on src/app/components/api-key/api-key-registration.jsx
> +              error={formik.touched.nameOrganization && Boolean(formik.errors.nameOrganization)}
Is the `Boolean` required? If the error= is just looking for falsy/truthy then we shouldn't need to cast it

2021-04-26 15:06 UTC, andlar reviewed
Why is there a `theme/theme.js` file getting committed in this PR with no content?

2021-04-26 15:06 UTC, andlar commented on .eslintrc
> -    "files": ["*.jsx", "*.spec.js"],
I think we're still trying to encourage the use of the angular $log service in our AngularJS files, which is why I don't think the removal of the `spec.` selector is correct. We're eventually going to ignore this rule entirely, unless React has a similar log service, on our trip towards using console.log, but I'd rather not allow it in our legacy AngularJS stuff yet

2021-04-27 14:34 UTC, andlar approved these changes

2021-04-27 14:37 UTC, kekey1 approved these changes

2021-04-27 14:40 UTC, merged