OCD 3502: AQA test for Developer/Product/Version Edit, Merge, Split - ALL+
chpladmin/chpl-website pull request #883
Opened 2021-04-07 16:01 UTC by palakpatel311

2021-04-08 15:40 UTC, andlar requested changes

2021-04-08 15:40 UTC, andlar commented on e2e/components/contact/contact.po.js
> +  editWebsite: '#developer-website',
These elements are not part of a Contact. A Contact is just the four elements elements above: full/friendly names, number, email. Website can be part of many things, and the Address fields should be in the an Address `po`

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +let hooks, page,toast;
```suggestion
let hooks, page, toast;
```

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +          page.splitDeveloper.click();
The spacing between blocks here is inconsistent
```suggestion
        });
      });

      describe('when looking at developer with more than one product', () => {
        it('should have split developer button', () => {
          expect(page.splitDeveloper.isDisplayed()).toBe(true);
        });

        it('should not have merge developer button', () => {
          expect(page.mergeDeveloper.isDisplayed()).toBe(false);
        });

        it('should allow split to happen', () => {
          page.splitDeveloper.click();
```

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +            country: 'country' + timestamp,
These fields are not part of a Point of Contact, but are instead either part of a Developer (website) or part a Developer's Address

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +        it('should show correct error message', () => {
This test could be in the `*.readonly.spec.js` file, as it's not actually saving anything. It doesn't _need_ to move, but it might make it easier to test if it's one of the readonly ones

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/products.readonly.spec.js
> +      let developer = 'Medical Information Technology, Inc. (MEDITECH)';
Why change these to be `let` when the values aren't changing?

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/products.spec.js
> +      describe('when looking at "PrimeSuite" product', () => {
This entire block could be a readonly test

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/versions.spec.js
> +    describe('when on the "Greenway Health, LLC" Developer page, on the "Greenway Prime Suite" Product', () => {
Also could be readonly

2021-04-08 15:40 UTC, andlar commented on e2e/pages/organizations/developers/versions.spec.js
> +      if (toast.toastContainer.isDisplayed()) {
If this "clear toast" hook is added to each of the afterEach blocks in nested blocks, why not move it up a level to a more global one, so it only needs to be in one place?

2021-04-08 20:04 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.spec.js
> +        it('should show correct error message', () => {
I kept this in non read-only cause if it fails ever, split would be successful which changes DB data.

2021-04-08 20:43 UTC, palakpatel311 commented on e2e/pages/organizations/developers/products.spec.js
> +      describe('when looking at "PrimeSuite" product', () => {
Same comment as before

2021-04-08 20:43 UTC, palakpatel311 commented on e2e/pages/organizations/developers/versions.spec.js
> +    describe('when on the "Greenway Health, LLC" Developer page, on the "Greenway Prime Suite" Product', () => {
Same comment as before

2021-04-09 16:43 UTC, ashwinimore approved these changes, later dismissed
needs a review/fix on failing test for developer split involving multiple ACBs, approved otherwise

2021-04-14 16:02 UTC, andlar commented on e2e/pages/organizations/developers/developers.readonly.spec.js
> +        page.certificationStatusFilter(0);
I see how this method works, but it would be helpful if it were a method with a useful name, maybe something like: 
```suggestion
        page.allAllCertificationStatuses();
```

Then the page could use the "set by index" method in the page object to do that, and if/when the implementation of how that filter works is changed, this test won't need to change, just the page's implementation of that action

2021-04-14 16:07 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +  let poc = {
Using full names is helpful for readability:
```suggestion
  let developerContact = {
```

2021-04-14 16:07 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +  let ad = {
Same: 
```suggestion
  let developerAddress = {
```

2021-04-14 16:07 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +      describe('when looking at developer with more than one product', () => {
We usually put blank lines between blocks
```suggestion
      });

      describe('when looking at developer with more than one product', () => {
```

2021-04-14 16:07 UTC, andlar commented on e2e/pages/organizations/developers/products.readonly.spec.js
> +        let productName = 'MEDITECH Expanse 2.2 Oncology';
Is the productName changing? If not, it should be a const. I don't see an update to code that suggests it does change

2021-04-14 16:07 UTC, andlar commented on e2e/pages/organizations/developers/versions.readonly.spec.js
> +        let name = 'Greenway Intergy Meaningful Use Edition';
Does this `name` change?

2021-04-14 19:33 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +        let developer = 'athenahealth, Inc.';
Does this variable change? If it doesn't, it should be a const

2021-04-14 19:33 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +        let developer = 'Altos Solutions, Inc';
Another one

2021-04-15 13:33 UTC, andlar commented on e2e/pages/organizations/developers/versions.spec.js
> +        let version = 'Version 2015';
Does this `let` variable change? If it doesn't, it should be a const too

2021-04-15 13:33 UTC, andlar commented on e2e/pages/organizations/developers/products.spec.js
> +        let newProduct = 'New product' + timestamp;
What about these? Do they change?

2021-04-15 15:45 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +  let developerContact = {
Do any of these change?

2021-04-16 14:55 UTC, andlar commented on e2e/pages/organizations/developers/developers.po.js
> +    let btn = product.$$('li').filter(item => item.getText() === 'Product')[0];
Is this a `let` for a reason? Does this change?

2021-04-16 14:55 UTC, andlar commented on e2e/pages/organizations/developers/developers.spec.js
> +  let timestamp = (new Date()).getTime();
Does this `let` change?

2021-04-16 15:07 UTC, palakpatel311 commented on e2e/pages/organizations/developers/developers.po.js
> +    let btn = product.$$('li').filter(item => item.getText() === 'Product')[0];
This was there before. I did not change line # 164

2021-04-16 16:21 UTC, andlar approved these changes, later dismissed

2021-04-16 16:26 UTC, ashwinimore submitted a review, later dismissed

2021-04-19 19:24 UTC, athomas-git submitted a review, later dismissed

2021-04-21 18:45 UTC, andlar commented on e2e/pages/organizations/developers/developers.po.js
> +    let btn = product.$$('li').filter(item => item.getText() === 'Product')[0];
Maybe you didn't add this line, but instead the one in the `mergeProduct` method? Git shows this PR as having changed this line
![image](https://user-images.githubusercontent.com/909012/115604602-8fc59800-a2af-11eb-9966-57fe78b786f1.png)

2021-04-21 19:14 UTC, andlar approved these changes

2021-04-21 20:54 UTC, ashwinimore approved these changes

2021-04-22 11:15 UTC, athomas-git approved these changes

2021-04-23 01:57 UTC, merged