OCD- 3649 : Update AQA test to have process listing instead of inspect list…
chpladmin/chpl-website pull request #885
Opened 2021-04-13 21:15 UTC by palakpatel311

…ing button

[#OCD-3649]

2021-04-13 21:58 UTC, andlar commented on e2e/pages/administration/confirm/confirm.spec.js
> +      assert.equal(toast.toastTitle.getText(), 'Success');
We're switching to `expect`, right?
```suggestion
      expect(toast.toastTitle.getText()).toBe('Success');
```

2021-04-13 21:58 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    $('//input[@id="reject-pending-listing-' + chplId + '"]').scrollAndClick();
If we have an ID, can we simplify the locator?
```suggestion
    $('#reject-pending-listing-' + chplId).scrollAndClick();
```

2021-04-13 22:09 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    $('//input[@id="reject-pending-listing-' + chplId + '"]').scrollAndClick();
Could we do the same simplification with the other ones too?
```suggestion
    $('#reject-pending-listing-' + chplId).scrollAndClick();
```

2021-04-13 22:37 UTC, andlar commented on e2e/pages/administration/confirm/confirm.po.js
> +    $('//button[@id="process-pending-listing-' + inspectListingId + '"]').scrollAndClick();
Can this be converted too?

2021-04-14 00:18 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.po.js
> +    $('//button[@id="process-pending-listing-' + inspectListingId + '"]').scrollAndClick();
This one is not working with only #Id.

2021-04-14 12:52 UTC, palakpatel311 commented on e2e/pages/administration/confirm/confirm.po.js
> +    $('//button[@id="process-pending-listing-' + inspectListingId + '"]').scrollAndClick();
Actually I had to revert other locators from id to xpath as it was giving error of invalid or illegal selectors.

2021-04-14 13:53 UTC, kekey1 requested changes
No functional requests from me, but some small spacing/capitalization style things

2021-04-14 13:53 UTC, kekey1 commented on e2e/pages/administration/confirm/confirm.spec.js
> +let confirmPage, hooks, loginComponent, toast,uploadPage;
```suggestion
let confirmPage, hooks, loginComponent, toast, uploadPage;
```

2021-04-14 13:53 UTC, kekey1 commented on e2e/pages/administration/confirm/confirm.spec.js
> +      confirmPage.rejectListingcheckbox(rejectListingId1);
```suggestion
      confirmPage.rejectListingCheckbox(rejectListingId1);
```

2021-04-14 13:53 UTC, kekey1 commented on e2e/pages/administration/confirm/confirm.spec.js
> +      expect(confirmPage.findListingtoReject(rejectListingId1).isDisplayed()).toBe(false);
```suggestion
      expect(confirmPage.findListingToReject(rejectListingId1).isDisplayed()).toBe(false);
```

2021-04-14 13:53 UTC, kekey1 commented on e2e/workflowTest/upload-confirm-listing-test/bypass-warnings.spec.js
> +    assert.equal(confirmPage.toastContainerTitle.getText(),'Please stand by');
```suggestion
    assert.equal(confirmPage.toastContainerTitle.getText(), 'Please stand by');
```

2021-04-14 13:53 UTC, kekey1 commented on e2e/workflowTest/upload-confirm-listing-test/bypass-warnings.spec.js
> +    assert.equal(confirmPage.toastContainerTitle.getText(),'Please stand by');
```suggestion
    assert.equal(confirmPage.toastContainerTitle.getText(), 'Please stand by');
```

2021-04-14 14:14 UTC, kekey1 approved these changes, later dismissed

2021-04-14 14:15 UTC, andlar commented on e2e/workflowTest/upload-confirm-listing-test/bypass-warnings.spec.js
>      assert.equal(confirmPage.toastContainerTitle.getText(),'Update processing');
```suggestion
    assert.equal(confirmPage.toastContainerTitle.getText(), 'Update processing');
```

Similar spacing stuff

2021-04-14 14:15 UTC, andlar commented on e2e/workflowTest/upload-confirm-listing-test/bypass-warnings.spec.js
>      assert.equal(confirmPage.toastContainerTitle.getText(),'Update processing');
```suggestion
    assert.equal(confirmPage.toastContainerTitle.getText(), 'Update processing');
```

2021-04-14 14:20 UTC, athomas-git submitted a review, later dismissed

2021-04-14 15:58 UTC, andlar submitted a review, later dismissed

2021-04-21 18:39 UTC, andlar reviewed
Is the `screenshots/.gitkeep` file needed, or will the tests automatically create that directory during the build?

2021-04-21 18:39 UTC, andlar commented on e2e/workflowTest/upload-confirm-listing-test/bypass-warnings.spec.js
> +    assert.equal(confirmPage.toastContainerTitle.getText(), 'Success');
```suggestion
    expect(confirmPage.toastContainerTitle.getText()).toBe('Success');
```

2021-04-22 12:49 UTC, andlar commented on wdio.conf.js
> +      var location = `${__dirname}/test_reports/e2e/screenshot/assertionError_` + message + '.png';
This line uses both interpolation and concatenation. Should do only one
```suggestion
      var location = `${__dirname}/test_reports/e2e/screenshot/assertionError_${message}.png`;
```

2021-04-22 12:49 UTC, andlar commented on wdio.conf.js
> +        }
Why are there three if/else sections, but only one of them has any actions? This should be a single

```
if (something is true) {
   do the unlinkSync action
}
```

2021-04-23 12:06 UTC, andlar commented on wdio.conf.js
> +          // pass these files- this will be download data, definition files and screenshot, report folder
This block doesn't do anything, so this block shouldn't exist

2021-04-23 13:10 UTC, palakpatel311 commented on wdio.conf.js
> +          // pass these files- this will be download data, definition files and screenshot, report folder
I wanted to have it to remember what all is there in this directory as this actually on bamboo.

2021-04-23 13:29 UTC, tmy1313 commented on wdio.conf.js
> +          // pass these files- this will be download data, definition files and screenshot, report folder
Basically, since this is a config file we control the use/calls/params of the `rmdir` function.  We should never be calling the function with a dir that we do not want deleted.  This is basically creating a 'whitelist' of dirs that cannot be deleted, but this is not the correct construct for whitelisting.

2021-04-23 17:11 UTC, andlar reviewed
![image](https://user-images.githubusercontent.com/909012/115906301-561e9980-a435-11eb-8451-955909dbcad2.png)
I don't think this file should be here. We specifically `.gitignore` the `/test_reports` directory at the root level, so forcing a file nested inside that ignored directory to exist seems wrong

2021-04-23 17:11 UTC, andlar commented on wdio.conf.js
> +    rmdir(downloadDir);
I'm confused by these lines. Are these trying to remove the directories called out in the method? If so, why was the downloadDir created in the lines just above this function? Also, why not just call rmdir(downloadDir) to wipe out both of the screenshot and junitreport directories at the same time? If they're not trying to remove the directories, then the name of the function doesn't make sense

Is the whole point here to remove artifacts created by our tests? But not all the files in the test_reports/e2e directory? If that's the case, then why not put all of the things we want to remove into a single directory (or a few of them) under the test_reports/e2e directory and just remove those?

Maybe the use of the variable "downloadDir" is the problem? I mean, this directory (test_reports/e2e) by directory name doesn't have anything to do with download files, and has a bunch of files that aren't related to download files, so maybe making it the download directory isn't the best way to do it

Do we need a directory structure something like
```
+ test_reports/e2e - for general output files
+----/screenshot - for screenshots
+----/allure-results - for allure reporting
+----/junitreport - for junit reporting
+----/downloads - for temporary storage of downloadable files
```

2021-04-23 17:24 UTC, palakpatel311 commented on wdio.conf.js
> +    rmdir(downloadDir);
Yes so all downloads by our tests are downloaded by test_reports/e2e/.
I would like to remove those. hence, rmdir(downloadDir);
e2e/screenshot/ has screenshots from all runs so bamboo artifacts all of the previous runs screenshots as well. so i am removing previous screenshot at the start of run hence rmdir(downloadDir + 'screenshot');. This is needed as i need to remove files from this folder.
Same with junit reports, i need to remove previous reports before the start of run.

I can certainly add +----/downloads - for temporary storage of downloadable files for download files but it would just change rmdir(downloadDir + downloads);

2021-04-26 14:47 UTC, andlar commented on wdio.conf.js
> +    rmdir(downloadDir);
The variable name is `downloadDir`, but it looks like that directory has things that are not downloadable files. Maybe the `test_reports/e2e` directory needs to be referenced by something like `outputDirectory` and the `downloadDir` variable could be created as `const downloadDir = outputDirectory + '/downloads';` or something similar

A separate option could be to use the `yarn e2e:clean` command, which might need to be updated, but was originally written to remove all of the generated output files before running tests. That's probably closer to the idiomatic way of building and cleaning output files

2021-04-27 14:51 UTC, andlar approved these changes

2021-04-27 14:54 UTC, andlar approved these changes

2021-04-27 14:54 UTC, kekey1 approved these changes

2021-04-27 15:07 UTC, athomas-git approved these changes

2021-04-27 15:13 UTC, tmy1313 approved these changes

2021-04-27 15:18 UTC, merged