OCD-3505: Add AQA tests for ONC-ACB and ONC-ATL management
chpladmin/chpl-website pull request #891
Opened 2021-05-03 15:29 UTC by ashwinimore

2021-05-03 16:49 UTC, palakpatel311 reviewed
Great work on first time doing these UI Tests in this frame work. :)

I have reviewed code related to ACBs edit and some of the comments applies to ATLs edit as well. So not repeating my self there.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.po.js
> +  acbGeneralInformationPanel: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[1]/div[2]',
Can we try avoiding using absolute xpaths?
for example: this one has Id as chpl-organization-ONC-ACB-3, Looks like dynamic but it has id so we should work with that.

Same comments on others.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.po.js
> +    return $('//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[1]/div/div/div[' + acb + ']/button');
I am not 100% sure what this is doing but if this is getting list of ACBs then we have unique class name as '.organizations-side-nav' which can be used here

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +	for (i=1; i<=6; i++) {
This should have first assertion to check length of actual acbs before comparing them.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +      page.acbWebsite.setValue(websiteUrl);
setValue() command does clear value first and then set it so line #63 is not needed.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +      page.acbEditButton.click();
We shouldn't have any cleaning steps in test after assertions. These steps should be moved to after() function which in this case may need rearranging tests.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +    it('should require ACB Name, website and address on edit', () => {
We are checking here error messages displayed on empty fields on required field so this test could be rephrased something like 'should show correct error message when required fields are empty'

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +      page.saveOrganizationButton.click();
This tests is saving it so it should be in non readonly

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.po.js
> +  acbCreatetButton: '//*[contains(text(),"Create New ONC-ACB")]',
Typo. Extra t between create and button

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-atls/atls.po.js
> +  atlCreatetButton: '//*[contains(text(),"Create New ONC-ATL")]',
Same typo

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-atls/atls.po.js
> +  ulButton: '//*[contains(text(),"UL LLC")]',
I see same button locator for cchitButton and drummondButton. This can be generalize by passing acb to a method.

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +      page.impersonateUser.click();
I see we dont have aqa atl set up right now. I would like to see if we can create one rather than impersonating atl user. Leaving it to @andlar

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +    it('should allow user to unretire and retire existing ATL', () => {
Can we separate these as in ACBs?
This test should be in non readonly

2021-05-03 16:49 UTC, palakpatel311 commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +      page.saveOrganizationButton.click();
This test should be in non readonly

2021-05-03 18:43 UTC, ashwinimore commented on e2e/pages/organizations/onc-acbs/acbs.po.js
> +  acbGeneralInformationPanel: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[1]/div[2]',
I _did_ think about this and thought of parametrizing, then thought it's ok just for this one as I did not see we'd want to change test data on this one as we would in other cases (also thought if/when we do move to react on this one, request better locators then) and that we don't really use acb ids (vs. name & code). I'll update it so it uses acb id   
As for other xpaths, the classname wasn't unique on those so I went ahead and used xpath, i'll look for other possibilities

2021-05-03 18:59 UTC, ashwinimore commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +    it('should allow user to unretire and retire existing ATL', () => {
so....i wrote this one also exactly similar to ATL one (unretire then retire), as discussed with the team last week and put it in readonly but there's slight difference with how ATL save is processed vs. ACBs (e.g. toaster/no toaster). This test didn't work for ACB same way it did here. I wanted to test this out on AQA plan- to see which one does better and then make an update but couldn't do that just yet. I read that specs within a describe block _should_ run in sequence but wanted to test it out first.. more on this after findings (thinking of using feature review for discussion)

2021-05-03 19:40 UTC, ashwinimore commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +      page.saveOrganizationButton.click();
I moved it here because i was changing the ATL name (same for ACB) back to original name and although address is changed, it doesn't have impact on anything else. I don't feel strongly about keeping it here, I originally had it in non readonly and moved it after the discussion last week. If no one else has different opinion, I'll move it to non readonly

2021-05-03 20:00 UTC, ashwinimore commented on e2e/pages/organizations/onc-atls/atls.readonly.spec.js
> +      page.impersonateUser.click();
A while ago, we had a brief discussion during team meeting on adding user accounts for aqa for the ones that we don't have it already and I recall the consensus was that we could use impersonation for those. I added this based on that and would like to keep it until we have the accounts added(if we decide to do so). I like that it covers impersonation test as well

2021-05-04 18:53 UTC, ashwinimore commented on e2e/pages/organizations/onc-atls/atls.po.js
> +  ulButton: '//*[contains(text(),"UL LLC")]',
already implemented using atlNameButton (atl) method below. This was missed in cleanup(leftover from initial write up before parameterizing), will be removed in next commit

2021-05-06 13:11 UTC, andlar requested changes

2021-05-06 13:11 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    for (i = 1; i <= 6; i += 1) {
What this test will miss is if there is an ACB added to the system that shows up in this list after UL LLC. The loop only goes to six, but if there are seven ACBs we won't notice that

2021-05-06 13:11 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.spec.js
> +    it('should allow user to unretire and retire existing ACB', () => {
I thought we were going to put this test in the `readonly` file?

2021-05-06 13:11 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/atls.spec.js
> +  describe('when logged in as ONC', () => {
```suggestion
  });
  
  describe('when logged in as ONC', () => {
```

I think we try to separate `describe` and `it` blocks with blank lines, though I haven't found an eslint rule that enforces that

2021-05-06 13:11 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  newOrganizationGeneralInfo: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[1]/div[2]',
```suggestion
  newOrganizationGeneralInfo: '//chpl-onc-organizations/div[2]/div[2]/div[1]/div[2]',
```

You can probably start from the `chpl-onc-organizations` html element, as on these pages there should only ever be one of them, and anything to cut down on the number of nested elements in an xpath is good with me

Can do something similar with the next two lines, starting with `chpl-address` and `chpl-users` respectively

2021-05-06 13:11 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +export default OrganizationPage;
The filename is plural, the class is singular. I don't know if this page toggles between singular and plural, but if the PO data is only one organization, then I'd suggest going with singular in both places

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +let address; let hooks; let login; let
These can be combined as let address,hooks,......

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +      expect(page.errorMessage.getText()).toBe('Field is required');
More appropriate is to check required fields when they click on save.

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +      expect(page.organizationEditButton.isDisplayed()).toBe(false);
expect(page.organizationEditButton.isDisplayed()**).toBeFalse;**

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  impersonateUser(userId) {
This doesnt belong to organizations page. It should be under user management po.

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  newOrganizationGeneralInfo: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[1]/div[2]',
only $('chpl-onc-organization') as locator would work.

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  addressLine1OnEdit: '//*[@id="chpl-organization-edit"]/div/chpl-address/span/span/div[1]/div[1]/div',
This locator looks like being used for error message for address and I do see separate error message locator for these messages.

2021-05-06 15:33 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  manageUsersPanelBody: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[2]/div[2]/chpl-users/span/div[2]',
Trying to avoid absolute xpath as much as we can. $('chpl-users') locator would work here.

2021-05-06 16:45 UTC, ashwinimore commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +let address; let hooks; let login; let
that's how I had it before doing the lint check, this change was a suggested fix to meet eslint rule. If we have the rule active, then I understand this is expected per practice. If we want to use 'combined' way then I think the rule should be relaxed. I think we should discuss this as a team to have some clarity (I know I need it)

2021-05-07 12:43 UTC, ashwinimore commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  manageUsersPanelBody: '//*[@id="main-content"]/div/div/ui-view/chpl-onc-organizations/div[2]/div[2]/div[2]/div[2]/chpl-users/span/div[2]',
addressed all comments in latest commit

2021-05-07 12:44 UTC, ashwinimore commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +export default OrganizationPage;
updated in latest commit

2021-05-07 12:56 UTC, andlar approved these changes, later dismissed
I have some suggestions, but none of them are required. I'm okay with this going forward as is

2021-05-07 12:56 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +  const timestamp = (new Date()).getTime();
No need to change this, but I discovered this recently, and thought it looked much better to do the same thing:

```suggestion
  const timestamp = Date.now();
```

2021-05-07 12:56 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +      expect(page.errorMessage.getText()).toBe('Field is required');
That might work, but there are some places where clicking the button is impossible if the form is invalid, which means that trying to click the button will fail, but trying to click it is required before the errors appear. Adding that interaction makes the test harder to implement; it could be done, but I'm not sure it's worth the effort

2021-05-07 12:56 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/organization.po.js
> +    return $(elements.organizationList).length;
You already define the `organizationList` above, so here it could leverage that definition in such a way that if the locator for the organization list changes, this count wouldn't have to

I think something like this should work:

```suggestion
    return this.organizationList.length;
```

2021-05-07 12:56 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/organization.po.js
> +    return $(`//*[@id="chpl-organization-ONC-${organizationType}-${organizationId}"]/ui-view/div/div`);
I find locators that aren't xpath easier to understand. I don't think it's required to change it, but something like this should work too, and I think is easier to read:

```suggestion
    return $(`#chpl-organization-ONC-${organizationType}-${organizationId}/ui-view/div/div`);
```

2021-05-07 12:56 UTC, andlar commented on e2e/pages/users/user.po.js
> +    return $(`//*[@id="user-component-impersonate-${userId}"]`);
Similar thought here. Also not required:

```suggestion
    return $(`#user-component-impersonate-${userId}`);
```

2021-05-07 14:23 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs/acbs.readonly.spec.js
> +	for (i=1; i<=6; i++) {
This is not addressed. We should check acbCount and expectedACBs length, if its same then only enter for loop

2021-05-07 14:25 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/organizations.po.js
> +  impersonateUser(userId) {
This seems to be missed.

2021-05-07 14:30 UTC, palakpatel311 commented
There was one comment seems to be missed. I don't want to hold up this PR for that. I can wait for that change to review in final code review.

2021-05-07 14:30 UTC, palakpatel311 submitted a review, later dismissed

2021-05-11 20:57 UTC, palakpatel311 approved these changes, later dismissed

2021-05-12 14:23 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    for (i = 1; i <= acbCount; i += 1) {
I think I figured out what is bothering me about this. What would happen if `UL LLC` was deleted? The `acbCount` variable would be 6, so the loop would check the array of expectedAcbs but for the values of `i` from 1 to 5, but that would not look for the expected `UL LLC`

I know that's an unusual situation to get into, but is that also what we're trying to do with our AQA stuff? Find and test edge cases that we wouldn't normally see?

2021-05-12 14:23 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +  describe('when logged in as an ACB', () => {
If we're logging in as a specific ACB, I think it would make sense to call out the ACB we log in as during the describe block. Probably would suggest we do the same thing for the `it` blocks on lines 52, 60, and 66. That way the tests would read something like

```
when logged in as UL
  it should display registered users under UL
  it should not present the option to edit ACB details for drummond
  it should not display registered users under drummond
```

2021-05-12 15:05 UTC, palakpatel311 commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    for (i = 1; i <= acbCount; i += 1) {
Now noticing there is 'ONC-ACBs' in the expected ACBs??

2021-05-12 17:38 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    for (i = 1; i <= expectedAcbs.length; i += 1) {
This now checks to see if all of the expected ACBs are found, but it won't give an error if there are any new ACBs that have been added

2021-05-13 11:34 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    const sortedAcbList = currentAcbList.sort();
The Javascript array sort method sorts the items in the array in place, modifying the original array, so this comparison will _always_ succeed

2021-05-14 10:30 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    const expectedList = actualList.sort();
The change didn't actually change anything. Calling `actualList.sort()` sorts the actual list. Setting the expected list to the sorted actual list will always mean that the two lists are equal. I can see two different ways of doing this. Pseudocode:

1)

```
// using an array to walk through the actual list, and string comparison for ordering check
actualList = get list from PO
for (i = 2; i < acbCount; i++) {
expect(actualList[i - 1]) to be less than actualList[i])
}
```

2)
```
// get two lists
actualList = get list from po
expectedList = page.organizationList.sort()
expect(actualList).toEqual(expectedList) // note, using toBe probably won't work
```

2021-05-14 17:14 UTC, ashwinimore commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    const expectedList = actualList.sort();
I thought i was doing option 2 except that I didn't realize that the array was modified at sort (thought that the value of actualList was not altered). I like your first option better and going to go with that. Thank you!

2021-05-17 11:27 UTC, andlar commented on e2e/pages/organizations/onc-acbs-atls/acbs.readonly.spec.js
> +    for (i = 1; i <= acbCount; i += 1) {
There's no reason to loop through this list twice. Either get the full list of ACBs using a page object method and then loop, or, in the one loop where you're adding them to this array (and why is that happening this way?) you could check the alphabetical order at the same time

2021-05-18 11:23 UTC, andlar approved these changes

2021-05-18 12:51 UTC, palakpatel311 approved these changes

2021-05-20 13:32 UTC, merged