OCD-3383: Add developer to version activity report
chpladmin/chpl-website pull request #901
Opened 2021-05-13 01:08 UTC by kekey1

2021-05-13 18:40 UTC, andlar requested changes

2021-05-13 18:40 UTC, andlar commented on src/app/pages/reports/versions/versions.html
> +            <th class="search-header" st-sort="developerName" st-skip-natural="true">Developer</th>
When adding a column to the table, the `<thead>` and `<tfoot>` sections need their `colspan` values to increase from the 4 they're set at to 5, so the header/footers span across the entire table

2021-05-16 21:18 UTC, andlar approved these changes

2021-05-18 13:55 UTC, tmy1313 approved these changes

2021-05-26 13:49 UTC, merged