OCD-3586 - Update README documentation for each project
chpladmin/chpl-website pull request #907
Opened 2021-05-24 15:49 UTC by tmy1313

2021-05-24 16:40 UTC, andlar requested changes

2021-05-24 16:40 UTC, andlar commented on README.md
> +* `lint:fix`: Run ESLint against all JavaScript files in the project and fix any errors that ESLint can fix automatically
```suggestion
* `lint:fix`: Run ESLint against all JavaScript files in the project and fix any errors that ESLint can fix automatically. Especially useful when run as `yarn lint:fix src/app/path/to/file.js[x]` to automatically apply fixes against a single file
```

2021-05-25 14:20 UTC, palakpatel311 approved these changes

2021-05-25 14:49 UTC, kekey1 approved these changes

2021-05-25 14:57 UTC, andlar approved these changes

2021-06-01 14:01 UTC, merged