OCD-3492 : AQA tests for rest of 2 charts
chpladmin/chpl-website pull request #911
Opened 2021-06-02 13:34 UTC by palakpatel311

test : AQA tests for rest of 2 charts
[#OCD-3492]

2021-06-02 15:27 UTC, andlar approved these changes, later dismissed

2021-06-02 15:27 UTC, andlar commented on e2e/pages/charts/charts.readonly.spec.js
> +  page;
```suggestion
let hooks; 
let page;
```

I know the auto-fixer does this, but I think it looks terrible...

2021-06-02 16:10 UTC, athomas-git approved these changes, later dismissed

2021-06-02 16:55 UTC, ashwinimore requested changes

2021-06-02 16:55 UTC, ashwinimore commented on e2e/pages/charts/charts.readonly.spec.js
>      it('should only show 2015 edition products', () => {
this test only verifies chart title and not the product edition, I'd suggest updating test description to indicate what it does

2021-06-02 16:55 UTC, ashwinimore commented on e2e/pages/charts/charts.readonly.spec.js
>      it('should have the right options in the "view certification criteria" dropdown', () => {
the label for dropdown is different on Nonconformity chart (not 'certification criteria') - "View the number of Non-conformities with type of Program Requirements Surveilled:" so maybe use something like "View the number of Non-conformities" instead of "view certification criteria"?

2021-06-02 18:21 UTC, ashwinimore approved these changes, later dismissed

2021-06-02 19:03 UTC, athomas-git approved these changes, later dismissed

2021-06-03 11:59 UTC, andlar commented on e2e/pages/charts/charts.readonly.spec.js
> +let hooks; let page;
```suggestion
let hooks; 
let page;
```

The reason the linter changed this in the first place is to make the variable declarations their own statements, for the reasons described in https://github.com/airbnb/javascript#variables--one-const. By moving them back to a single line, but as separate statements, this change does support the reasoning behind debugging, and the thing about forgetting a comma, but it doesn't help with the "adding or removing a variable impacts the rest of these variables in the git diff"

2021-06-03 12:44 UTC, andlar approved these changes

2021-06-03 12:48 UTC, athomas-git approved these changes

2021-06-04 15:09 UTC, ashwinimore approved these changes

2021-06-04 15:10 UTC, merged