OCD-3637: Add AQA test regarding permissions for surveillance
chpladmin/chpl-website pull request #912
Opened 2021-06-03 03:57 UTC by palakpatel311

[#OCD-3637]

2021-06-07 11:52 UTC, andlar requested changes

2021-06-07 11:52 UTC, andlar commented on e2e/components/navigation/navigation.po.js
> +    return $(this.elementselements.reportsToggle);
Looks like a typo. If this is a typo, but the tests are passing, then maybe this element doesn't need to exist at all?

2021-06-07 11:52 UTC, andlar commented on e2e/components/navigation/navigation.readonly.spec.js
> +      login.logoutButton.waitForDisplayed();
Leaving a note here that when the PR for OCD-3546 gets merged, this line will likely need to be removed

2021-06-07 11:52 UTC, andlar commented on e2e/components/upload/upload-surveillance/upload-surveillance.readonly.spec.js
> +describe('when on administration upload page as admin', () => {
I think our general rule is that we want to test the actions that our users will be taking, and usually that means not testing the ROLE_ADMIN stuff as much, as we want to make sure we catch things before ROLE_ACB runs into them

2021-06-07 11:52 UTC, andlar commented on e2e/components/upload/upload-surveillance/upload-surveillance.spec.js
> +  uploadSurveillanceComponent;
```suggestion
let hooks; 
let loginComponent; 
let toast; 
let uploadSurveillanceComponent;
```

2021-06-07 11:52 UTC, andlar commented on e2e/components/upload/upload-surveillance/upload-surveillance.po.js
> +      root: 'chpl-upload-surveillance-bridge',
I'm not sure if there's a better option, but the `*-bridge` elements are temporary things that we hope will go away over time. If it's possible to use something else to scope this element that would be better for long term maintenance purposes

2021-06-08 12:50 UTC, palakpatel311 commented on e2e/components/upload/upload-surveillance/upload-surveillance.readonly.spec.js
> +describe('when on administration upload page as admin', () => {
Added a test for acb as well and kept admin test as onc and admin behavior is different in this case.

2021-06-08 12:50 UTC, palakpatel311 commented on e2e/components/upload/upload-surveillance/upload-surveillance.po.js
> +      root: 'chpl-upload-surveillance-bridge',
I am aware, but there is not other element to go by. when we remove *-bridge , hopefully it will be easy to just remove bridge from the locator.

2021-06-08 12:55 UTC, palakpatel311 commented on e2e/components/navigation/navigation.po.js
> +    return $(this.elementselements.reportsToggle);
Tests were failing on these so fixed typo.

2021-06-08 12:56 UTC, palakpatel311 commented on e2e/components/navigation/navigation.readonly.spec.js
> +      login.logoutButton.waitForDisplayed();
Removed

2021-06-08 18:34 UTC, andlar approved these changes, later dismissed

2021-06-08 21:48 UTC, athomas-git approved these changes, later dismissed

2021-06-23 12:23 UTC, andlar reviewed
Mostly grammar stuff, but I think it's reasonable to have text that's supposed to be able to be read and mean something to be grammatically correct

2021-06-23 12:23 UTC, andlar commented on e2e/components/navigation/navigation.readonly.spec.js
> +  describe('as an ONC', () => {
Suggest

```suggestion
  describe('as an ONC User', () => {
```
or

```suggestion
  describe('as ROLE_ONC', () => {
```

The phrase "an ONC" doesn't make sense, as there's no such thing as a single "ONC"

Same comment with the ONC-STAFF

2021-06-23 12:23 UTC, andlar commented on e2e/components/navigation/navigation.readonly.spec.js
> +  describe('as an Admin', () => {
```suggestion
  describe('as an ADMIN user', () => {
```

or

```suggestion
  describe('as ROLE_ADMIN', () => {
```

Here the problem is that the word "Admin" is not specific to our ROLE_ADMIN, as it generally just means "an administrative user", which in our system could be any logged in user

2021-06-24 14:13 UTC, andlar submitted a review, later dismissed

2021-06-29 14:01 UTC, athomas-git approved these changes, later dismissed

2021-07-06 12:56 UTC, andlar approved these changes

2021-07-07 11:56 UTC, athomas-git approved these changes

2021-07-07 15:26 UTC, merged