OCD-3708: AQA test to add RWT data on listing edit
chpladmin/chpl-website pull request #932
Opened 2021-07-06 19:42 UTC by ashwinimore

2021-07-07 13:04 UTC, palakpatel311 requested changes

2021-07-07 13:04 UTC, palakpatel311 commented on e2e/components/listing/listing.po.js
> +  rwtPlansUrl: '#rwt-plans-url',
Can you move all of these new added changed to e2e/pages/listing/listing.po.js?
I was planning to remove this file once we update upload specs to new UI so going forward we will be using listing page class.

2021-07-07 13:04 UTC, palakpatel311 commented on e2e/workflowTest/edit-listing-test/edit-basic-listing-data.spec.js
> +import loginComponent from '../../components/login/login.po';
loginComponent L needs to be capital

2021-07-07 13:04 UTC, palakpatel311 commented on e2e/workflowTest/edit-listing-test/edit-basic-listing-data.spec.js
> +      browser.waitUntil(() => toast.toastTitle.isDisplayed());
May be good idea to check toaster title to be success or update processing (not sure which one it shows)

2021-07-07 14:09 UTC, ashwinimore commented on e2e/components/listing/listing.po.js
> +  rwtPlansUrl: '#rwt-plans-url',
I was thinking about keeping this component and rename it to listing-edit (?) and use listing.po.js under pages for page objects on listing details page(not edit). Listing edit component can be used on both before and after listing confirm vs. listing page is post confirm. What do you think?

2021-07-07 14:17 UTC, ashwinimore commented on e2e/workflowTest/edit-listing-test/edit-basic-listing-data.spec.js
> +      browser.waitUntil(() => toast.toastTitle.isDisplayed());
I think this is good for this test as the actual data from update is verified after this step and test won't pass unless update was successful. There are failures on some existing tests that expect success and not find the text due to either the toast is missing or has other text, so not adding that check would avoid false failures of those kind

2021-07-07 16:12 UTC, palakpatel311 commented on e2e/components/listing/listing.po.js
> +  rwtPlansUrl: '#rwt-plans-url',
Yes renaming sounds good. I was checking src code and to be consistent with that, can we add this edit component under e2e/components/listing/edit(new folder)?
This will affect existing some of the tests

2021-07-08 14:25 UTC, palakpatel311 approved these changes, later dismissed

2021-07-08 16:09 UTC, palakpatel311 approved these changes

2021-07-08 16:18 UTC, athomas-git approved these changes

2021-07-08 16:23 UTC, andlar approved these changes

2021-07-26 18:30 UTC, merged