OCD-3572 - Add new NON_CONFORMITY_CLOSE_DATE field to CHPL
chpladmin/chpl-website pull request #935
Opened 2021-07-13 15:33 UTC by tmy1313

2021-07-13 18:42 UTC, kekey1 submitted a review, later dismissed
I approve of what I see. I'm wondering if there need to be any changes related to the listing reports and how that displays changes to surveillance activity? To show the new field.

2021-07-14 11:49 UTC, andlar requested changes

2021-07-14 11:49 UTC, andlar commented on src/app/components/components.module.js
> +  .component('chplSurveillanceViewBridge', reactToAngularComponent(ChplSurveillanceView))
This line is the same as the one two lines below, and should be removed

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/edit.html
> +      <label for="non-conformity-close-date" class="col-sm-3">Non-conformity Close Date <span class="text-danger" ng-if="$ctrl.nonconformity.nonConformityCloseDateObject">*</span></label>
```suggestion
      <label for="non-conformity-close-date" class="col-sm-3">Non-conformity Close Date</label>
```

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/edit.html
> +          <input class="input-sm form-control" type="text" uib-datepicker-popup="MM/dd/yyyy" ng-model="$ctrl.nonconformity.nonConformityCloseDateObject" is-open="$ctrl.nonconformity.nonConformityClos
```suggestion
          <input class="input-sm form-control" type="text" uib-datepicker-popup="MM/dd/yyyy" ng-model="$ctrl.nonconformity.nonConformityCloseDateObject" is-open="$ctrl.nonconformity.nonConformityCloseDatePicker" close-text="Close" id="non-conformity-close-date" name="nonConformityCloseDate" ng-model-options="{ timezone: 'UTC' }">
```

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/edit.html
> +        <div class="text-danger" ng-if="$ctrl.showFormErrors && $ctrl.editForm.nonConformityCloseDate.$error.required">Field is required</div>
```suggestion
```

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/nonconformity-view.jsx
> +                    <ChplTooltip title="For non-conformities related to specific regulatory references (e.g. certified capabilities, disclosure requirements, or use of the Certification Mark), the re
```suggestion
                    <ChplTooltip title="For non-conformities related to specific regulatory references (e.g. certified capabilities, disclosure requirements, or use of the Certification Mark), the regulation reference is used (e.g. 170.315(a)(2) or 170.523(l)). If the non-conformity type is designated as 'Other Non-Conformity', then the associated non-conformity does not have a relevant regulatory reference.">
```

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/requirement/edit.html
> +              <td>{{ noncon.nonConformityCloseDateObject ? 'Closed' : 'Open' }}</td>
Should this be the object (`nonConformityCloseDateObject`), or the actual value (`nonConformityCloseDate`)?

2021-07-14 11:49 UTC, andlar commented on src/app/components/listing/details/surveillance/view.html
> +                  <th scope="row"><a href uib-tooltip="For non-conformities related to specific regulatory references (e.g. certified capabilities, disclosure requirements, or use of the Certificatio
```suggestion
                  <th scope="row"><a href uib-tooltip="For non-conformities related to specific regulatory references (e.g. certified capabilities, disclosure requirements, or use of the Certification Mark), the regulation reference is used (e.g. 170.315(a)(2) or 170.523(l)). If the non-conformity type is designated as 'Other Non-Conformity', then the associated non-conformity does not have a relevant regulatory reference." tooltip-trigger="'mouseenter focus click'">Non-Conformity Type</a></th>
```

2021-07-14 11:49 UTC, andlar commented on src/app/services/network.service.js
> -    this.apiGET('/data/nonconformity_status_types')
Is this endpoint marked as deprecated in the controller that provides this data?

2021-07-15 13:59 UTC, tmy1313 commented on src/app/components/listing/details/surveillance/requirement/edit.html
> +              <td>{{ noncon.nonConformityCloseDateObject ? 'Closed' : 'Open' }}</td>
I think it is correct as the `nonconformityCloseDateObject` since that is the value that the UI updates as changes are made.  Then when we save, the `nonconformityCloseDateObject` is converted and written to `nonconformityCloseDate`, which is the correct format expected by the API.

2021-07-15 13:59 UTC, tmy1313 commented on src/app/services/network.service.js
> -    this.apiGET('/data/nonconformity_status_types')
Yes

2021-07-15 16:46 UTC, andlar reviewed
There probably needs to be something in the listing reports file(s) related to showing the changes in surveillance with respect to changes to the Close Date. We probably can't remove whatever was checking on the change of status, for historical purposes, but probably need to add something to show the change in dates (add / remove / modify)

2021-07-15 16:46 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/edit.component.js
> +      if (this.nonconformity.nonconformityCloseDate) {
Should this have the capitalized conformity?

```suggestion
      if (this.nonconformity.nonConformityCloseDate) {
```

2021-07-16 17:18 UTC, kekey1 approved these changes, later dismissed

2021-07-20 17:29 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/nonconformity-view.jsx
> +              { nonconformity.status.name }
> Line 69 is incorrect - it's using the deprecated value.

2021-07-20 17:29 UTC, andlar commented on src/app/components/listing/details/surveillance/nonconformity/inspect.html
> +              <th scope="row">Non-conformity closed date</th>
Should this be 
```suggestion
              <th scope="row">Non-conformity close date</th>
```
to match the tense of the variable?

2021-07-20 23:36 UTC, kekey1 approved these changes, later dismissed

2021-07-22 10:28 UTC, andlar approved these changes, later dismissed

2021-07-22 10:35 UTC, kekey1 approved these changes, later dismissed

2021-08-12 11:23 UTC, andlar approved these changes

2021-08-12 11:54 UTC, kekey1 approved these changes

2021-08-12 14:01 UTC, merged