OCD 3483 : AQA test for view listing details
chpladmin/chpl-website pull request #939
Opened 2021-07-20 17:04 UTC by palakpatel311

2021-07-21 20:04 UTC, ashwinimore requested changes

2021-07-21 20:04 UTC, ashwinimore commented on e2e/components/listing/details/compliance/compliance.readonly.spec.js
> +    it('should display surveillance and direct review activities under compliance activity', () => {
This test only looks for header display and not activities under respective headers. It helps to have description that precisely matches what the test does (suggestion: replace 'activities' with 'sections' or 'accordions' or 'headers' e.g. "should display surveillance and direct review accordions under compliance activity"

2021-07-21 20:04 UTC, ashwinimore commented on e2e/components/listing/details/compliance/compliance.readonly.spec.js
> +    it('should display surveillance and direct review activities under compliance activity', () => {
same as prior comment about test description

2021-07-21 20:04 UTC, ashwinimore commented on e2e/components/listing/details/information/information.readonly.spec.js
> +  it('should not display ATL information', () => {
although this test works for this particular listing because it's a legacy listing and does not have ATL data, the 2014 listings with new CHPL ID format (e.g. 14.04.04.2916.Smar.61.01.0.170411) do contain ATL data and it is displayed in basic listing information section. Therefore I'd suggest either remove this test or use test applicable test data and change test to check for existence of data.

2021-07-21 20:04 UTC, ashwinimore commented on e2e/pages/listing/listing.readonly.spec.js
> +let cmsComponent; let compareComponent; let hooks; let page; let login;
```suggestion
let cmsComponent; 
let compareComponent;
let hooks; 
let page; 
let login;
```

2021-07-22 19:14 UTC, ashwinimore approved these changes, later dismissed

2021-07-22 20:38 UTC, athomas-git approved these changes, later dismissed

2021-07-22 20:44 UTC, andlar approved these changes, later dismissed

2021-07-27 19:26 UTC, ashwinimore submitted a review, later dismissed

2021-07-27 20:38 UTC, athomas-git submitted a review, later dismissed

2021-07-28 19:35 UTC, andlar approved these changes

2021-07-28 20:07 UTC, athomas-git approved these changes

2021-07-28 20:08 UTC, ashwinimore approved these changes

2021-07-28 20:18 UTC, merged