OCD-3716: Add test for onc staff permission to user actions report
chpladmin/chpl-website pull request #946
Opened 2021-08-04 18:56 UTC by palakpatel311

test: Add test for onc staff permission to user actions report

[#OCD-3716]

2021-08-05 14:51 UTC, andlar approved these changes, later dismissed

2021-08-05 14:53 UTC, athomas-git approved these changes, later dismissed

2021-08-17 10:17 UTC, andlar requested changes

2021-08-17 10:17 UTC, andlar commented on e2e/components/cms-widget/cms-widget.readonly.spec.js
> +      assert.equal(cms.cmsIdReverseLookupLink.getAttribute('href'),cmsReverseLookup);
We're switch to `expect`, right?

2021-08-17 13:45 UTC, andlar approved these changes

2021-08-17 13:52 UTC, athomas-git approved these changes

2021-08-17 14:16 UTC, merged