build: update XSD-MODIFICATION trigger file for rwt
chpladmin/chpl-website pull request #956
Opened 2021-08-20 16:36 UTC by tmy1313

OCD-3737

2021-08-20 19:36 UTC, andlar approved these changes

2021-08-21 10:59 UTC, kekey1 approved these changes, later dismissed

2021-08-24 10:17 UTC, andlar requested changes
PR has a merge conflict

2021-08-24 14:27 UTC, andlar commented on XSD-MODIFICATION
> +OCD-3572 - Add new NON_CONFORMITY_CLOSE_DATE field to CHPL
This ticket was already deployed, right?

2021-08-24 15:00 UTC, kekey1 submitted a review, later dismissed

2021-08-24 15:00 UTC, andlar submitted a review, later dismissed

2021-08-30 14:20 UTC, andlar approved these changes

2021-08-30 15:31 UTC, kekey1 approved these changes

2021-08-30 18:20 UTC, merged