OCD 3678: add aqa tests for SED data validation on listing upload
chpladmin/chpl-website pull request #957
Opened 2021-08-20 18:35 UTC by ashwinimore

2021-08-23 13:24 UTC, palakpatel311 approved these changes

2021-08-23 13:24 UTC, palakpatel311 commented on e2e/components/login/login.po.js
>    }
There has been many failure due to changes made to this login component.
Can we please try not to change this and find workaround which may have triggered this to change?

2021-08-23 13:42 UTC, palakpatel311 requested changes

2021-08-23 13:42 UTC, palakpatel311 commented on e2e/components/login/login.po.js
> +    $(this.elements.loginToggle).click();
There has been many failure due to changes made to this login component.
Can we please try not to change this and find workaround which may have triggered this to change?

2021-08-23 13:49 UTC, ashwinimore commented on e2e/components/login/login.po.js
> +    $(this.elements.loginToggle).click();
I am working on it. I am unable to test locally (scrollAndClick() function fails on my local) when I reverse the change. I am going to do it anyway and test it on bamboo

2021-08-24 03:22 UTC, ashwinimore commented on e2e/components/login/login.po.js
> +    $(this.elements.loginToggle).click();
Actually no, the alternate option is needed as the tests failed on QA too..will continue to work on it

2021-08-26 01:38 UTC, palakpatel311 approved these changes

2021-08-26 09:48 UTC, andlar approved these changes

2021-09-09 14:19 UTC, merged