OCD-3714: Authentication updates
chpladmin/chpl-website pull request #964
Opened 2021-09-14 15:57 UTC by andlar

2021-09-16 01:43 UTC, palakpatel311 requested changes

2021-09-16 01:43 UTC, palakpatel311 commented on e2e/components/upload/upload-api-documentation/upload-api-documentation.spec.js
> +    expect(uploadcomponent.apiDocUploadText.getText()).toContain('was not uploaded successfully.');
This assert was to **not** include so expect should be .not.toContain

2021-09-16 01:43 UTC, palakpatel311 commented on e2e/components/upload/upload-listing/upload-listing.spec.js
> +    expect(uploadListingComponent.listingUploadText.getText()).toContain('File has uploaded successfully');
This is additional check added which fails as line #32 is what we have on upload confirmation. #33 needs to be removed. same with #39

2021-09-16 01:43 UTC, palakpatel311 commented on e2e/components/upload/upload-rwt/upload-rwt.spec.js
> +    expect(uploadRwtComponent.fileUploadText.getText()).toContain('File has uploaded successfully');
Same comment as above.

2021-09-16 01:43 UTC, palakpatel311 commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +        expect(count, input.chplProductNumbers.length).toBe('All chpl product numbers aren\'t present in the download file');
This assertion should be  expect(count).toBe(input.chplProductNumbers.length)
same applies to line #72,

2021-09-16 01:43 UTC, palakpatel311 commented on e2e/pages/search/search.readonly.spec.js
> +          page.moreCertificationEndDateFilter.setValue(['01', 'Jan', 'Tab', '2019']);
For some reason, this date particularly getting set as 01/dd/2019

2021-09-16 12:26 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +          page.moreCertificationEndDateFilter.setValue(['01', 'Jan', 'Tab', '2019']);
I ran this locally a few different times trying to get it to go wrong, and every time it continued to pass. I'd lean towards leaving it as is and checking again after our AQA has settled down a bit

2021-09-16 12:30 UTC, andlar commented on e2e/pages/resources/cms-lookup/cms-lookup.readonly.spec.js
> +        expect(count, input.chplProductNumbers.length).toBe('All chpl product numbers aren\'t present in the download file');
Line 72 doesn't have anything about a count that I could see

2021-09-16 17:11 UTC, palakpatel311 commented on e2e/pages/search/search.readonly.spec.js
> +          page.moreCertificationEndDateFilter.setValue(['01', 'Jan', 'Tab', '2019']);
I'd like to keep this conversation unresolved. Hopefully we can check this in QA and before staging we can resolve it.

2021-09-16 17:11 UTC, palakpatel311 approved these changes, later dismissed

2021-09-16 17:29 UTC, andlar commented on e2e/pages/search/search.readonly.spec.js
> +          page.moreCertificationEndDateFilter.setValue(['01', 'Jan', 'Tab', '2019']);
Yep. Leaving a conversation unresolved is a great way to make sure we handle it eventually. We're not supposed to merge any PRs to staging without having resolved each and every conversation, and I prefer to have the original author of the conversation be the one to resolve it, as I feel they're the person whose acceptance of the resolution we need to get

2021-09-16 18:51 UTC, kekey1 submitted a review, later dismissed

2021-09-17 13:51 UTC, palakpatel311 submitted a review, later dismissed

2021-09-17 13:51 UTC, kekey1 submitted a review, later dismissed

2021-09-17 14:06 UTC, ashwinimore approved these changes, later dismissed

2021-09-17 16:12 UTC, tmy1313 approved these changes, later dismissed

2021-09-17 18:36 UTC, palakpatel311 reviewed
Impersonation tests are failing due to login change. Looks like missed those spec in this

2021-09-20 13:25 UTC, palakpatel311 commented on package.json
> +    "chromedriver": "^92.0.0",
chrome version is updated to 93. can you update driver to 93, too?

2021-09-27 16:30 UTC, palakpatel311 approved these changes

2021-09-27 16:56 UTC, kekey1 approved these changes

2021-09-27 17:12 UTC, ashwinimore approved these changes

2021-09-27 20:31 UTC, tmy1313 approved these changes

2021-09-28 13:51 UTC, merged